### ISSUE TITLE
Energy underflow

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#116]
Energy Unit
![qq 20150729165103](https://cloud.githubusercontent.com/assets/5047602/8953587/2796d632-3612-11e5-89c8-27bf339dee80.png)

**Comment by WeAthFoLD** [comment]
How is this triggered? What machine do you put it in?

**Comment by KSkun** [comment]
@WeAthFoLD Advanced Node

**Comment by WeAthFoLD** [comment]
I see. Will fix it in a few days.
