### ISSUE TITLE
SyncAction duplication at player client opening the SyncAction in Client/Server env

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#121]
When in standard client/server layout, when I start an SyncAction at client side, another duplication of it is spawned at client side too. That dummy duplication receives onStart() callback, but nothing else. So when player ends using the ability a dangling SyncAction is left behind.

You can use the CurrentCharging skill in Electro Master to test. I have left the debug print in case you use them.

**Comment by EAirPeter** [comment]
See cn.academy.vanilla.electromaster.skill.CurrentCharging.createSkillInstance(...).new SkillInstance() {...}.onStart()

See cn.academy.ability.api.ctrl.SkillInstance.ctrlStarted()
