### ISSUE TITLE
Render out of bound

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#122]
![qq 20150801162119](https://cloud.githubusercontent.com/assets/5047602/9021218/74536dec-3869-11e5-9529-e8edac126fdb.jpg)
![qq 20150801162127](https://cloud.githubusercontent.com/assets/5047602/9021219/74588200-3869-11e5-99fe-543da531fcda.jpg)
Using Freq Transmitter

**Comment by WeAthFoLD** [comment]
Actually I am just planning to fix this...
