### ISSUE TITLE
Use dirty flag for AbilityData syncing rather than syncing on the fly

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#13]
If player performs multiple actions simultaneously this can be a big network problem. By doing this we can also specify the 'flag check frequency', and thus adjust network syncing frequency.

**Comment by acaly** [comment]
```AbilityData``` has an internally controlled flag ```isInSetup```. While it is true, sync packet will not be sent. When doing multiple actions, just make sure you are in that state. In fact, in most cases when you might perform multiple actions on ```AbilityData```, it will start an in-setup state. 

Maybe an API is needed to manually start an in-setup state from outside.
