### ISSUE TITLE
Use MY render routine for particle and other blend effects

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#145]
to avoid ShaderMod to hack into them.

**Comment by KSkun** [comment]
In order to support other mods fully, we do many improvement and take much time. I'm afraid most of mods will not work on these things.

**Comment by WeAthFoLD** [comment]
Nope, using my routine means no other mods can touch it, which makes it safer.

**Comment by WeAthFoLD** [comment]
By 'my' I mean using raw GL44 call (like glDrawArrays glDrawElements) or GL10 call (glBegin glEnd)

**Comment by KSkun** [comment]
Well, you need to know how hardware supports GL44.

**Comment by WeAthFoLD** [comment]
well, actually using GL10 calls would have the same effect... as long as you don't care about performance.

**Comment by KSkun** [comment]
Performance hhhhhhhhhhh

**Comment by WeAthFoLD** [comment]
Closed via f45138fa4cf5dcee9bc7dd1357cc7fce408cdeec.
