### ISSUE TITLE
Water and blocks render overlay

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#148]
![qq 20150825110123](https://cloud.githubusercontent.com/assets/5047602/9457721/da54267e-4b18-11e5-9973-6d9857d2af75.jpg)
![qq 20150825110140](https://cloud.githubusercontent.com/assets/5047602/9457722/daa4eca8-4b18-11e5-97cd-7eecbf18c78f.jpg)

**Comment by WeAthFoLD** [comment]
sabiMC
