### ISSUE TITLE
[Suggestion] Using GameRegistry.findItem(modId, itemName)?

### ISSUE THREAD

**Issue by 3TUSK** [LambdaInnovation/AcademyCraft#159]
Related line:
https://github.com/LambdaInnovation/AcademyCraft/blob/c9b8e99edf4f61a409ddf1d8226b64bce7d4d251/src/main/java/cn/academy/support/te/TESupport.java#L24
Also, for initializing thermal expansion support, there should be a method in `fml.common.Loader` called ````isModLoaded(modName)````, if so, then I think there is no necessary to [use reflect](https://github.com/LambdaInnovation/AcademyCraft/blob/8b007a997bdb39718aeff42c0fa89cb1b777b743/src/main/java/cn/academy/core/AcademyCraft.java#L135). 
Thus, people can build a dev version *without* adding dev version of thermal expansion. 

Fairly new to modding, if there is something wrong, please forgive me.

**Comment by WeAthFoLD** [comment]
Reasonable suggestion. I'll fix it.

**Comment by liach** [comment]
Oh geez actually ore recipe worths more... ~~You can ignore me if you want~~

**Comment by 3TUSK** [comment]
`ThermalExpansion!=GregTechAPI` I don't think those stuff in te has oredict entry(ies).
