### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by vagaprime** [LambdaInnovation/AcademyCraft#166]
Some of the items are not showing how to craft them when using NEI. for example the Machine frame and the Data terminal both do not show any crafting recipes. I am using NEI version 1.0.4.83

**Comment by WeAthFoLD** [comment]
Your forge version please? It is known that in forge version under 1448, the recipe registry will broken, but it works fine in 1448 and 1492.

**Comment by vagaprime** [comment]
I am using 1448. I have even updated NEI to its latest version for 1.7.10

**Comment by WeAthFoLD** [comment]
Personally Tested with the following setup:

* 1710 Forge 1448
* CCC 1.7.10-1.0.6.43

With some other mods installed (IC2, te, MouseTweaks), and I found no problem.
Can you please provide your mod list and the console output or the log in the Minecraft loading phase?

**Comment by vagaprime** [comment]
Link to my mod list
https://docs.google.com/spreadsheets/d/13WVyKMBs3wSDexM8u18fbpin77VEwHLOjXdLmtoNsRU/edit#gid=523235715

Link to the FML client log
https://drive.google.com/open?id=0B-rHWVN9X53Aa1RUQUVJa2lMN2M

**Comment by WeAthFoLD** [comment]
Whoa, that's a lot of mods installed. I didnt see any problem in the log, so I will probably have to dig deeper into that. Sorry for the inconvenience.
If you have time, can you do me a favor by using divide-and conquer to find out which mod is conflicting? Or if you dont want to that's completely fine, I know it's a boring work. :(

**Comment by vagaprime** [comment]
Ya its a lot of mods but then again that is also my modpack. I can give it a try and rebuild the back from ground up starting with Academycraft. But if I can get the crafting recipes from you I can add them in with mine tweaker for now on the pack pack while I rebuild.

**Comment by WeAthFoLD** [comment]
http://ac.li-dev.cn/wiki/index.php

Currently Chinese only, but there should be no problem iterating through pages and find the pictures xD

**Comment by vagaprime** [comment]
Thank you

**Comment by vagaprime** [comment]
The problem seems to be caused by Open Computers

**Comment by vagaprime** [comment]
Hey. I was just wondering if there has been any progress on figuring out the issue where the recipes become unable to be looked up through NEI. As soon as I add open computers to my pack the recipe for the machine frame and other key items will no longer show up when using the recipe look up key to find out how it is crafted.

**Comment by WeAthFoLD** [comment]
Check this out #199 
I think this issue is essentialy solved along with that one.
