### ISSUE TITLE
JRE7 legacy support

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#169]
Probably just clean up loose ends to let RetroLambda work.

**Comment by FrozenBird** [comment]
I think you can make a new luncher to help other people because someone update the Java,but they still can't open the mod.You can all so make a auto installer to help them.Can you think about my ideas?

**Comment by WeAthFoLD** [comment]
That didn't completely solve the problem. I think we'll try to make the mod compatible with JRE7, if that's not possible, possibly.

**Comment by FrozenBird** [comment]
ok
