### ISSUE TITLE
[Feature Request] Support for IGW-mod

### ISSUE THREAD

**Issue by 3TUSK** [LambdaInnovation/AcademyCraft#171]
As title shown.
[IGW(In-game wiki)](https://github.com/MineMaarten/IGW-mod) is a minecraft mod aiming to provide a internal guide-book so that player can get detailed information very quickly. 
It sounds like a huge chunk of work, but I believe it's ***worth***. If so, players won't switch between their game and browser multiple times.

**Comment by WeAthFoLD** [comment]
Thanks for your interest. We do intend to add in-game mod instructions, but that should not require any mod support. Actually, we have already made a [markdown intepreter](https://github.com/LambdaInnovation/LIUtils/pull/21) that generates lang file. What's left is just rendering it at runtime. As for the form, nothing new but another book maybe. :ice_cream:

**Comment by 3TUSK** [comment]
Or... it won't be a bad idea that AC has its own guidebook and the support of IGW. If there were a pull request for the igw support, will you accept it?

**Comment by WeAthFoLD** [comment]
Definetly! Be my guest if you have interest on this.

**Comment by WeAthFoLD** [comment]
@3TUSK The tutorial system is well implemented into the mod now. The content still needs to be further polished though. Shall we close this issue?

**Comment by 3TUSK** [comment]
Agree, cause I started to work on this instead: http://ftb.gamepedia.com/AcademyCraft

**Comment by WeAthFoLD** [comment]
That seems like going to be very helpful. Thanks for your work in advance! ^^
