### ISSUE TITLE
[Ferature Request] Prevent ability developer being placed if there is no enough space

### ISSUE THREAD

**Issue by 3TUSK** [LambdaInnovation/AcademyCraft#174]
As the gif shown (fps is very very very low but it doesn't really matter):
![testgif](https://cloud.githubusercontent.com/assets/9113033/10413850/0fb4b4d0-6f88-11e5-8a40-bbdee6697d7b.gif)

**Comment by WeAthFoLD** [comment]
Already fixed in d5bdef6a65f8361b926cde4525a029f8f082c88e.
