### ISSUE TITLE
私服中测试出的一些BUG

### ISSUE THREAD

**Issue by YueLengM** [LambdaInnovation/AcademyCraft#175]
无限虚相位液体
用虚相位液体单元右键BC储罐获得盛过虚相位液体的空单元，此空单元右键储罐可再次在储罐中装入1000mb的虚相位液体。不可与普通空单元堆叠。(虚相位液体在储罐中显示为丢失材质-紫黑块)

转移传送技能产生负数量物品
用转移传送技能对10个堆叠量左右的物品使用时有几率触发。最后一个物品并不会随着使用技能而消失，数量继续减少堆叠量变为负数。

金属处理机无法使用
金属处理机只能处理冲压模式，不能处理其他模式。

能力开发机
若甲玩家使用能力开发机时若附近有玩家，附近玩家都会显示该甲玩家的能力开发界面，此时甲玩家进行学习或升级会导致客户端未响应或进度不动。

forge版本：10.13.4.1448-1.7.10
buildcraft 版本：7.1.8
AcademyCraft版本：1.0pr1
服务端版本：KCauldron-1.7.10-1448.133

**Comment by WeAthFoLD** [comment]
了解，会在pr2发布前进行修复的 xD

**Comment by WeAthFoLD** [comment]
Fixed via 698a7cf0c3a5186f8002157c1d51ce6cec78eede.
