### ISSUE TITLE
[Feature Request] Add OreDictionary Names to Ores and Items

### ISSUE THREAD

**Issue by TheLMiffy1111** [LambdaInnovation/AcademyCraft#179]
OreDictionary is a ingame database that nearly all major mods use to let other mods use the item or block easier, for example ore processing. Can the team add names to the ores and the raw materials?
P.S. Please add that also Toaru Majursu no Index is what the mod is based on.

**Comment by WeAthFoLD** [comment]
I will add the OreDict for materials. And I think it's a bit of redundant to add Index because everyone knows that Railgun is a spin-off of it. Also doesn't make much sense because we focus only on super-ability side. Thank you :ice_cream:

**Comment by TheLMiffy1111** [comment]
So will the team add abilities that only appeared in Index

**Comment by WeAthFoLD** [comment]
As mentioned in the README, the mod's inspiration comes from the anime, but it's content is not limited to the background. As long as an ability is interesting enough (and we have time), we might add it regardless of where it comes from.
