### ISSUE TITLE
Dangling SkillStates

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#18]
In many cases, ```SkillState```(generated by ```Patterns```) will not normally end.
For example, when I press M0 and press M1, and then release M0, the skill activated by M0 is still executing.
This is a really serious gameplay issue, better fix it quickly...

**Comment by acaly** [comment]
Some ```Pattern```s do leave the states unfinished, while some others finish them when key is released. Currently only ```PatternHold``` does this.
