### ISSUE TITLE
[REQUEST] Improve RF-support of Current Charging ability

### ISSUE THREAD

**Issue by Nova001Sol** [LambdaInnovation/AcademyCraft#188]
The ability doesn't charge all multiblocks (tested with BuildCraft Additions' Advanced Kinetic Energy Buffer) or items (tested with various items from Redstone Arsenal, Thermal Expansion 4 and Ender IO). It also fails to charge anything from Immersive Engineering (tested with all three capacitors and an Industrial Squeezer multiblock).

**Comment by WeAthFoLD** [comment]
I believe it is already implemented [HERE](https://github.com/LambdaInnovation/AcademyCraft/blob/master/src/main/java/cn/academy/support/rf/RFSupport.java#L39).

But in 1.0pr1 the RF support module is not initialized if ThermalEpansion is not installed. In pr2 the module is always initialized. I remember testing this ability and found no problem charging TE machines.

So please make sure if it still doesn't work in pr2, then I'll see what I can do.

**Comment by Nova001Sol** [comment]
It works with single blocks, but I can't seem to make it work with multiblock devices or items.

**Comment by WeAthFoLD** [comment]
To be exact, what blocks doesn't work with this skill please?

**Comment by Nova001Sol** [comment]
As far as I have been able to figure out? Everything from Immersive Engineering, most multiblocks and all items. Can't really look for more right now, I'm away from my PC at the moment.

**Comment by WeAthFoLD** [comment]
OK, I'll try to fix it when I have time.

**Comment by Wolfseverest93** [comment]
While we are on the topic of RF compatibility, I would like to inform you that for some reason the rf out block doesn't work. I connect it to the matrix, or the node, or both, and have tried everything from fluxducts to thermal expansion energy cells, as well as every item and block that pulls RF energy from blocks that I know of in ender io buildcraft and ae2, and it just doesn't release the energy, if it's converting it.

**Comment by WeAthFoLD** [comment]
@Wolfseverest93 I see. Will look into fixing RF out block.

**Comment by Wolfseverest93** [comment]
Thank you very much! I'll make sure to grab the update asap.

**Comment by WeAthFoLD** [comment]
Fixed RF Out block compatibility via f829ddd8b0993865c613a77e32e45453a0f41bdc.

**Comment by Mastize** [comment]
Indeed it fails to charge capacitors in EnderIO, as I have found in issue #217

**Comment by Mastize** [comment]
RF block support problem should be fixed in 9b4b558

**Comment by WeAthFoLD** [comment]
@Mastize That's a nice addition.

**Comment by WeAthFoLD** [comment]
This issue is too old and contains several problems with some of them being solved. I will close this for now, if there are more problems please open up a new issue.
