### ISSUE TITLE
Academy craft pr 2 is not compatible with Iron_chest

### ISSUE THREAD

**Issue by SlashTodd** [LambdaInnovation/AcademyCraft#190]

**Comment by SlashTodd** [comment]
OK,it's just have conflicts with the bronze-chest,=_=

**Comment by SlashTodd** [comment]
em, its a question about a items,not the iron_chest

**Comment by WeAthFoLD** [comment]
Can you please provide more details for the issue? Not quite sure about what you're encountering.

**Comment by SlashTodd** [comment]
Sorry,the fact is that the mod was worked in my last saves,so there is an id conflicts between one item in two mod versions,and that was stored in the iron-chest,when I open the chest ,the game crashed down.I just made a mistake that the issue is a mod conflicts :(
