### ISSUE TITLE
Issue with RF IN block.

### ISSUE THREAD

**Issue by Wolfseverest93** [LambdaInnovation/AcademyCraft#191]
At least that is what I'm assuming this is. I'm going to both copy the crash report onto a pastebin and give you the direct copy of the .txt file generated. What happened was I accidentally clicked on the rf in block which is below one of my many ae2 crafting terminals, and then tried to open my ae2 network, but instead of reaching for the ae2 console string, it tried to open a gui for the rf in block, which doesnt exist, and in turn crashed the server.

I will attempt to somehow fix this on my end for now, probably by removing the block and placing it somewhere else after extending the fluxducts I had connected to it before. But I felt you should know of this issue as well, so that it can be dealt with on your end as well. We both know that block doesn't have or need a gui. So I'm sure you're just as lost as I am about why it's trying to open one for it.

pastebin: http://pastebin.com/4YXUgcLV

Dropbox: https://www.dropbox.com/s/m0otw7au1f4lk27/crash-2015-10-28_08.30.33-server.txt

**Comment by Wolfseverest93** [comment]
Update: I was right, removing and replacing the rf in block got rid of the error. I still hope that the bug that caused it gets fixed however, as this could likely repeat some time down the road.

**Comment by WeAthFoLD** [comment]
Yes, turns out it's a side judgement mistake that will crash the server. Will fix in next release.
