### ISSUE TITLE
Incorrect oreDict names 

### ISSUE THREAD

**Issue by TheLMiffy1111** [LambdaInnovation/AcademyCraft#195]
oreDict names of resources normally has the name of the type in front of the name and has no underscores.
Corrected oreDict names:
oreConstraintMetal
oreImagCrystalLow
oreImagSilicon
oreResonantCrystal
gemImagCrystalLow
gemImagCrystalNormal
gemImagCrystalPure
ingotConstraintMetal
ingotImagSilicon
gemResonantCrystal
pieceImagSilicon
Others are ok

**Comment by WeAthFoLD** [comment]
yup, camelCase rather than under_score >_>
