### ISSUE TITLE
[Feature Request] Add jukebox tracks and index tracks to media player

### ISSUE THREAD

**Issue by TheLMiffy1111** [LambdaInnovation/AcademyCraft#196]
As the title says, only three tracks is a bit less.

**Comment by WeAthFoLD** [comment]
Currently the major problem is the track size. Each track file is about 3mB and more tracks will cause the mod size to increase dramatically.

I actually plan to do some in-mod track download mechanism, but not too soon (Currently major working on the in-mod tutorial). So more tracks will probably come after that.

Track customization is also planned in case you are wondering.

**Comment by knight-ryu12** [comment]
well, it is interesting.
I think ogg or mp3 will be enough for do it.
(oggs are used in some Mods)

**Comment by WeAthFoLD** [comment]
Implemented in 1.0.0 and will get closed when it is released.

**Comment by knight-ryu12** [comment]
Wow!
