### ISSUE TITLE
Recipes script load error

### ISSUE THREAD

**Issue by Sliprunner** [LambdaInnovation/AcademyCraft#200]
We're having issues with the mod for our (Private) modpack, specifically its not loading the recipes as far as I can tell. I'm not entirely sure whats going on, other then the fact it loads and is even initialized (as its enabled when you check mod listings ingame)...but doesn't actually function at all.

Log Link: http://bit.ly/1MeYjry
(I couldn't upload to pastebin, my log file was to big for my free account >.>)

**Comment by WeAthFoLD** [comment]
You've been using outdated version of LIUtils and AnnotationRegistry.

Pleease download [LambdaLib 1.0](http://minecraft.curseforge.com/projects/lambdalib/files/2263911), which is required by pr2_1.

I have updated the changelog in curseforge in case someone else make this mistake.
