### ISSUE TITLE
Add dependency of LambdaLib in @Mod

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#201]
Which helps version collision detection.

**Comment by KSkun** [comment]
Hey, wolf. You opened 15 days ago, but it is a really small enhancement on \@Mod to only replace a ModID! Why don't you close this first?

**Comment by WeAthFoLD** [comment]
Because it's actually an problem out there, and issue tracker is a way to remind us of problems... Why close it?

**Comment by KSkun** [comment]
Uh, using wrong word.
I mean, why not fix it first. It can be fixed by just some chars.

**Comment by WeAthFoLD** [comment]
Because I'm preparing for test and don't want to touch eclipse...

**Comment by KSkun** [comment]
What can I help for u? Or do u need someone to make the team more active?

**Comment by WeAthFoLD** [comment]
Nope, they are developing other parts of the project. It's complete fine.
The part of reason I didn't do it immediately is because I was refactoring LambdaLib.
