### ISSUE TITLE
晚上睡觉游戏崩溃

### ISSUE THREAD

**Issue by asdw15255** [LambdaInnovation/AcademyCraft#204]
晚上上床睡觉后游戏崩溃然后存档再也打不开了

**Comment by WeAthFoLD** [comment]
请提供崩溃报告，forge版本和已安装的mod列表。

**Comment by asdw15255** [comment]
游戏是闪退，不知道怎么弄崩溃报告，forge10.3.2.1230.mod 

![Uploading QQ截图20151112203819.png…]()
![Uploading QQ截图20151112203831.png…]()

**Comment by WeAthFoLD** [comment]
1448以下可能出现各种预期外情况，请更新一下forge版本 >_>
