### ISSUE TITLE
[Improvement] Rebinding keys

### ISSUE THREAD

**Issue by andrejsavikin** [LambdaInnovation/AcademyCraft#205]
Feature for rebinding keys would be really useful as it would allow a much better workflow of this mod with other mods. It would also to some extent remove confusion for players that use controls menu to actually check controls, like me.
~Sava

**Comment by andrejsavikin** [comment]
Sorry notice the settings in data terminal as I'm just starting out with the mod ;~;

**Comment by WeAthFoLD** [comment]
That's fine ^^ Actually I am considering add a settings to vanilla control menu too. It's more clear this way.
