### ISSUE TITLE
RF Support problem with Current Charging

### ISSUE THREAD

**Issue by Math321** [LambdaInnovation/AcademyCraft#217]
In a creative mode single player world, I used /aim to give myself level 5 and set the mastery level of Current Charging to 100%. Then, I set up a Capacitor Bank from Ender IO next to an Energy Bridge (CoFH Out) from Academycraft.

When I used Current Charging on the Capacitor Bank directly, it charged at 7 RF/t.
When I used Current Charging on the Energy Bridge, the Capacitor Bank charged at 120 RF/t.

7 RF/t seems very low. I'd expect the two numbers to both be 120 RF/t. Is this a bug, or intended?

**Comment by Mastize** [comment]
We expect that the value should be quarter (i.e. 30RF/t) if don't use energy bridge. However, I found that Current Charging doesn't work on Capacitor Bank directly in latest version , thus there are some problem in RF support.

**Comment by Mastize** [comment]
Check issue #188 please

**Comment by Mastize** [comment]
fix in 9b4b558
