### ISSUE TITLE
Advanced Ability Developer giving io.netty.channel.embedded.EmbeddedChannel recordException

### ISSUE THREAD

**Issue by Alaberti** [LambdaInnovation/AcademyCraft#221]
Noticed this issue in my fml client console when I'm near an advanced ability developer: http://pastebin.com/j9XbdWjv. Removing the developer stops it from spamming the console.

**Comment by WeAthFoLD** [comment]
Yes.. I have noticed it, and will investigate further when I have time.
Duplicate with #207 .

**Comment by Alaberti** [comment]
Thank you, and my apologies.
