### ISSUE TITLE
When fire Railgun at Electromaster skilltree in SMP, Cooldown will shared

### ISSUE THREAD

**Issue by knight-ryu12** [LambdaInnovation/AcademyCraft#223]
see title. 

No crashlog about that. it might be Code side.
If it's default, let me know.

**Comment by WeAthFoLD** [comment]
I remember solving that issue once before... Your AC version please?

**Comment by knight-ryu12** [comment]
1.0pr1
2015/12/23 23:51 "WeAthFoLD" <notifications@github.com>:

**Comment by WeAthFoLD** [comment]
Try pr2 then :)

**Comment by knight-ryu12** [comment]
Oh. Thanks! (Is it fixed?)

Ah Btw. I am Japanese
