### ISSUE TITLE
Make Teleporter entity mark display across walls

### ISSUE THREAD

**Issue by sfmiyuki** [LambdaInnovation/AcademyCraft#226]
我在试用这个能力时发现它并不能使持有的物品穿墙传送到对面，但是可以隔墙攻击生物。
但攻击生物时的时候瞄准特有的红色框框不会显示(被墙体阻挡)。
请问可以隔墙攻击生物是特性吗？如果是，希望能让瞄准红色框框改成可以隔墙显示；如果不是，希望能修正

**Comment by WeAthFoLD** [comment]
可以隔墙攻击生物。锁定框的显示会在接下来的版本修正的。
