### ISSUE TITLE
[1.0pr3] Wind Generator GUI wireless icon misplacement

### ISSUE THREAD

**Issue by Shykel** [LambdaInnovation/AcademyCraft#228]
I had major problems configuring the wireless connection of the wind generator. Upon disabling NEI, i noticed that the wireless icon is hidden unusually far to the right of the screen (AcademyCraft-1.0pr3)

**Comment by WeAthFoLD** [comment]
Thanks, I'll check when I have time. For now you can use the Freq Transmitter in the Data Terminal.
