### ISSUE TITLE
Crash a server

### ISSUE THREAD

**Issue by PalePyth** [LambdaInnovation/AcademyCraft#233]
After installing your mod I see this on my server: http://puu.sh/mpqPl/84d4f0835d.png
Logs: http://pastebin.com/74a8qBXr
SMP works fine.
KCauldron-1.7.10-1614.UNOFFICIAL

**Comment by Schrubbls** [comment]
yea got that one too 
http://pastebin.com/hMpy4JJ6
i guess i have to still use the pre2 version

**Comment by WeAthFoLD** [comment]
Indeed. Looks like pr3 has some really serious problems. I'll look into them as soon as I have time. For now use pr2_1 please, sorry :-)

**Comment by PalePyth** [comment]
It doesn't work too.

**Comment by WeAthFoLD** [comment]
@PalePyth Your paste contains only a very small portion of the log, which makes it impossible to track down the problem. Please paste the whole log (or crash report).

Also pr2_1 really doesn't have any problem on installing. You might have to confirm that you are using Java8 and have [LL1.0](https://github.com/LambdaInnovation/LambdaLib/releases/tag/1.0) installed.

**Comment by PalePyth** [comment]
It's really so! WOW! The great mod!
