### ISSUE TITLE
[1.0pr3] Outright crash in server, caused by ref to Vector2f

### ISSUE THREAD

**Issue by thephoenixlodge** [LambdaInnovation/AcademyCraft#236]
Crash Log here: http://pastebin.com/mKfMPK44
Bit more info can be read about what might be causing this here: https://twitter.com/BlayTheNinth/status/686101539753201664

This was found after the mod was incorporated into the Regrowth mod pack, resulting in the server side of the pack being completely broken is a bit of a hindrance.

**Comment by Schrubbls** [comment]
yea we all have this problem you can use the pre 2 for now with the lambdalib 1.0 then it will work just as fine

**Comment by WeAthFoLD** [comment]
Confirmed. Will fix it in a bugfix release, which will hopefully out in next week.

**Comment by WeAthFoLD** [comment]
Fixed in 1.0pr3.
