### ISSUE TITLE
[1.0pr3] BlockAbilityDeveloper crash in server

### ISSUE THREAD

**Issue by KomeijiRin** [LambdaInnovation/AcademyCraft#237]
https://bpaste.net/show/f711e73d8ff2
懒得打英文了……单机正常 放到服务端上和EU冲突了貌似?

**Comment by liach** [comment]
Full log. Seems to be extra utilities bug.

**Comment by KomeijiRin** [comment]
https://bpaste.net/show/5979e95b56c8
多次调整过EU的版本 都没有效果 
单机部分正常工作
AC和EU只装其中一个的时候都是正常工作的

**Comment by liach** [comment]
EU的问题吧……话说能不能不看渲染分类就判定某个方块是不是栅栏？爆的原因是EU在服务端上查找一个ac方块的渲染种类。

**Comment by WeAthFoLD** [comment]
是由于在服务器端加载类时method validation访问了`RenderEmptyBlock`所致。对`getRenderType`方法打上SideOnly就好了。

下个bugfix版本会修复的。
