### ISSUE TITLE
[1.0pr3] Metal Former recipe of resoCrystal is in-out reversed

### ISSUE THREAD

**Issue by 3TUSK** [LambdaInnovation/AcademyCraft#238]
https://github.com/LambdaInnovation/AcademyCraft/blob/master/src/main/java/cn/academy/crafting/ModuleCrafting.java#L224

Looks like the `oreResoCrystal` and `resoCrystal` are *switched* into wrong place.
Reference:
https://github.com/LambdaInnovation/AcademyCraft/blob/da732e2f57bcbb09cd03e9c102fc264331e9dc0e/src/main/java/cn/academy/crafting/api/MetalFormerRecipes.java#L58

**Comment by WeAthFoLD** [comment]
Indeed. Thanks 4 pointing out, will fix soon :I
