### ISSUE TITLE
有了空间系的能力，怎么可以没有时间系的

### ISSUE THREAD

**Issue by Jiumosi** [LambdaInnovation/AcademyCraft#243]
不要太变态，定住对方一到两秒，还有给自己加速，不是吃加速药水那种，要像子弹时间的那种，别人都很慢，只有我很快，这两个好像都比较难实现哈，没关系，加油，很喜欢这个mod

**Comment by WeAthFoLD** [comment]
谢谢你的建议，我们会考虑的:) 不过请注意一般性的内容建议不适合在github提出，可以发邮件。
