### ISSUE TITLE
Loading crash

### ISSUE THREAD

**Issue by PalePyth** [LambdaInnovation/AcademyCraft#244]
The game says me I need coFHLib. Okay. Then says I need LIUtils. Then AnnotationRegistry. And finally after this steps I get a crash.
http://pastebin.com/yPB0kGG0

**Comment by 3TUSK** [comment]
Please use LambdaLib, **not** LiUtils+AnnotationRegistry.
LambdaLib can be found on curseforge.

**Comment by PalePyth** [comment]
I use it too!

**Comment by 3TUSK** [comment]
Ah I see it, but you should not use LambdaLib with LiUtils+AnnoationRegistry at the same time, though.
