### ISSUE TITLE
Config Option to Move the GUI

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#245]
My friends and I are making a server, and we're using FTB Infinity Evolved as a base. We added AcademyCraft and Nevermine/Eternal Isles/Advent of Ascension/whatever its changed its name to, and they both put a gui in the top right corner. Neither currently has a method to adjust the location of their respective GUI's, and it's quite annoying having the CP bar covered by Nevermine's... whatever the bar is, I don't know. Being able to reposition where the CP bar renders would be helpful for that. My friend has recommended perhaps checking out how Ars Magica 2's GUI repositioning works, but adding an app to the terminal could be cool.

**Comment by WeAthFoLD** [comment]
Aye, actually I also have this in mind. Will do this probably in next few releases.

I'm also considering adding a standalone GUI for tweaking the position.
