### ISSUE TITLE
发现一个无限刷硬币的BUG。Unlimited access to Coin of BUG

### ISSUE THREAD

**Issue by Northwhite** [LambdaInnovation/AcademyCraft#247]
1.首先准备两组的硬币，装备在快捷栏中
2.第一组若干硬币，第二组64个满硬币
2.抛起第一组的一个硬币，在硬币落下之前滚轮切换到第二组
然后就谜一样的在物品栏获得了2个硬币。重复步骤可无限获得
发现BUG的版本：
LambdaLib-1.1.0
AcademyCraft-1.0pr3
Minecraft-1.7.10-Forge10.13.4.1558
Java8_u66
我服务器的一个玩家无聊抛硬币发现的，不清楚有没有人提交这个BUG

**Comment by 3TUSK** [comment]
标题不应该是Duplication of coins bug吗...

**Comment by Ahrwing** [comment]
这bug... 总感觉似曾相识。

**Comment by KSkun** [comment]
Fixed on #255
