### ISSUE TITLE
[Feature request] An end-game ability/device that allow player recharge power faster

### ISSUE THREAD

**Issue by 3TUSK** [LambdaInnovation/AcademyCraft#249]
https://www.reddit.com/r/feedthebeast/comments/42lkgd/academycraft_any_ways_to_change/

Edit: From my point of view, such an/a ability/device should be in end-game; otherwise it's too op.

**Comment by WeAthFoLD** [comment]
Interesting. Actually that we have a different design that tries to ease this cp-deplete issue -- the medicine system, through which player can craft(brew?) medicine that have effect related to abilities, such as CP recovering as you stated. It's still in early developement thou :I

**Comment by WeAthFoLD** [comment]
Closed as the issue doesn't lead to further disscussion.
