### ISSUE TITLE
All network info is cleared if a matrix or node is moved by a frame from Funky Locomotion

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#250]
I'm working on a special modpack where you are in a void world and the base you spawn on is a frame machine, and is moving through the world. Since frames have a limit on how many blocks you can move, I have included AcademyCraft for its wireless power transfer (saves block count considerably) as well as the eu and rf conversion. However, I have found that whenever a frame moves either the matrix or the node, they both lose any network data they have stored. The matrix loses its SSID, the nodes lose they're name and everything disconnects. I'm thinking this data is stored based on location, since power stored is maintained, and if that's the case there's not much to be done, but I really wanted this in. 

Not sure if this should go in a second post, but moving only one block of the matrix causes the other blocks to be removed (no hit box) while the moved one still exists. Interestingly enough, it otherwise works perfectly fine, and even renders properly. But placing transparent blocks where the rest should be will render the structure inside those blocks. I'm impressed it didn't crash though. I thought that would end far worse then it did, so I commend you on that.

If you care for a heads up on pack inclusion, this would work too probably.

**Comment by WeAthFoLD** [comment]
Please submit another issue for the matrix problem :)

And yeah, the network data is currently stored based on block location. It can be modified so that network is stored based on per TileEntity, and that might possibly even be a good approach! But we will not work on energy system for some time, so this idea will be suspended.

**Comment by Renniuq** [comment]
I'll go make that new issue right now. With screenshots to boot!
