### ISSUE TITLE
Incompatibility with Data Terminal when also using CosmeticArmorReworked mod 

### ISSUE THREAD

**Issue by Alaberti** [LambdaInnovation/AcademyCraft#257]
SAOUI Version: saoui-1.7.10-1.4.a
- http://minecraft.curseforge.com/projects/sao-ui/issues/16

AcademyCraft-1.0pr3_1

I have mentioned this to the SAO UI team as well. With these two mods being used together, the Data Terminal GUI will not display, but does work (if you click in the right places, you can access other GUIs).

**Comment by Alaberti** [comment]
CosmeticArmorReworked is the mod causing the problem, not SAO UI.

**Comment by WeAthFoLD** [comment]
Will look into it when have time.

**Comment by Alaberti** [comment]
After several more rounds of testing, discovered it was a corrupted config file. I apologize for not testing further before opening the issue.
