### ISSUE TITLE
Can'

### ISSUE THREAD

**Issue by Utildayael** [LambdaInnovation/AcademyCraft#274]
This may be user error....

I can only seem to use the base level 1 skill as a Meltdowner. If I try barrage or shield it immediately goes overloaded! I figured ok maybe need more levels but I'm level 4 now and still can't use either of those skills, same deal. Overloaded.

Am I miss a step or is that just not working currently? 

Thanks :)

**Comment by WeAthFoLD** [comment]
There are some skill data miscalibrated in some previous versions. I believe that it has be fixed in 1.0pr3_1 mostly. If you still have problem on some skills, please list them out. We'll fix it.

**Comment by Utildayael** [comment]
Excellent news! I'm using the Regrowth mudpack and they still have 1.0pr2 included so hopefully he updates that soon in the pack.

Thanks :)
