### ISSUE TITLE
[1.0pr3_1] Rail Gun & Magnetic Manipulation

### ISSUE THREAD

**Issue by HalestormXV** [LambdaInnovation/AcademyCraft#280]
Two issues running on this version. 

The Rail Gun ability does not work or trigger. You have the coins in your inventory and when click the hotkey assigned to it, nothing happens. I have tried assigning multiple hotkeys just to test if it was the hotkey assignment and still same result.

Magnetic Manipulation - Does not allow you to throw blocks. The only thing you can do with it is when you have a conductive block in your hand you can use the ability to increase movement speed and then when you stop casting it consumes the block. I am not sure if this was the intention or not.

**Comment by HalestormXV** [comment]
After doing some testing here is an update. If you are in ability using mode it doesn't work period. However if you exit ability use mode and you right click with the coin in your hand you crash with an internal server error. Here is the error message:

http://pastebin.com/66dnR0Xw

It appears to have something to do with the updated LamdaLib.

**Comment by WeAthFoLD** [comment]
Both skills are rewritten so same error shouldn't be expected in next version.
