### ISSUE TITLE
[1.0pr3_1] Transport Use

### ISSUE THREAD

**Issue by IceLagTun** [LambdaInnovation/AcademyCraft#281]
Horse: Data Menu not working; Ability Menu not working
Minecart: Ability Menu not working
Boat: Ability Menu not working

**Comment by WeAthFoLD** [comment]
I see. Will fix in next release.

**Comment by WeAthFoLD** [comment]
Well I can't reproduce any of them in current dev branch. Not sure in pr3_1, but should be fine in next version.
