### ISSUE TITLE
Feature: Coins will return a heads or tails result

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#282]
Now, I know these items mainly exist for the Railgun ability (in fact,exclusively, right?) but having the flipping animation and everything I thought it would be cool if, say, you don't fire it with the railgun, then when it lands back in your hand, perhaps it could in some way indicate whether it landed heads or tails.

Just thought it would be a relatively simple task to implement (I think, let me know if i'm wrong) and would be nifty when you want to, well, flip a coin.

**Comment by WeAthFoLD** [comment]
A interesting addition. How about adding an `Heads or Tails` option in Data Terminal, and send the result as chat message to player when it lands?

**Comment by Renniuq** [comment]
That sounds cool, I feel like the data terminal needs more uses, while it isn't useless or anything right now, it feels like it could be more fleshed out, you know? I like it though.
