### ISSUE TITLE
Magnet Manipulation Causing Weird Fall Damage

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#284]
With the magnet manipulation, If you pull yourself to the ceiling, drop down, and then use magnet manipulation to slow yourself down, even if you barely graze the ground, you still take the full damage as if you had simply free fallen.

From my knowledge of the game, I happen to be convinced that this is due to the way minecraft handles fall damage, where its calculated based on distance fallen rather entity speed when hitting the ground. I know this has caused problems with methods of flight throughout the game's development, both modded and not. I don't know if there's any way to fix that reliably, but It's rather annoying when you barely tap the ground with a toe and then explode into a million items from falling "really far."

Just thought I'd point it out if it could be fixed.

**Comment by WeAthFoLD** [comment]
Are you sure it isn't magnet movement? Anyways this is a reasonable enhancement.

**Comment by Renniuq** [comment]
Ah, yes, got the names of those two switched around again. Not sure why I have so much trouble with those two in particular... =/
