### ISSUE TITLE
高速闪现同时按下多个方向键会出现无法消除的实体——残留

### ISSUE THREAD

**Issue by codehz** [LambdaInnovation/AcademyCraft#285]
![image](https://cloud.githubusercontent.com/assets/13158903/13547844/5aacc5d8-e31c-11e5-9681-fc7f5cd891c7.png)
如图所示，重新进入世界后恢复

**Comment by WeAthFoLD** [comment]
已确认，下个版本会进行修复

related commit: 08004dc8690428913f4439271cb25e6ffa5bcc88
