### ISSUE TITLE
Media Player volume not able to be changed

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#287]
Pretty self explanatory, the only way to make it quieter is to turn down the master volume, and that doesn't really help when you want to turn it down so you can hear the rest of the game. Also maybe just having it be a bit quieter in general could be good, its a little much as is. I think this would be especially useful when you get to adding the normal records, or the media system I hear you are thinking about.

**Comment by WeAthFoLD** [comment]
This is an useful feature that many people have mentioned. Since we are re-working that part, I think it's appropriate to implement it right now and add it in next version.

**Comment by WeAthFoLD** [comment]
Done. b17a6ecb32b1e01e0079c354404f54a404fe3fb2
