### ISSUE TITLE
Metal Former resets mode on chunk reload

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#291]
Rather simple, if you set the metal former to be in say, etching mode, then reload the chunk by either go far enough away or relogging, it goes back to plate crush mode. Kinda annoying cause I want to automate etching data chips with AE but that makes it impossible. also happens with incising and refining modes.

**Comment by WeAthFoLD** [comment]
Already fixed in ff861e92b4b33fd38f3cfa33fe43db7256844179.
