### ISSUE TITLE
Message uses wrong encoding in linux

### ISSUE THREAD

**Issue by skydark** [LambdaInnovation/AcademyCraft#295]
![http://imgur.com/05zcq3W](http://i.imgur.com/05zcq3W.png)

**Comment by WeAthFoLD** [comment]
@ShieLian

**Comment by ShieLian** [comment]
Change the encoding of zh_CN.lang in LambdaLib from CRLF UTF-8 to LF UTF-8 at [e07e939](https://github.com/LambdaInnovation/LambdaLib/commit/e07e9394acfc9c194d115fb3875225580d1697b7) in LambdaLib. You can replace the lang file manually to check whether  it works or not.

**Comment by skydark** [comment]
@ShieLian 
I have cloned your LambdaLib repository and the lang file is encoded by gb2312/gbk.
It should be utf-8 [instead](http://www.minecraftforge.net/wiki/Localizing#Lang_file).

After I converted `zh_CN.lang` to utf-8 manually it works. Thank you and @WeAthFoLD for your help!
