### ISSUE TITLE
[1.0pr3_1] [严重]发现一个利用机器可刷任何物品的BUG

### ISSUE THREAD

**Issue by Northwhite** [LambdaInnovation/AcademyCraft#299]
上次我服务器里那个发现抛硬币BUG的玩家已经升为管理了，这次我和他发现了个更为严重的BUG，如题
由于这个BUG的严重性，应该还没人发现，所以我不方便细说
利用虚能融合机，金属处理机，甚至风力的主机，只要能放东西进去的都行，
服务器和单机经测试都可以刷，大致就是经过几个步骤复制一个你放进去的物品，无论放多少一次只能复制一个
考虑了很久要不要公开BUG，毕竟不是刷硬币那么简单
请问一下如何在不公开的情况下提交

**Comment by WeAthFoLD** [comment]
请发送一封邮件到 feedback@li-dev.cn 说明bug的相关情况，感谢提供反馈

**Comment by Northwhite** [comment]
已发送 希望AC越做越好

**Comment by Northwhite** [comment]
然而1.0.1也并没有修复 药丸..

**Comment by WeAthFoLD** [comment]
莫急 锅太多 一个一个端 :shaved_ice:

**Comment by Mastize** [comment]
@Northwhite 这个比较难发现，所以优先更紧急的Bug了……请谅解0.0

**Comment by ShieLian** [comment]
实际上这种bug很多mod都有。。┑(￣Д ￣)┍

**Comment by Northwhite** [comment]
@ShieLian 对 每个mod我都试了一遍，只要破坏后GUI能关闭，基本都没事。主要是服务器里已经有人用AC和其他mod搭配刷东西 实在防不胜防

**Comment by Mastize** [comment]
~~然而此时LI的策划们正在疯狂脑洞新内容，药丸~~
