### ISSUE TITLE
Not Support to old graphic cards

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#30]
On the platform with old graphic cards, GUIs' drawing become wrong.
The problem will only be at big GUIs.

Test Platform:
Graphic Card: GeForce G 105M
Driver Ver: 332.44

**Comment by WeAthFoLD** [comment]
Can't reproduce the problem. This is put off until someone really encounters and was bothered by the bug.

**Comment by KSkun** [comment]
Another Platform:
Graphic Card: Intel GMA 4500
Driver Ver:

**Comment by KSkun** [comment]
Another Platform:
Graphic Card: Nvidia GeForce 9600 GT
Driver Ver: 9.18.13.2049

**Comment by KSkun** [comment]
Another Platform:
Graphic Card: Nvidia GeForce GT 240
Driver Ver:
