### ISSUE TITLE
Improve metallic block testing

### ISSUE THREAD

**Issue by 3TUSK** [LambdaInnovation/AcademyCraft#301]
![image](https://cloud.githubusercontent.com/assets/9113033/14584767/017215f2-0425-11e6-99ea-a8bd0803b520.png)

http://tieba.baidu.com/p/4483460396

**Comment by WeAthFoLD** [comment]
Indeed a bug. At the beginning we are casual about deciding whether a block is metallic or not. I guess at least a table for all vanilla blocks is needed :shaved_ice:

**Comment by WeAthFoLD** [comment]
About this, actually I've came up with an interesting idea. Remember the Misaka clones' goggles? I think they can be implemented as a way to identify the metal blocks acknowledged by the mod.

**Comment by Mastize** [comment]
Serious? I believe someone confuses Magnet **Movement** and Magnet **Manipulation**. Iron Block works fine in both skills, and indeed you could use Magnet **Movement** to fly to Stone or Nether Block after your Magnet **Movement** has get enough exp. And I think it is proper.

**Comment by 3TUSK** [comment]
@Mastize Essay topic "To what extends does improper translation misleading interpretation" confirmed

**Comment by Mastize** [comment]
@3TUSK  I talked with WeAthFoLD just now, and I believe he fixes this problem somehow in that refactor, lol

**Comment by 3TUSK** [comment]
Well I just feel sad on people's abusing *features*.
