### ISSUE TITLE
Default Font maybe invalid in some platform

### ISSUE THREAD

**Issue by ShieLian** [LambdaInnovation/AcademyCraft#303]
M$ Yahei will not be available in win which uses Chinese. (and Japanese?
微软雅黑 may also can take effect in win which uses English. (and Japanese?

**Comment by ShieLian** [comment]
Also, the encoding of the cfg will magically change, causing 微软雅黑 turns into ΢���ź�

**Comment by WeAthFoLD** [comment]
Can't replicate the bug, issue closed :-)
