### ISSUE TITLE
[1.0pr3_1]重新进入游戏导致熟练度重置的bug 

### ISSUE THREAD

**Issue by Raindet** [LambdaInnovation/AcademyCraft#304]
每次重新进入地图后原有的熟练度都会重置，释放技能几下就过载

但是在学习机中看到的熟练度仍然是原来的数值。

没试过单独安装AcademyCraft有没有这个bug。

Forge版本 1614

**Comment by Mastize** [comment]
能否举个具体的例子？，比如使用什么能力系的什么技能会发生熟练度重置？我这边挑了几个技能测试了下，应该是正常的
