### ISSUE TITLE
[1.0.0] crash on world load after updating mod :( 

### ISSUE THREAD

**Issue by monkeybee11** [LambdaInnovation/AcademyCraft#315]
it says something about ac:item_item is no longer in this world do u still want to play?
then after clicking yes this happens 
http://pastebin.com/5GVJGMwa

**Comment by WeAthFoLD** [comment]
Don't use 1.0.0 on old world, open a new one. No compatibility is guaranteed.

**Comment by monkeybee11** [comment]
ah oki ...woud of been a good warning to add when u start up the game or something :P oki wont be updating the mod for a long time then thx for the info ^_^
