### ISSUE TITLE
关于“矢量操作"能力的一些建议

### ISSUE THREAD

**Issue by sfmiyuki** [LambdaInnovation/AcademyCraft#319]
很高兴看到你们终于开发出了这玩意...虽然有些地方看得不尽人意，不过大体上能看的去（也许是你们想做好但是心有余而力不足，不是代码上而是创意上）。这里我提的是一些比较让我不满的地方
血液逆流是怎么对骷髅造成伤害的...想弄一些很厉害的伤害技我可以理解。但是这也要符合常理，况且你们设置的"致命性伤害"也仅仅是相对于原版怪物的。希望做成对特定类生物达到秒杀的效果"不仅限于大量伤害“而是代码上的杀死。并对特定类型的怪物失效

 "矢量反射"仅仅是将受到的伤害同等量的给予攻击者，但自身也会受伤。也许是我偷懒没用代码改熟练度的缘故，但这与初衷是绝对不符的（根本就是war3100%反弹，事实上玩过魔兽RPG都知道100%反弹并没有什么卵用）。可以参考一下苹果奶茶2(Applemilktea2)中反射buff的代码（对方收到同等伤害，自身不受伤），这样才有矢量反射的样子。而且矢量反射的消耗也是够高，建议将消耗大小设置为根据反射伤害的量决定，平时可以几乎无损的使用能力

以上就是我的一些牢骚。本人对代码是一窍不通的，在github混也就是偶尔插手弄个本地化什么的，如果提出了什么不合理的建议还希望能够谅解。

**Comment by Mastize** [comment]
我个人而言，对您说的两点是不太同意的。以下仅代表个人意见，不代表团队中其他人看法。

您说的两个问题完全是设定上的事情，并不涉及代码层面。

先来说血源逆行。我查看了下团队的设定文档，血源逆行绝对没有涉及任何“秒杀”的因素。它纯粹就是一个单体高伤技能（即使零熟练也足以秒杀一般怪物），然后叫这么个名字，并弄上了流血的动画效果，比如你可以试试用零熟练度的血源逆行攻击末影人，是不能一击杀死的。而在MC中，所谓骷髅、僵尸说到底也就是个游戏的模型，本身没有“是不是有血”这种设定。个人认为希望把游戏的每个技能都弄得很合情合理或者很合乎科学道理是没太大意义的。如果是指与技能的名字或动画效果表现不符的技能，我相信马上可以在War3或者其他经典游戏里找出一打。

再说矢量反射，同样我看了眼团队的设定文档，并且私下实验了一番确认了下，其实反射率这个玩意是跟熟练度挂钩的。在你刚学会这个技能的时候确实是自己也会受伤，当你熟练度逐渐上升以后就会免伤甚至是反弹率超过100%。我个人认为这个设定是没太大问题的。

至于矢量反射消耗大，我认为这也合情合理，因为反射本身就是比较强的技能。如果按照您说的改成根据反射伤害的量决定，而不是现在开着就消耗，那直接结果就是玩家可以一直开着这个技能而没有任何消耗，直到受到攻击，换句话说就是大家都不敢打矢量能力者了（你可以想想目前的技能伤害量和玩家血量）。这么改不是不可以，但是那就必须让CP的消耗变得非常大以防止玩家无脑开反射……那我个人猜测其实最终结果还是矢量不敢随便开着反射。

当然，矢量作为一个新的能力系，有各种各样的问题也是在所难免。事实上团队内部就因为矢量的技能发生过多次争论。我们承认因为能力有限，团队目前对于能力系的策划是比较不平衡的，但也绝对不是随性乱来。

我们欢迎玩家们提意见，但是希望当您真心想提一个意见的时候，也要做足功课。比如血源逆行到底是不是“秒杀”，矢量反射到底是不是真的不能免伤，相信您是可以私下测试出来的。事实上我们团队现在就深受一些奇怪的建议、bug报告所困扰。

**Comment by FreezeIce** [comment]
感谢你们能花费时间来制作这个mod，为我们带来别致的游戏体验。
对于"矢量反射"这个技能我想提一下自己的看法。"矢量反射"这个技能能完全反射远程伤害，但对于近程伤害只能单单反弹“伤害”，而并不能反弹击退效果。下面针对于"击退"说一下：
“矢量操作”这个技能整体上来看，是这个mod中唯一一个偏向近战的能力，贴着别人的脸才可以打出伤害；并且，四个伤害技能(除"电浆炮")，没有一个不是需要蓄力的，这就让“矢量操作”的近战能力更加鸡累，被攻击后镜头摇摆，距离拉远，还有技能不好锁定目标，这让释放技能难度大大提升。“踏击导向”这个技能在空中无法释放，也就是说在击飞段无法释放，实测，在僵尸围攻时，这个技能根本放不出来，只能逃出去对准再放；"定向冲击"单体伤害，只能先手；“集束冲击”是个AOE，还凑合；"血源逆行"可以不用蓄力释放，这在战斗中还稍微有点优势，不过是单体。实测level5，所有技能满级（不带装备），用这几个技能还打不过一群僵尸。"矢量反射"的"最强"并没有体现出来.....
“矢量操作”这个技能不能像动作游戏一样爽快的近战，那么就需要一个稳定的输出环境。所以，"矢量反射"这个技能释放时(满熟练度)，最好能稳定的站下脚，不被打飞（苦力怕，TNT，击飞），最好能保持自身下面的一个方块不被破坏为好，做到真正反射一切的效果。(这样效果看上去也好)
Ps：魔法禁书目录的一方通行的矢量反射本身就是反射一切的......当然幻想杀手除外...
另外一点，如果"矢量反射"这个技能，再从高出掉下来后，对周围有冲击力，造成伤害，那就更好了。
这都是我个人的观点，有什么不合理的地方，请谅解，希望能继续讨论。
