### ISSUE TITLE
Vector Manip Directed Shock can punch Spiders through 1 block ceilings.

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#320]
I've managed to do this 3 times now, every time a spider is hanging near the top of a wall, if I punch with my maxed Directed Shock, it pops right through the ceiling onto the roof.

**Comment by WeAthFoLD** [comment]
I had to say that this is very... unfixable. The skill did never altered the attacked entity's position, but only changed its speed. I guess it's Minecraft's physics calculation is to blame.

**Comment by Renniuq** [comment]
You're asking me if I find it very unsatisfying that I can punch spiders so hard they phase through the ceiling? No, I don't, in fact I kinda enjoy it a little. It's definitely not as annoying as the magnet movement fall damage thing I reported a while back (and come to think of it, I still need to test if the fix worked right. I assume it did, but I'll put it on the list), it simply clearly struck me as at least an unintended effect. In my case its not an issue, I could see some where it would be, but its not a high priority thing. I will admit Minecraft's physics engine is far from perfect. I think magnet movement proved that.

**Comment by WeAthFoLD** [comment]
Issue closed then :-)
