### ISSUE TITLE
[1.0.0] Metal former mode doesn't change with Wawla

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#321]
I can't seem to get the metal former to change modes now. It's perpetually in Plate Crushing. I click the arrows next to the mode, and it will change it to the symbol for refining mode, and when I mouse over the mode it will pop "refining" up for a split second before changing the popup to "plate crushing." it won't flash the "refining" popup again until i click the arrow again, at which point nothing seems to change, except it will occasionally make it so the popup will flash once when you hover over the symbol again. it still works like its in plate crushing mode, and will make constraint metal ingots into plates. Rarely, when clicking the arrows in quick succession, the symbol will change to what I can only guess to be etching, and it will only popup the "plate crushing" text. It also still works as if it is in that mode. If I close and re-open the interface, no matter what mode the symbol says it should be in, it resets to the plate crushing mode and picture. I've tried breaking and replacing it, moving it close and farther from the node, as well as simply out of the space it was in, in case there was residual data in that space from when I loaded the world without AcademyCraft so I could actually continue using the world (I just spawned everything I had back in) in the new version. I have no idea what is causing it, but is does make things more difficult.

**Comment by NoX-programer** [comment]
I confirm that one - metal former become broken after updating to the last version.

**Comment by SeppeSai** [comment]
I had the same issue but I tested with just the mod itself and it was fine so I figured it was other mods I had messing with it. So I did some trial and error of disabling mods and found it to be Wawla(What are we looking at). So if you have that installed try disabling it.

**Comment by WeAthFoLD** [comment]
Can't reproduce in forge 1614 with solely AC installed.
Can't reproduce with AC+Waila installed.
Successfully reproduced with AC+Waila+Wawla.

Wow lets try hack that >_>

**Comment by WeAthFoLD** [comment]
Fixed. The actual problem is that metal former's NBT read/write is buggy, and Wawla changed the tile entity's NBT behavior somehow, which exposed this bug.
