### ISSUE TITLE
[1.0.0] Wireless Imag Node can't get energy from RF Energy Bridge

### ISSUE THREAD

**Issue by skydark** [LambdaInnovation/AcademyCraft#322]
As title, I put them next to each other and no energy comes into the node. It was not broken in pr3.

**Comment by WeAthFoLD** [comment]
RF Energy bridge is a plain **Wireless Generator** as viewed by Node. You have to use the Freq Transmitter to link it to the node. It was a miss to not add link gui for energy bridges, but doesn't affect the core functionality.

**Comment by skydark** [comment]
It works, thank you! Hope the gui for energy bridge returns soon.
