### ISSUE TITLE
[1.0.0]  Rejoining Bug

### ISSUE THREAD

**Issue by mkpoli** [LambdaInnovation/AcademyCraft#324]
"After rejoin in wirld items in machines will be deleted and all wireless systems will be reset." (после перезахода в мир предметы в машинах будут удалены, а также все беспроводные системы будут разорваны) - by юра никольский <nikolanski@mail.ru>

After rejoining a world, items and wireless data will be reset.

**Comment by WeAthFoLD** [comment]
Wireless reset: Can't reproduce.
Machine inventory lost: confirmed.

Please don't merge two issues into one. This makes things hard to handle.

**Comment by mkpoli** [comment]
Affirmative. @WeAthFoLD
