### ISSUE TITLE
[1.0.0] Storm Wing breaks Multiparts

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#326]
Until I actually typed that title, I thought that it just broke torches intentionally, but if its a full bug, then maybe not. If its intended, that might be the cause. When I activate Storm Wing, the torches near me break, and I thought that was a (rather cool) effect, but it also breaks any multiparts (from the ForgeMultipart API). This isn't much of an issue until you realize that, being an api, many blocks are listed as such. This includes transfer nodes and pipes from ExtraUtils, all of Applied Energistics, Item ducts, fluid ducts, and just decorative multiparts. It broke my protective (and decorative) casing for my rock crusher, and it deleted a good portion of my transfer pipe system. I'm guessing its affecting torches and then, by extension, all other multiparts, but not having looked at the code, I'm purely speculating.

**Comment by WeAthFoLD** [comment]
Yes, the skill doesn't see Multipart blocks as special, and no I don't think there should be special support for it. When the exp is larger than 15%, the skill won't break blocks nearby anymore. But there indeed lacks proper description for this effect of the skill, and might be destructive&unsatisfying when first used around home. Will add that to the skill's description.

**Comment by Renniuq** [comment]
Yeah, most people would prefer a warning before accidentally deleting their entire ME system. I do enjoy the fact that you break weak blocks with wind pressure while you aren't very good at using it, and then as you improve you get less destructive. That's really cool to me.
