### ISSUE TITLE
[1.0.0] Block-removing problem while teleporting

### ISSUE THREAD

**Issue by mkpoli** [LambdaInnovation/AcademyCraft#329]
> 关于传送使的一个bug
> -在使用转移传送可能会移除其他方块（基岩），这可能会导致服务器查询失效（或单机玩家痛苦欲绝！）
> 
> 完毕

 - by 572679942 <572679942@qq.com>

[Translation Needed]

**Comment by KSkun** [comment]
Can't reproduce the problem. The issue should be kept open until comfirmed and fixed.
