### ISSUE TITLE
[1.0.0] Metal Former mode change buttons both cycle the same way.

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#331]
Having an arrow that points left, and one that points right, I figured that one would cycle one way, and the other would cycle the other. I'm not sure if its just a bug that it's not working for me or if it wasn't thought of, but I definitely think it should do that. overshooting the mode by one and then clicking the other arrow only to advance farther away is somewhat bothersome. It's not a huge issue, but it would be a nice quality of life improvement. I'm trying to figure out why the mode isn't exactly staying put between some uses of it, but I'll be doing further testing of that to see if I can narrow down a culprit before posting that issue.

**Comment by WeAthFoLD** [comment]
Same issue with #321 and already fixed.
