### ISSUE TITLE
[1.0.0] Teleporter Critical Hit kicking user from server

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#332]
I recently managed to get an ability developer on my small server (might have taken so long because I went straight to advanced), and I got teleporter. Everytime I use the Threatening Teleport to damage an enemy and it crits, I get kicked from the server. I'll have to wait a while to get a server-side log (friend is hosting and away at work atm) but it does seem to be 100% consistent and 100% annoying. I don't care for getting disconnected every 5 seconds when I use my ability on our already laggy server. as if PvE wasn't hard enough at 5 tps, constant relogging definitely doesn't help. I have noticed that the ability that used to give higher chance for crits, as well as the one that gives higher damage crits, haven't been gaining any experience, and I'm not sure if its due to this or due to them not auto-unlocking anymore (haven't tested teleporter yet in the new version).

**Comment by WeAthFoLD** [comment]
#317

**Comment by Renniuq** [comment]
Ah!  I thought I had seen something similar, but I couldn't manage to find when searching for some reason =/ Yep, that's the same
