### ISSUE TITLE
一个可能是BUG的小问题！

### ISSUE THREAD

**Issue by LMLL** [LambdaInnovation/AcademyCraft#334]
首先，我只一个普通的玩家

然后，反馈真心麻烦

最后，重点：

我用传送使的危险传送技能攻击任何生物后有几率会
'关闭内置服务器...'

然后显示
‘链接已丢失’
‘Afatal error has occured, this connection is terminated’

然后就到了游戏主菜单的多人游戏页面

Forge版本：1.7.10-Forge10.13.4.1558

然后，我只能做这么多了，我不太会找原因，所以对不起我没帮上什么忙，可能还帮了倒忙
我的MCBBS ID：荒城孤岛
QQ：2971131798

**Comment by WeAthFoLD** [comment]
重复bug，已修复。在提出issue时请先检查是否已经存在 :-) #317
