### ISSUE TITLE
Dev env setup

### ISSUE THREAD

**Issue by dingshao0402** [LambdaInnovation/AcademyCraft#335]
Hey, I have an issue setting up the dev env. After I cloned the repo and ran gradle install, there is an exception as you can see below.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve cn.lambdalib:LambdaLib:1.2.0.
  Required by:
      cn.academy:AcademyCraft:1.0.0
   > Could not resolve cn.lambdalib:LambdaLib:1.2.0.
      > Could not get resource 'https://libraries.minecraft.net/cn/lambdalib/LambdaLib/1.2.0/LambdaLib-1.2.0.pom'.
         > Could not GET 'https://libraries.minecraft.net/cn/lambdalib/LambdaLib/1.2.0/LambdaLib-1.2.0.pom'. Received status code 403 from server: Forbidden

It seems like I do not have permission to access LamdaLib pom file. I'm wondering if it is the right way to set up. Appreciated if you can give me help. Thanks!

**Comment by WeAthFoLD** [comment]
> you must first build LambdaLib with the required version as specified in build.properties locally (using gradlew install).

As stated in README, clone LambdaLib and run `gradlew install` command, and then you can build AcademyCraft.

**Comment by dingshao0402** [comment]
Cool. It works. Thanks man!
