### ISSUE TITLE
[1.0.1]GUI text display with tChinese showing English only

### ISSUE THREAD

**Issue by AileRozy** [LambdaInnovation/AcademyCraft#339]
使用繁體中文進行遊戲時 除了道具是中文以外  所有GUI顯示都是英文
如果繁中GUI尚未完成, 可否先使用簡中介面代替?

When playing with language tChinese, GUI are in English except items.
If tChinese GUI not ready yet, can we have sChinese GUI instead?

**Comment by WeAthFoLD** [comment]
Will fix next version (update zh_TW.lang).

**Comment by WeAthFoLD** [comment]
Fixed in 1.0.2.
