### ISSUE TITLE
[1.0.0] 在安装某些mod的情况下出现玩家数据混乱

### ISSUE THREAD

**Issue by JrantKing** [LambdaInnovation/AcademyCraft#340]

**Comment by JrantKing** [comment]
进入其他mod的维度可能会有提示你没安装终端，但是你安装的时候又提示已经安装，结果就是不能使用能力

**Comment by WeAthFoLD** [comment]
请问能否提供如下信息？

* 所使用AC版本
* 所使用客户端/服务端，forge版本
* 已安装的mod列表
* 客户端/服务端日志
* 用java.exe而非javaw.exe启动游戏，检查控制台输出，是否有刷屏等异常情况出现，如果有请cv到这里

**Comment by JrantKing** [comment]
AC1.0.0
客户端forge1614服务端KCauldron-1.7.10-1614.201
星系和三个星系附属，AC
控制台没有任何报错

**Comment by JrantKing** [comment]
![qq 20160519122314](https://cloud.githubusercontent.com/assets/16501400/15382396/a2cd4952-1dbc-11e6-950a-98b2e9bc9a6d.png)

**Comment by JrantKing** [comment]
![_bqo pr csam_ e cap](https://cloud.githubusercontent.com/assets/16501400/15382497/7ce82b3e-1dbd-11e6-807d-ba5a53bc7619.png)

**Comment by WeAthFoLD** [comment]
已修复 (#504)
