### ISSUE TITLE
[1.0.0][Feature Request] Config to disable receiving MisakaCloud Terminal on world creation

### ISSUE THREAD

**Issue by thephoenixlodge** [LambdaInnovation/AcademyCraft#345]
Due to the drawn out nature of the progression in Regrowth, I prefer to have it set to not spawn the player with anything other than the HQM quest book. However it seems currently there is no way to disable spawning with the MisakaCloud Terminal, meaning players are left with a guide item won't be of any use to them until long after starting the world.
As such, it would be nice if a config option to disable getting a free one on world spawn.

**Comment by WeAthFoLD** [comment]
Resonable.

**Comment by WeAthFoLD** [comment]
It's done :P will be available in next release.

**Comment by thephoenixlodge** [comment]
Awesome, thanks :D
