### ISSUE TITLE
[1.0.1]Magnet Manipulation not worked

### ISSUE THREAD

**Issue by triplebee** [LambdaInnovation/AcademyCraft#346]
可對鐵磚、柵欄右鍵吸收，但是無法投擲攻擊生物甚至是對著牆扔
吸收狀態音效也會一直在耳邊環繞直到狀態時效到了才消失

**Comment by AileRozy** [comment]
當配置文件 B:destroyBlocks 設置為 false 時
磁場控制 轉移傳送 這類放置方塊於世界的技能會無法使用和鍛鍊
建議修復後, 當B:destroyBlocks=false時 方塊改以道具形式掉落而非放置於世界

**Comment by KSkun** [comment]
@AileRozy 您好，由於這些建議與本Issue無關，已經為您新開一個Issue反饋了，謝謝支持

**Comment by KSkun** [comment]
磁场控制的投掷会出现一定程度的偏差，但是可以用来攻击生物，偏差有时体现在对着墙投掷到了墙后面
@WeAthFoLD 你怎么看

**Comment by WeAthFoLD** [comment]
这个是EntityBlock那东西遗留已久的碰撞检测问题。这个修起来会比较复杂，暂时还没什么思路。

**Comment by KSkun** [comment]
你好，我们没有找到这个问题。如果你在推荐的环境下重现了该问题，能否给我们提供更多的信息呢？
