### ISSUE TITLE
[1.0.1]bugs with B:destroyBlocks=false

### ISSUE THREAD

**Issue by AileRozy** [LambdaInnovation/AcademyCraft#347]
B:destroyBlocks=false時會有一些技能出現無法使用或無法鍛鍊的情況導致無法正常遊戲

電擊使 磁場控制: #346 , 無法正常使用導致無法鍛鍊, 後續技能無法學習

原子破壞 採集光束: 技能能正常施放, 但由於無法破壞方塊導致無法鍛鍊, 後續技能無法學習

傳送使 轉移傳送: 會出現照準方框, 但是放開按鍵後無任何後續動作, 無法施放導致無法鍛鍊和學習後續技能

需要透過破壞方塊來鍛鍊的技能可能都無法正常鍛鍊
涉及放置方塊於世界的技能可能都無法正常使用

關於該功能為false時的建議 #348

**Comment by WeAthFoLD** [comment]
Discussion moved to #348
