### ISSUE TITLE
[1.0.1]bugs and suggestion with B:destroyBlocks=false

### ISSUE THREAD

**Issue by AileRozy** [LambdaInnovation/AcademyCraft#348]
建議B:destroyBlocks=false時

需要破壞方塊才能正常發揮功能或鍛鍊的採集類技能在false時仍然能正常破壞方塊

會在世界放置方塊的技能在false時改成掉落道具於地面

**Comment by WeAthFoLD** [comment]
destroyBlocks=false时自动加满熟练度并且不允许使用该技能如何？不然的话刷一个“伪技能”经验的过程真的是非常无聊。

**Comment by AileRozy** [comment]
B:destroyBlocks=false時會有一些技能出現無法使用或無法鍛鍊的情況導致無法正常遊戲

電擊使 磁場控制: #346 , 無法正常使用導致無法鍛鍊, 後續技能無法學習

原子破壞 採集光束: 技能能正常施放, 但由於無法破壞方塊導致無法鍛鍊, 後續技能無法學習

傳送使 轉移傳送: 會出現照準方框, 但是放開按鍵後無任何後續動作, 無法施放導致無法鍛鍊和學習後續技能

需要透過破壞方塊來鍛鍊的技能可能都無法正常鍛鍊
涉及放置方塊於世界的技能可能都無法正常使用

我個人認為採集光束這類專門為了採集而破壞方塊的技能 應該要能在destroyblocks為false時能正常發揮功用 畢竟那也算是該能力的特色之一
如果取消或習得技能後都用不到感覺少了一點樂趣

磁場控制和轉移傳送就更不用說了, 一個是電磁砲的前置招式, 一個是4級必經之路, 而且兩個都還是輸出招, 轉移傳送還是傳送使勉強算的上有AOE的技能
以上是個人觀點

**Comment by WeAthFoLD** [comment]
我想这个问题应在1.0.2中应该不复存在了。新版本添加了技能数据自定义功能，并且有技能级别的打开/关闭方块破坏的选项。详情：
https://github.com/LambdaInnovation/AcademyCraft/blob/dev/src/main/resources/assets/academy/config/default.conf

如果没有什么问题的话这个issue就可以close了 :P

**Comment by AileRozy** [comment]
Leave a comment
