### ISSUE TITLE
无法运行。

### ISSUE THREAD

**Issue by 1061628249** [LambdaInnovation/AcademyCraft#356]
[fml-client-1.txt](https://github.com/LambdaInnovation/AcademyCraft/files/299789/fml-client-1.txt)
[fml-client-3.txt](https://github.com/LambdaInnovation/AcademyCraft/files/299790/fml-client-3.txt)
[fml-client-latest.txt](https://github.com/LambdaInnovation/AcademyCraft/files/299791/fml-client-latest.txt)

**Comment by WeAthFoLD** [comment]
应该是mod冲突所致。请问分别移除以下mod之后是否还会崩溃？

* 动态光源
* FastCraft
* Walia

**Comment by WeAthFoLD** [comment]
无进一步信息提供，故关闭。
