### ISSUE TITLE
Media player issues

### ISSUE THREAD

**Issue by blazelink3** [LambdaInnovation/AcademyCraft#357]
Its not game-breaking by any means, however when the current song (E.G. Only my railgun) finishes, a player can press stop and then play, and the media player will play the next song without it's installation. (tested for Only my railgun to Judgelight, unsure about judgelight to Sister's noise. Confirmed for both creative and survival mode)

**Comment by WeAthFoLD** [comment]
Fixed in 984c52ee360da4bb61ac431be889d86310be30cc.
