### ISSUE TITLE
我刚启动就崩溃了

### ISSUE THREAD

**Issue by TheBlackDayDream** [LambdaInnovation/AcademyCraft#358]
版本：1.7.10 Forge版本：1614 Mod：bspkrsCore,CodeChickenLib,RedGearCore,Sim-U-Craft,Better HUD,NameWankander,Paxel,CodeChickenCore,CoroUtil,FastCraft,IronChest,Waila,Weird-Things,Voxel Map,MSM-SNAP,NEI,R键整理,WailaHarvestability,ZombieAwareness,FoodPlus,MoreHome,Power Tools Mod,Dense Ores,gokiStats,Torcherino Mod,加速火把支持核心,inventory,TreeCapitator,VeinMiner Mod,Stefinus 3D Guns,雄伟计划,InputFix

**Comment by ShieLian** [comment]
请发crash-report
