### ISSUE TITLE
1.0.1版本无法启动

### ISSUE THREAD

**Issue by sadasd12332** [LambdaInnovation/AcademyCraft#359]
forge mod loader has found a problem with your minecraft installation,the mod and versicrs listed below could not be found
        lambdalib : [1.2.0,1.2.0]
forge版本：10.13.2.1230
LambdaLib 1.0 版本没有问题

**Comment by WeAthFoLD** [comment]
AC 1.0.1 对 LambdaLib 的版本需求是1.2.0，请在官网更新LL版本。
