### ISSUE TITLE
Location Teleport forgets all locations

### ISSUE THREAD

**Issue by Himeki** [LambdaInnovation/AcademyCraft#368]
Forge 1566
AcademyCraft 1.0.1
LambdaLib 1.2.0

Marking locations then save and quit/disconnect (server).
On reconnect, all locations are lost and must be re-visted and remarked for use in that session.

**Comment by EmoGithub** [comment]
same problem

**Comment by Himeki** [comment]
Small addition to this. If you use Mystcraft, any time you enter a mystcraft world or return to the overworld the locations are also lost.

**Comment by WeAthFoLD** [comment]
Should've been fixed in 1.0.2.
