### ISSUE TITLE
[1.0.1] Shift Teleport does not seem to work

### ISSUE THREAD

**Issue by Himeki** [LambdaInnovation/AcademyCraft#369]
Forge 1566
AcademyCraft 1.0.1
LambdaLib 1.2.0

Holding a block and then, pressing and holding the assigned button (default or not) shows a target marker, but does nothing on release.

Tested with ore blocks, stone, cobble, sand, gravel, various AcademyCraft ores and other blocks.

**Comment by KSkun** [comment]
Please check if you disabled 'destroBlocks' setting.
