### ISSUE TITLE
Typo in MisakaCloud front page

### ISSUE THREAD

**Issue by 3TUSK** [LambdaInnovation/AcademyCraft#371]
![image](https://cloud.githubusercontent.com/assets/9113033/16102353/265866d6-33a1-11e6-9dd9-849c3c73895a.png)
Ablities -> Abilities

**Comment by WeAthFoLD** [comment]
@NolifeM

**Comment by KSkun** [comment]
257c763d0493f786ece435a23226f87f647b4c14 Fixed.
