### ISSUE TITLE
版本1.0.1，未崩溃，达到要求，进入游戏后字体变成一块一块白色的

### ISSUE THREAD

**Issue by TheBlackDayDream** [LambdaInnovation/AcademyCraft#374]

**Comment by 3TUSK** [comment]
F3+T强制刷新材质后再试。此问题在任何mod环境下都有可能触发。

**Comment by ShieLian** [comment]
请尝试将配置文件中的字体(形如“微软雅黑”或"Microsoft Yahei")更改为系统有的字体(win 中文系统没有Microsoft Yahei，英文没有微软雅黑)
