### ISSUE TITLE
[1.0.1] Teleporter Dimension Folding Theorem not improving

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#376]
So, I finally got back to messing with AcademyCraft, and this time I got teleporter. I'm enjoying the lack of crashing every time I crit, but I've noticed that the Dimension Folding Theorem isn't improving. I've unlocked it manually (unlike every other time, where it seemed to unlock itself, just like spatial folding used too) but, even though I've gotten crits multiple times, It's still at 0.0%. My guess is that whatever the fix you implemented for the crashing was caused this, but its based on my *very* limited knowledge, so take that with a grain of salt.

On an unrelated note, I was really hoping for VecManip, but then I got teleporter. My friend then came to get an ability, was hoping for teleporter, and got VecManip... RNG be trolling hard xD

**Comment by WeAthFoLD** [comment]
Duplicate with #386
