### ISSUE TITLE
[1.0.1] Ability Induction Factor's description is mistaken

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#377]
I haven't used on before, so I might not be using it right, but I do believe you need the ability induction factor, a high voltage magnetic coil, an advanced ability developer, and to be at least level 2, right? I have all those requirements, I right click the developer with the vecmanip ability induction factor in my inventory, and the special boot screen shows up, and once it fails and tells me to use "reset" I put that in, and it says "Can't reset ability -- either level is too low or induction factor not detected."

However, I clearly am level 2, and have the ability induction factor in my hotbar. I've tried it with it in my inventory, and with it in my hotbar both before the high voltage magnetic coil and after it, but no luck.

[Screenshot of the developer screen with the induction factor in my hotbar](http://imgur.com/d3Ak5Tl
)

After grinding the threatening teleport for a whopping 3000 uses to get to level 2 so I could get vecmanip... This is a tad infuriating xD

**Comment by WeAthFoLD** [comment]
Actually there is a mistake writing MisakaCloud, and the actual level requirement is level 3. This will be clarified in next version by a clear error message in Ability Developer, and correcting MisakaCloud.

**Comment by Renniuq** [comment]
Doh! Time to grind for another hour xD

That's good to know though.
