### ISSUE TITLE
[1.0.1] Hopper pulls from Input of Metal former

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#378]
A Hopper under a metal former will pull out the iron from the input slot that a hopper above is putting in, so automating with non-intelligent item routing methods is not very possible. I believe this is an issue with I-Sided implementations, but I'm not sure on that. I'm guessing the imag fusor will have the same issue.

**Comment by WeAthFoLD** [comment]
Will fix.

**Comment by Renniuq** [comment]
Also, pipes (and hoppers) can input items into the output once the input fills up, which is probably the same issue.
