### ISSUE TITLE
[1.0.1] 定位传送：将其他玩家一同传送后在极短时间内该其他玩家会退回至原地

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#379]
如题，具体方式可有：死亡、退出游戏。
forge1558

另附建议：
1.定位传送的标记界面中将“添加坐标”按钮变为可用（因为我见过很多人将该按钮视为添加的按钮（包括我自己））
2.已标记的坐标在界面中名字可居中显示，靠左会使有些坐标的名字不是太清晰。
3.为坐标添加默认名字，如（1）、（2）等，以给懒人福利。

**Comment by nirvanaxiao6** [comment]
关于定位传送还有一个BUG，有时将其他玩家一同传送后在极短时间内该其他玩家会退回至原地。

**Comment by WeAthFoLD** [comment]
已重写， 传送玩家的那个点需要修一下
