### ISSUE TITLE
[Feature Suggestion] Magnetic block config

### ISSUE THREAD

**Issue by LatentDesire** [LambdaInnovation/AcademyCraft#381]
A config option to add blocks that are also ferromagnetic but not already effected by the magnet abilitys in the electro master branch of powers. 

These would be iron, nickel, cobalt, and gadolinium blocks added by other mods. Also possibly blocks that would be largely composed of said blocks.

**Comment by LatentDesire** [comment]
Possibly with a separate part of the config for ores.

**Comment by Renniuq** [comment]
I agree, this feature would be very good. I'd love the ability to fix iron furnaces not being magnetic, for instance

**Comment by WeAthFoLD** [comment]
A direct solution would be a list of supported OreDict IDs in config. I suppose that's enough?
