### ISSUE TITLE
[1.0.1] Server OP's can't use /aim on other players

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#384]
We'd like to be able to use /aim to (currently) bypass the leveling annoyance and let an OP level a player up once they max all their abilities in the level, but it isn't possible to use it on another player. It also doesn't work from the console, and it could cause problems for servers in the future. Adding a username to one of the arguments could be a good idea.

**Comment by WeAthFoLD** [comment]
It's already there. `/aimp <player> <command> [args...]`

**Comment by Renniuq** [comment]
oh... well, aren't I silly and ignorant xD

thanks.
