### ISSUE TITLE
[1.0.1] Some abilities don't improve

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#386]
I've found this applies to more than just the Dimension Folding Theorem I submitted an issue for earlier.

I've had it happen with the following abilities:
β Radiation Intensify (Meltdowner category) - started off at ~22% for some reason, and stayed there, 2 seperate people on my server had the exact same issue, and nobody else had meltdowner
Dimension Folding Theorem (Teleporter category)
Magnet Movement (Electromaster category) - one of the people on my server had this happen, it stopped at 1.4% and didn't go up anymore, but it worked fine for me in SP so not sure what happened
Vector Reflection (VecManip category)

I've excluded the three shared abilities of mind course and brain course, since those aren't supposed to improve (I don't think).

Not sure what is causing it, but there is one ability from each category (at least, I'm the first to reach level 4 on my server, in VecManip, the electromaster is level 3, and the two meltdowners are level 2 both, so we haven't checked every ability yet, but it does make for some rather good play testing.)

Edit: Seems Railgun doesn't improve either.

**Comment by WeAthFoLD** [comment]
Will check.

**Comment by WeAthFoLD** [comment]
1. β radiation intensify's: exp logic is slightly confusing. Moved to #418.
2. VecReflection: moved to #409
3. Can't reproduce for Magnet Movement. Slightly altered the calculation logic of experience though.
4. Fixed for Dim Folding Theorem
