### ISSUE TITLE
[Feature Suggestion] Config option to scale damage

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#387]
Now, for a vanilla-oriented environment, most abilities do good amounts of damage, but in a modded environment (especially some mods like OreSpawn or Divine RPG) they do simply inadequate amounts of damage. Thus, I don't want a straight damage buff to anything, since there are environments where they are good. But when your trying to fight mobs with, say 500 health and that will hit for 100 hearts, being able to only peck for 5, or even 10 of that is enough to make the mod useless in such environments. Now, this is an extreme example, but in, say a pvp environment, if railgun will only hit for 3 hearts when wearing simply decent armor (for the pack, anyways), it makes me feel that it needs to do more damage. As such, I'd like a way to do so, with my idea being a config option that is a universal damage multiplier. this way, a pack creator who wants to have it useful in Divine RPG could, say, multiply the damage 5 times or something, but someone who only wants a minor increase could just go 1.2 times, etc. also, it would be simpler than configuring each ability, but if you want to go the super-customization route, I won't exactly complain. Of course, I respect the fact that its your mod, and you have the right to do what you want with it, and that this might be considered ruining the spirit of what your doing. Just thought I'd ask in case. That's also why this is a feature suggestion, not a feature request.

**Comment by WeAthFoLD** [comment]
Already implemented in 1.0.2.
