### ISSUE TITLE
原子崩坏不平衡.电击使太弱

### ISSUE THREAD

**Issue by kaixue233** [LambdaInnovation/AcademyCraft#390]
原子崩坏攻击防御和实用都是各职业的一个极端，堪称最强。相比之下，电击使的技能一开始就没其他能力强，攻击低，机动性不强，是一个完完全全的腊鸡233

**Comment by EmoGithub** [comment]
赞成 手动斜眼

**Comment by WeAthFoLD** [comment]
能力系的绝对平衡并不在AC设计的追求范围内。
而且实际上，我们收到的建议平均的分为以下四种：

* 电击使最强
* 原子崩坏最强
* 空间最强
* 矢量操作最强

由于本issue不具有太大的开发指导价值，故关闭。
