### ISSUE TITLE
[1.0.1] Vector Reflection doesn't reflect Ghast fireballs right.

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#391]
Rather simple, when trying to reflect ghast fireballs, it seems to reflect twice, resulting in it going in the same direction it was at first. That or it tries a few times and fails, not sure. The sound and visual effects trigger, but the fireball maintains it's course.

On a side note, I doubt you did it intentionally, but I can't seem to reflect Thaumcraft magic, which, honestly, makes me kinda happy. Since its magic, and... Vector Reflection doesn't work well against it. Just a little bit of unintentional compat? that made me chuckle a little.

**Comment by WeAthFoLD** [comment]
Hmmm. For the case of arrow reflection, there is a flag to check whether it is reflected. Will see if this is also done in other entities.

**Comment by LatentDesire** [comment]
Not sure if this is for vector deflection or reflection, but when I tried using it with Matter Overdrive against Rouge Androids, it took about 1-2 shots from the ranged androids before I was overloaded. Was probably deflection. I imagine that the player weapon would function the same.

**Comment by WeAthFoLD** [comment]
already fixed in 1.0.3 (Added accepted entity config)
