### ISSUE TITLE
[建议]被禁用的技能通过其他方式提升经验值

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#398]
有些技能被禁用后无法提升经验值，会导致后续一系列技能无法学习

**Comment by WeAthFoLD** [comment]
咦，忘了写

**Comment by WeAthFoLD** [comment]
经检查，现在的逻辑不存在问题。如果一个技能被禁用，后续技能对它的依赖会自动取消。如果直接禁用了lv1的技能导致无法通过任何手段提升经验，那只能说是实力作死。
