### ISSUE TITLE
[1.0.2] Effect of ElectroBomb skill is not displayed correctly

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#400]
来自外国友人的反馈，以下为原文
Hi, there's problem with skills, I cant see meltdowner skills like electro bomb I can see only circle. I cant see my friends skills either and they cant see mine. I can see electromaster skills only when I am electromaster.
My friend can see only railgun.

**Comment by WeAthFoLD** [comment]
1. circle应该是指代光球，应该是指electro bomb等技能看不到发出的光束
2. 有一部分的技能使用只能自己看到，其他玩家看不到，具体哪些不明
3. `My friend can see only railgun`意义不明

优先修复1，2和3由于缺少信息暂时无视。

**Comment by nirvanaxiao6** [comment]
3句可能为承接上句，说明当朋友不是电击使的时候只能看到自己发出的电磁炮的特效
