### ISSUE TITLE
1.0.2装服务器后，服务器无法启动

### ISSUE THREAD

**Issue by xbaox360** [LambdaInnovation/AcademyCraft#402]
错误报告都没有，直接未响应开不动了

服务器租的，用的后台管理，点了开启服务器后，挂了一晚上都还在载入中...

换了其他服务端也没用，之前1.0.1用得还好好的

**Comment by WeAthFoLD** [comment]
未响应的话也应该可以看到服务器的运行日志，请贴上来，以及包括服务器的配置、操作系统、Java版本等关键信息。缺少这些的话是没有办法进行错误排查的。

**Comment by xbaox360** [comment]
好吧问题搞定了 控制台输入了/fml confirm后就能启动了
