### ISSUE TITLE
[1.0.2]NEI的合成支持中，机器合成的显示错位问题

### ISSUE THREAD

**Issue by NolifeM** [LambdaInnovation/AcademyCraft#415]
如图：
![qq 20160712005346](https://cloud.githubusercontent.com/assets/10100253/16739153/5f8483e8-47cb-11e6-987f-817d09456ec1.png)
![qq 20160712005426](https://cloud.githubusercontent.com/assets/10100253/16739154/5f8718e2-47cb-11e6-9a42-8f5bd08d4537.png)

**Comment by KSkun** [comment]
#417 Included
