### ISSUE TITLE
/aim commands should have a [player] argument

### ISSUE THREAD

**Issue by Himeki** [LambdaInnovation/AcademyCraft#416]
Server admins cannot target a player to check/edit.
Using a /aim command on server console reports an error about lacking a target player (including /aim help). Adding an optional player argument to the end of the commands would work for server console/admin purposes.
Examples of use on server:
- Certain abilities do not work, the ability to set a player's experience high enough for them to continue instead of giving them OP powers to do it to themselves. (eg shift teleport set to 100% to continue to flashing)
- If a glitch to a player results in requiring deletion of player data, there is no way to return them to what they were.

**Comment by WeAthFoLD** [comment]
`/aimp <player> <command> [args...]`

One thing to admit is that it's not documented good enough for players to find it. Will find a way to improve.

**Comment by Himeki** [comment]
Thank you, I didn't even know the /aimp version existed.
