### ISSUE TITLE
[1.0.2] Vector Reflection doesn't work correctly with kCauldron

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#425]
Now, I'm not exactly sure what caused the issue, I believe it to be kCauldron, since it didn't appear until we added that and plugins to the server, and it persists even with the plugins gone, and since that means it is the main difference, I used deductive reasoning.

Anyways, the issue I'm having is now, when Reflection is active, projectiles will reflect just fine like they used to, as will damage, but it no longer negates damage to me. In fact, while reflection is on, all damage I take bypasses my armor. This makes it far less useful in combat situations, although it _may_ be able to be considered a type of balancing, just... not the kind intended. it did negate damage before kCauldron was added. This also seems to apply to vector deviation, as well.

I first encountered the issue in 1.0.1, but since I had no way of knowing what exactly caused it, I didn't want to submit it as an issue until I could pinpoint a cause, but with it persisting through the version update, I figured I'd submit it anyways.

**Comment by KSkun** [comment]
Here's one posibility: If you are in overload, the skill will fail to work.
And I don't find the problem (even though I'm in overload) in KCauldron 1.7.10 with Forge 10.13.4.1517. Could you give me your Forge version plz?

**Comment by Renniuq** [comment]
We're using the default forge for FTB Infinity Evolved, let me go see... Forge 10.13.4.1614, by the looks of the debug screen. oh, right: Fastcraft is installed too. I know that can cause abnormalities, totally forgot to mention that last time, my apologies.

Also, I wasn't overloaded, the ability itself was functioning, reflecting both damage and projectiles, but it would fail to negate damage to me. Hitting me with it on would still hurt the other, and would use some of my cp and give me some overload, but I'd take the full damage of the attack. I was wearing Quantum armor from IndustrialCraft2, which negates a good bit of damage; When hit by an electon beam with the armor on and reflection off, I'd take half a heart of damage, but if I was hit by that with the armor on and reflection active, I'd take 6 hearts of damage, completely ignoring the fact that I was wearing the armor. Damage would only bypass my armor when the skill was active, if it was off the armor would function like normal. That being said, we've since removed kCauldron, and reflection is working once again, so its not a pressing issue for me anymore, but it does further incline me to believe kCauldron was the culprit.

**Comment by KSkun** [comment]
Got it. Thanks for your feedback.
It seems to be a bug indeed. We will check it out.
And I have a suggestion that you can try kCauldron with Forge 10.13.4.1517 and it might solve the problem. I think I didn't find the problem using 1517.
