### ISSUE TITLE
[1.0.2] Vector Reflection feedback loop with Thaumcraft "Spined" mobs

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#426]
Pretty simple, I punched a spined skeleton with reflection on, it hurt me with its thorns, so reflection hit it, hurting me, hitting it, hurting me, etc. Normally, it'd cause an instant overload and probably a dead skeleton, but with the fact that reflection currently makes all damage I take bypass armor (previously made issue) I ended up dying about 40 times in the span of a single game tick. I now have most deaths on our server! the skeleton seemed to have also experienced a similar fate, having dropped a stack in a half of bones, 6 bows, 2 skulls, 74 arrows, and 96 treasures (a thaumcraft drop, each "special" mob will drop one on death). I'm interested in testing this against the thorns enchant, will report back with my findings if they are of the buggy kind.

**Comment by WeAthFoLD** [comment]
Is it still present in 1.0.3?

**Comment by Renniuq** [comment]
Our server is yet to update, I'll let you know after it does and once I find another spined mob. Actually, I'll just test it in singleplayer... let's see. Well, at least for skeletons, it is fixed now; They can no longer hit you with arrows...

I am noticing that when something is dealt the final blow by reflection, it seems to trigger multiple times. It also sometimes triggers more than seemingly necessary. Also, as was the case last version, if your too close to a skeleton, when you reflect the arrows back, they don't hit the skeleton, instead simply passing through it. Seems that range is around 6 or 7 blocks, farther out it works fine.

Well, having just tanked an endless zombie horde for a good 10 minutes with no issues, I'd say its fixed. There was bound to be a few spined zombies in there, there were plenty of other special ones. It seems that when reflection kills a zombie, it will trigger on the damage that deals the last blow, and then will reflect the "dead zombie" entity that will spawn after, not sure why, but that was the multiple reflections on death I was seeing.

**Comment by Renniuq** [comment]
Wait... no, its not reflecting the dead zombies... its reflecting xp orbs? there was a bunch of xp on the ground, it would "reflect" each orb, whilst not actually doing anything to them, and it'd only do it once... I'm guessing the fix for ghast fireballs made them count xp orbs as projectiles too, weird.
