### ISSUE TITLE
Some errors in the words in academy-craft-data.conf.

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#428]
Line 14 and 15.
    maxcp_incr_rate: 0.0025 # The max cp increase rate (multiply by CP consumption)
    maxo_incr_rate: 0.0058 # The max overload increase rate (multiplied by Overload consumption)
Multiply or Multiplied,which should be used?

Line 24.
  # Global skill caculation interferers.
caculation→calculation.
And I don't know the meaning of the word "interferers".

**Comment by WeAthFoLD** [comment]
14&15. by grammar it's 'multiplied.

24. The meaning is that those configuration properties affects(interferes) global damage/cp/etc. calculation.
