### ISSUE TITLE
[1.0.2]The number of death will be wrong while using both Vector Reflection and Plasma Cannon at the same time.

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#429]
While..something must be wrong with the update.I can't show the picture here.
If a player use Vector Reflection reflect his Plasma Cannon and finally if it caused his death,there will be a lot of death information appearing.They are all like this:Player 1 is killed by Player 1 by Vector Reflection.But the final one shows that player 1 killed by Plasma Cannon.
//My English is poor,I'm just loading force.

**Comment by KSkun** [comment]
1. "with the update"->"in uploading" U can just keep a dictionary near you.
2. Here's the picture.
![pic1](https://cloud.githubusercontent.com/assets/5047602/16894261/c8349ec6-4b83-11e6-9c76-5d861c9bdfcc.jpg)

**Comment by Renniuq** [comment]
I've had the same thing happen when shooting myself with a crossbow (from tinkers); shoot it straight up, turn on reflection, and usually it will reflect the bolt, but sometimes the bolt will hit and will trigger a loop of reflection reflecting the damage of the bolt you dealt to you, causing reflection to reflect it again, and so on and so forth, until it will cause you to die. We have a death tracker on our server, and it peaked at about 90 deaths counted for the one death. I also dropped several of my heads...

This is also almost identical to the result in issue #426 with me dying 40 or so times when getting hit by a skeleton with thorns, essentially. The skeleton also dropped the loot for 96 skeletons (it was special and had a guaranteed drop to get one of).

I imagine a similar result might occur if a player with reflection on hits a different player with it on, I'd have to get back to you on that one.

**Comment by Renniuq** [comment]
I just had this happen, with Vector Reflection reflecting plasma cannon at me in a loop, clocked in 100 deaths on the death counter right there. It doesn't always happen, it seems that reflection will usually reflect the plasma cannon damage just fine, but occasionally it will do that. I have yet to be able to determine a specific trigger for it, atm it seems mostly random.

**Comment by KSkun** [comment]
Tested in AC 1.0.3 & LL 1.2.2 & KCauldron 1517. Not happened again.
Maybe you can update to 1.0.3 and check if the problem is fixed.
