### ISSUE TITLE
[1.0.2] Skills can destroy paintings and item frames when the blockDestroy set 'false'.

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#437]

**Comment by WeAthFoLD** [comment]
Just according to the title, I don't think it's a bug at all, it's intended behaviour.

**Comment by KSkun** [comment]
@WeAthFoLD I just forgot some other conditions. 233

**Comment by Renniuq** [comment]
I'd imagine this would be related to how players can break paintings in adventure mode, due to them being more entities than blocks. This would also make me think it'd happen for item frames too.
