### ISSUE TITLE
[1.0.1] When using a certain texture pack, the developer is invisible and doesn't work.

### ISSUE THREAD

**Issue by aidandunn** [LambdaInnovation/AcademyCraft#441]

**Comment by WeAthFoLD** [comment]
Please be more specific. Check out the README of the repository.

**Comment by KSkun** [comment]
请提供更多的信息。例如你在使用什么材质包。
Please provide us with more information. Such as what texture pack you are using.

**Comment by aidandunn** [comment]
it happend when i turned on the loot texture pack mod support

**Comment by aidandunn** [comment]
and it was 1.0.2 i did have not enough items mod

**Comment by aidandunn** [comment]
i turned of the texter pack but still invisble plz reply soon after this

**Comment by aidandunn** [comment]
i fixed it i had to go to 1.0.3 yay😂

**Comment by aidandunn** [comment]
it happend in 1.0.3 and i had no texterpack on😥😥

**Comment by KSkun** [comment]
Please tell us about your system information.
We at least need these information below:
 - Video card
 - Video card version
 - Supported GL Version
 - OS (Windows, Linux, OS X, etc.)
 - OS Version
 - Forge Version
Thanks for your feedback.

**Comment by aidandunn** [comment]
fixed i had to get the verson onr more time yay

**Comment by aidandunn** [comment]
um i fised it i upgraded i dont need help and i dont know any of that informatoin well the forge i know but its fised yay
