### ISSUE TITLE
[Feature] MagManip & MagMove support moving some other blocks besides metal blocks.

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#443]
It should be a feature of milestone developing.

**Comment by WeAthFoLD** [comment]
Isn't it supported by metal block configuration?

**Comment by KSkun** [comment]
@WeAthFoLD Not at all. That config can only set supported blocks but not milestone developing of proficiency. We should redo that part to add our default features.

**Comment by KSkun** [comment]
里程碑属于大任务
