### ISSUE TITLE
[1.0.3] Achievements of VecManip is missing.

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#444]

**Comment by WeAthFoLD** [comment]
What the heck is Echievement

**Comment by nirvanaxiao6** [comment]
I think we can let the achievements of AC disappear.It doesn't very useful or playable now,Misaka Cloud will be the guide that the achievements used to be.

**Comment by KSkun** [comment]
@nirvanaxiao6 And we aren't talking about the same thing. You can talk about it in our groups.
