### ISSUE TITLE
[1.0.3] 装入服务器后，一登录服务器就被弹回了多人游戏选择服务器的界面

### ISSUE THREAD

**Issue by EvilGiraffe233** [LambdaInnovation/AcademyCraft#446]
提示语为：A fatal error has occured,this connection is terminated,     服务器能开，但是一进去就被崩出去了

**Comment by liach** [comment]
给下服务端在玩家连接时的log

**Comment by EvilGiraffe233** [comment]
似乎没有说为什么被弹出去，服务器控制台那边还显示玩家在线，可是实际上玩家已经被弹出

**Comment by EvilGiraffe233** [comment]
控制台是这么说的：
【断开连接】玩家xxx离开了服务器，原因：A fatal error has occured,this connection is terminated

**Comment by EvilGiraffe233** [comment]
若是使用1.0.1及之前的版本就没有这个问题，使用1.0.2或1.0.3就会出现这个问题

**Comment by EvilGiraffe233** [comment]
25.07 14:58:20 [服务器] 严重错误 FMLIndexedMessageCodec exception caught
25.07 14:58:20 [面板] www2 执行指令 每日信息
25.07 14:58:20 [建立连接] 玩家 www2 的IP为: 218.14.47.6
25.07 14:58:20 [服务器] 信息 [可忽略]服务器MOD已确定
这是连接时的控制台信息，也许是那个严重错误引起的

**Comment by KSkun** [comment]
请问你是使用Thermos服务端版本为1566的吗？

**Comment by KSkun** [comment]
与#413 重复。
