### ISSUE TITLE
bug 1.03版本 开启矢量反射后客户端闪退

### ISSUE THREAD

**Issue by hxp1999** [LambdaInnovation/AcademyCraft#447]
在开启矢量反射后客户端立即停止响应，出现闪退
错误报告如下

> 
> ---- Minecraft Crash Report ----
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 16-7-25 下午3:39
> Description: Unexpected error
> 
> java.lang.IllegalStateException: Function is not supported
> 	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
> 	at org.lwjgl.opengl.GL33.glVertexAttribDivisor(GL33.java:378)
> 	at cn.lambdalib.pipeline.api.GraphicPipeline.flush(GraphicPipeline.java:80)
> 	at cn.academy.vanilla.vecmanip.client.effect.WaveEffectUI.render(WaveEffectUI.scala:141)
> 	at cn.academy.vanilla.vecmanip.client.effect.WaveEffectUI.onFrame(WaveEffectUI.scala:94)
> 	at cn.academy.vanilla.vecmanip.skills.VecReflectionContextC.onRenderOverlay(VecReflection.scala:229)
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_438_VecReflectionContextC_onRenderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
> 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
> 	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
> 	at net.minecraftforge.client.GuiIngameForge.renderCrosshairs(GuiIngameForge.java:217)
> 	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:130)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:120)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
> 	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
> 	at org.lwjgl.opengl.GL33.glVertexAttribDivisor(GL33.java:378)
> 	at cn.lambdalib.pipeline.api.GraphicPipeline.flush(GraphicPipeline.java:80)
> 	at cn.academy.vanilla.vecmanip.client.effect.WaveEffectUI.render(WaveEffectUI.scala:141)
> 	at cn.academy.vanilla.vecmanip.client.effect.WaveEffectUI.onFrame(WaveEffectUI.scala:94)
> 	at cn.academy.vanilla.vecmanip.skills.VecReflectionContextC.onRenderOverlay(VecReflection.scala:229)
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_438_VecReflectionContextC_onRenderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
> 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
> 	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
> 	at net.minecraftforge.client.GuiIngameForge.renderCrosshairs(GuiIngameForge.java:217)
> 	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:130)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [EntityClientPlayerMP['CrazyShit'/7033, l='MpServer', x=568.51, y=73.62, z=796.76]]
> 	Chunk stats: MultiplayerChunkCache: 212, 212
> 	Level seed: 0
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (236,64,271), Chunk: (at 12,4,15 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 898392 game time, 909664 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Forced entities: 48 total; [EntityClientPlayerMP['CrazyShit'/7033, l='MpServer', x=568.51, y=73.62, z=796.76], EntitySlime['史莱姆'/5011, l='MpServer', x=602.38, y=29.00, z=764.38], EntityZombie['僵尸'/7065, l='MpServer', x=509.66, y=65.00, z=775.59], EntityZombie['僵尸'/6943, l='MpServer', x=552.50, y=70.00, z=742.50], EntityCreeper['爬行者'/7072, l='MpServer', x=506.47, y=17.00, z=851.03], EntityCreeper['爬行者'/7075, l='MpServer', x=503.50, y=16.00, z=848.50], EntitySpider['蜘蛛'/7076, l='MpServer', x=505.53, y=16.00, z=844.75], EntityCreeper['爬行者'/7077, l='MpServer', x=515.50, y=70.00, z=743.50], EntityBrainyZombie['红眼僵尸'/7080, l='MpServer', x=502.34, y=17.00, z=842.34], EntityPig['猪'/1832, l='MpServer', x=611.53, y=68.00, z=749.66], EntityCreeper['爬行者'/7082, l='MpServer', x=534.50, y=72.00, z=741.50], EntityPig['猪'/1834, l='MpServer', x=611.97, y=66.00, z=792.16], EntityPig['猪'/1837, l='MpServer', x=579.97, y=67.00, z=840.53], EntityPig['猪'/1841, l='MpServer', x=589.50, y=68.00, z=817.47], EntityPig['猪'/1842, l='MpServer', x=577.87, y=68.00, z=825.70], EntityPig['猪'/1843, l='MpServer', x=589.84, y=63.00, z=842.50], EntityZombie['僵尸'/7091, l='MpServer', x=518.50, y=19.00, z=839.50], EntityPig['猪'/1844, l='MpServer', x=582.41, y=65.00, z=826.06], l['未知'/53, l='MpServer', x=0.00, y=0.00, z=0.00], EntityPig['猪'/1846, l='MpServer', x=581.69, y=64.00, z=839.53], EntityZombie['僵尸'/7094, l='MpServer', x=562.50, y=45.00, z=739.50], EntitySpider['蜘蛛'/7097, l='MpServer', x=510.50, y=69.00, z=824.50], EntityCreeper['爬行者'/7226, l='MpServer', x=598.50, y=67.00, z=803.50], EntitySkeleton['骷髅'/7100, l='MpServer', x=513.50, y=47.00, z=787.50], EntityPig['猪'/1852, l='MpServer', x=619.47, y=72.00, z=828.53], EntityCreeper['爬行者'/7101, l='MpServer', x=511.50, y=47.00, z=786.16], EntityPig['猪'/1853, l='MpServer', x=612.97, y=66.00, z=822.09], EntityPig['猪'/1854, l='MpServer', x=601.44, y=64.00, z=843.97], EntityCreeper['爬行者'/7102, l='MpServer', x=511.50, y=47.00, z=785.31], EntityPig['猪'/1856, l='MpServer', x=608.50, y=64.00, z=845.19], EntityCreeper['爬行者'/7106, l='MpServer', x=534.28, y=71.00, z=736.50], EntityPig['猪'/1860, l='MpServer', x=597.94, y=69.00, z=853.09], EntityPig['猪'/1861, l='MpServer', x=592.50, y=70.00, z=851.69], EntityPig['猪'/1864, l='MpServer', x=612.59, y=63.00, z=849.28], EntityItem['item.item.porkchopRaw'/6863, l='MpServer', x=539.25, y=75.13, z=846.91], EntityXPOrb['经验球'/6865, l='MpServer', x=538.25, y=74.25, z=851.72], EntitySkeleton['骷髅'/6995, l='MpServer', x=536.53, y=73.00, z=747.84], EntitySkeleton['骷髅'/7123, l='MpServer', x=532.69, y=71.00, z=754.50], EntityZombie['僵尸'/7124, l='MpServer', x=541.50, y=53.00, z=834.50], EntitySpider['蜘蛛'/7256, l='MpServer', x=618.65, y=75.00, z=739.73], EntitySpider['蜘蛛'/7257, l='MpServer', x=616.58, y=75.00, z=737.70], EntityItem['item.item.porkchopRaw'/6746, l='MpServer', x=547.41, y=75.13, z=831.38], EntityCreeper['爬行者'/7258, l='MpServer', x=617.96, y=75.00, z=738.44], EntityZombie['僵尸'/7012, l='MpServer', x=527.50, y=72.00, z=749.50], EntitySkeleton['骷髅'/7017, l='MpServer', x=530.50, y=72.00, z=750.50], EntitySkeleton['骷髅'/7027, l='MpServer', x=529.22, y=72.00, z=755.13], EntitySkeleton['骷髅'/7028, l='MpServer', x=532.50, y=72.00, z=758.50], EntitySkeleton['骷髅'/7029, l='MpServer', x=531.00, y=72.00, z=756.91]]
> 	Retry entities: 0 total; []
> 	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
> 	Server type: Non-integrated multiplayer server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:120)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_91, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 387130552 bytes (369 MB) / 622899200 bytes (594 MB) up to 1060372480 bytes (1011 MB)
> 	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
> 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 33 mods loaded, 33 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
> 	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
> 	UCHIJA	betterfps{1.0.0} [BetterFps] (minecraft.jar) 
> 	UCHIJA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
> 	UCHIJA	LambdaLib|Core{1.2.2} [LambdaLib|Core] (minecraft.jar) 
> 	UCHIJA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
> 	UCHIJA	NotEnoughItems{1.0.3.74} [Not Enough Items] ([NEI]NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
> 	UCHIJA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
> 	UCHIJA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
> 	UCHIJA	LambdaLib{1.2.2} [LambdaLib] ([lib]LambdaLib-1.2.2.jar) 
> 	UCHIJA	academy-craft{1.0.3} [Academy Craft] ([AC]AcademyCraft-1.0.3.jar) 
> 	UCHIJA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] ([AE]appliedenergistics2-rv3-beta-6.jar) 
> 	UCHIJA	FastCraft{1.21} [FastCraft] ([FPS优化]fastcraft-1.21.jar) 
> 	UCHIJA	Waila{1.5.4a} [Waila] ([NEI]Waila v1.5.4a.jar) 
> 	UCHIJA	wawla{1.0.4} [What Are We Looking At] ([NEI]Wawla-1.0.4_1.7.10.jar) 
> 	UCHIJA	UnicodeFontFixer{1.1.3} [UnicodeFontFixer] ([字体修复]UnicodeFontFixer-1.1.3-mc1.7.10.jar) 
> 	UCHIJA	IC2{2.2.823-experimental} [IndustrialCraft 2] ([工业]industrialcraft-2-2.2.823-experimental.jar) 
> 	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
> 	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] ([神秘时代]M-Thaumcraft-1.7.10-4.2.3.5-SaraFix-a1.jar) 
> 	UCHIJA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
> 	UCHIJA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] ([禁忌魔法]Forbidden Magic-1.7.10-0.575.jar) 
> 	UCHIJA	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] ([竹]Bamboo-2.6.8.5.jar) 
> 	UCHIJA	IC2LaserFix{2.0} [IC2 Laser Fix] ([镭射修复]IC2LaserFix-1.7.10.jar) 
> 	UCHIJA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] ([高级太阳能]AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar) 
> 	UCHIJA	CustomStuff2{0.11.29} [Custom Stuff 2] (CustomStuff2-0.11.29-MC1.7.10.jar) 
> 	UCHIJA	UBB{1.0.0} [UBB] (CS2_UBB) 
> 	UCHIJA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (DamageIndicators 伤害与血量显示 v3.2.0.jar) 
> 	UCHIJA	flenixcities{0.13.0} [FlenixCities] (FlenixCitiesCore_[1.7.10]-0.13.0-b105.jar) 
> 	UCHIJA	mo{0.4.1} [Matter Overdrive] (MatterOverdrive-1.7.10-0.4.1.jar) 
> 	UCHIJA	flammpfeil.slashblade{mc1.7.10-r85} [SlashBlade] (SlashBlade-mc1.7.10-r85.jar) 
> 	UCHIJA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
> 	UCHIJA	ArmorStatusHUD{1.27} [ArmorStatusHUD] (耐久显示.jar) 
> 	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics'
> 	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
> 	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
> 	Launched Version: 1.7.10
> 	LWJGL: 2.9.1
> 	OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.4229, Intel
> 	GL Caps: Using GL 1.3 multitexturing.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Anisotropic filtering is supported and maximum anisotropy is 16.
> Shaders are available because OpenGL 2.1 is supported.
> 
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: []
> 	Current Language: 简体中文 (中国)
> 	Profiler Position: N/A (disabled)
> 	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	Anisotropic Filtering: Off (1)

**Comment by KSkun** [comment]
不支持GL33的显卡将不受支持
The video cards which don't support GL Version 3.3 are no longer under support.
