### ISSUE TITLE
[Enhancement] 有关御坂云终端一些可改进的地方

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#456]
~~由于御坂云终端的右侧边栏在阅读正文时毫无帮助，可以考虑加入一个隐藏右侧边栏的功能，使正文区域更加开阔，这样也许可以加入一些更大的图片。~~
同时，还可以加入为正文调整字号的功能，有助于屏幕小的人阅读。

**Comment by Paindar** [comment]
@nirvanaxiao6 有时间的话可以考虑更新一波
