### ISSUE TITLE
[1.0.3] 服务器中重新登入会造成能力信息重置

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#469]
经过测试发现  使用KCauldron-1.7.10-1614.188开服  超能力始终重置
但是用cauldron-1.7.10-1.1388.1.0开服超能力就是正常的，不会重置
不过使用cauldron-1.7.10-1.1388.1.0无法启动AC1.0.2及其以上版本

From feedback@li-dev.cn 635534556@qq.com

**Comment by Paindar** [comment]
过期+无法重现
