### ISSUE TITLE
[1.0.4] AB: 管理领地权限存在漏洞

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#473]
加了超能力识别领地的插件之后发现了两个问题
1.电气使的磁场控制可以拿起或放置无权限领地的铁质方块
2.电气使可以令领地里的木质方块着火

**Comment by EAirPeter** [comment]
这issue该丢隔壁啊。。。

**Comment by KSkun** [comment]
Check https://github.com/LambdaInnovation/AcademyBukkit/issues/1
