### ISSUE TITLE
[1.0.4] 标记传送客户端崩溃

### ISSUE THREAD

**Issue by hongfen** [LambdaInnovation/AcademyCraft#476]
~~空间使的放置方块的技能在关闭方块破坏的服务器无法使用，经验无法增加，最终技能也无法学习~~
Duplicate with #468

**Comment by hongfen** [comment]
另外，现在我一按标记传送，客户端就崩溃

**Comment by hongfen** [comment]
求解

**Comment by hongfen** [comment]
==

**Comment by KSkun** [comment]
@hongfen 请提供崩溃报告以及更详细的信息。

**Comment by hongfen** [comment]
OK

**Comment by hongfen** [comment]
![Uploading image.png…]()

**Comment by hongfen** [comment]
![Uploading @@7Q18RA8@ZHW(WP{NMK5HR.png…]()

**Comment by hongfen** [comment]
![0o nn s hx5n9ww nd9 b](https://cloud.githubusercontent.com/assets/20910295/17504565/b1a1faf8-5e2c-11e6-9cfe-878e7c75b544.png)

**Comment by hongfen** [comment]
![7q18ra8 zhw wp nmk5hr](https://cloud.githubusercontent.com/assets/20910295/17504581/d509115c-5e2c-11e6-9bf3-31620701a0d8.png)

**Comment by hongfen** [comment]
![ci 06c_xcow9ufeq1z 0rm](https://cloud.githubusercontent.com/assets/20910295/17504593/e9cf4868-5e2c-11e6-99d9-0c77e3381330.png)

**Comment by KSkun** [comment]
你好，你可以将其粘贴在
http://pastebin.ubuntu.com/
并把地址发来。

**Comment by hongfen** [comment]
哦

**Comment by hongfen** [comment]
你这样看不行吗--

**Comment by hongfen** [comment]
方便加下QQ吗

**Comment by hongfen** [comment]
给图方便

**Comment by KSkun** [comment]
抱歉，不方便。你可以把文本粘贴到上述网站或者将其发至feedback@li-dev.cn。谢谢合作。

**Comment by hongfen** [comment]
哦

**Comment by hongfen** [comment]
那空间使技能经验无法获得的那个BUG呢？

**Comment by KSkun** [comment]
已经在issue描述中标注与已有issue #468 重复。

**Comment by hongfen** [comment]
但是我听不懂你说的==

**Comment by hongfen** [comment]
只能打开文本，不能放图片啊

**Comment by KSkun** [comment]
图片建议你发至feedback@li-dev.cn。

**Comment by hongfen** [comment]
这个打不开啊

**Comment by hongfen** [comment]
QAQ

**Comment by hongfen** [comment]
是AC的官网？

**Comment by hongfen** [comment]
当我没说，脑抽了，sorry

**Comment by KSkun** [comment]
你好。
提交崩溃报告和相关信息至邮箱后我们将进一步处理。
如果需要其他信息我们会通过邮箱联络你。
感谢你的反馈。
