### ISSUE TITLE
[1.0.4] 部分技能不能击碎面前的方块

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#480]
已知影响技能有 Groundshock DirBlast Meltdowner

**Comment by Paindar** [comment]
初步怀疑是因为取整问题。
对于某一坐标值为-3.x的位置，强行使用(int)或.toInt会导致其成为-3，而在MC中-3代表的是隔壁方块，因此调整为(int)Math.floor()或.floor.toInt
