### ISSUE TITLE
[1.0.4] 更新后服务器所新创建的世界无法使用超能力

### ISSUE THREAD

**Issue by Scaleph** [LambdaInnovation/AcademyCraft#481]
1.0.3还好，只不过这只出现在新创建的世界里，使用与开发都无法进行。
原本在主世界满级的超能力者在新世界也会失去能力。
使用的Multiverse-Core-2.5多世界插件。
在1.0.4个更新中我并没有发现有新增设置可以调整这个问题，请求解答！感谢！

**Comment by WeAthFoLD** [comment]
具体的来说是怎样无法使用超能力？按V和N都无法调出相关界面么？以及请提供一下你所使用的客户端/服务端的相关配置和其他Mod。

**Comment by Scaleph** [comment]
全部无效=.= 就是根本不能使用任何超能力有关的物品与能力（包括数据终端与mod方块）
客户端1.7.10 服务端……所有插件都需要列出来吗？ 其他mod全部？

**Comment by Scaleph** [comment]
客户端1.7.10
CoroUtil-1.0
ZombieAwareness-1.9.2
SlashBlade-mc1.7.10-r85
ShinColle-1.7.10.rv26_無Forge限制 
Flans Mod-1.7.10-4.10.0
CustomNPCs_1.7.10c
Bamboo-2.6.8.5
MrCrayfishFurnitureModv3.4
这是所有需要服务器端支持，实际新增物品、方块与生物mod
CodeChickenLib版本：1.7.10-1.1.1.106-universal

**Comment by Scaleph** [comment]
关于服务端口：
从1.0.2开始没有任何异常、没有进行任何特殊设置仅仅在1.0.2时关闭了方块破坏，升级为1.0.3后没有进行任何调整进行游戏，后直接升级为1.0.4
升级为1.0.4后发现1.0.2之后新增的世界全部无法使用超能力仅有一直存在的生存世界与主世界可以使用资源世界在超能力更新到1.0.4之后重置，也无法使用超能力。
无法使用的情况为：超能力无法开发80%左右卡住不动，已开发的超能力在新增世界无法激活使用，能力抑制方块无法激活，在其他世界已安装的数据终端无法使用。
