### ISSUE TITLE
[1.0.4]服务器无法使用部分超能力

### ISSUE THREAD

**Issue by Love-collapse** [LambdaInnovation/AcademyCraft#488]
传送使的转移传送无法在服务器中传送
不管在什么情况下 都没办法扔出去方块
单人测试正常

**Comment by KSkun** [comment]
你好，请告诉我们更具体的信息。
如服务端的种类和版本、Forge版本等信息。

**Comment by m1583525155** [comment]
Thermos-1.7.10-1614-57-server 和 KCauldron-1.7.10-1614.188都存在此bug
