### ISSUE TITLE
[1.0.4] 退出游戏重进后各个能源节点的连接会断开

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#497]
forge版本：1.7.10-forge10.13.4.1558-1.7.10
非多人游戏

**Comment by Paindar** [comment]
未能发现此现象。
forge版本：1.7.10--forge10.13.4.1614

**Comment by Paindar** [comment]
未能发现此现象+1.
无法重现+历史遗留。
