### ISSUE TITLE
[1.0.4] 转移传送会一次消耗2个方块

### ISSUE THREAD

**Issue by voidcl** [LambdaInnovation/AcademyCraft#501]
这个转移传送是使用一次消耗两格方块么？奇怪的是我使用到最后2格物品的时候可以使用两次，如下图：
1图中拿出了一组圆石，二图开始使用技能，三图技能使用完毕，可见使用了两块原石，四图分出了2块单独的圆石，五图使用技能，六图可见两块原石使用了两次，加起来消耗了4块原石但是只出现3块方块
![2016-08-23_09 44 16](https://cloud.githubusercontent.com/assets/20895139/17877509/67c78a0c-6916-11e6-9b5a-2a566479e063.png)
![2016-08-23_09 44 20](https://cloud.githubusercontent.com/assets/20895139/17877510/67ea9fe2-6916-11e6-9963-36c6b92903b9.png)
![2016-08-23_09 44 24](https://cloud.githubusercontent.com/assets/20895139/17877506/658ad4ec-6916-11e6-9bb1-7116dc738d0c.png)
![2016-08-23_09 44 35](https://cloud.githubusercontent.com/assets/20895139/17877505/657c255a-6916-11e6-8237-740da3a24b38.png)
![2016-08-23_09 44 43](https://cloud.githubusercontent.com/assets/20895139/17877507/6639761e-6916-11e6-86a9-33b00508917b.png)
![2016-08-23_09 44 58](https://cloud.githubusercontent.com/assets/20895139/17877508/663a2834-6916-11e6-8ee2-3fd0866a2c88.png)

~~另外，mod中的无线能源系统，在我配置的IC2，BC环境中有一定几率出现能量无法从节点输送到能源桥的情况，而且有重复出现的迹象，不是偶然的错误，亲测大概4个小时出现2-3次。一般发生在我长时间打开游戏的情况下，具体情况表现为节点中能量满，但是与能源桥相连的IC2机器或者BC炼油厂无法获得对应的能量输入，退回首届面再进入该世界可以解决这个问题~~

**Comment by KSkun** [comment]
你好，该技能应该只消耗1个方块。应该属于bug。
另外一个问题已经帮你转到 #502 。

**Comment by voidcl** [comment]
(=ﾟωﾟ)ﾉ辛苦了。。顺带一提，本人是即将大三的软件工程学生，非常喜欢这个模组，不知道能不能有幸加入你们的团队ಠ_ಠ

**Comment by KSkun** [comment]
https://ac.li-dev.cn/aboutpage_zhcn/
可以在这里找到加入我们的方式哟，欢迎你加入Lambda Innovation

**Comment by voidcl** [comment]
哦～了解了，我去试试看(=ﾟωﾟ)ﾉ
