### ISSUE TITLE
[1.0.4] 能源桥一段时间后会中断从节点处取电

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#502]
mod中的无线能源系统，在我配置的IC2，BC环境中有一定几率出现能量无法从节点输送到能源桥的情况，而且有重复出现的迹象，不是偶然的错误，亲测大概4个小时出现2-3次。一般发生在我长时间打开游戏的情况下，具体情况表现为节点中能量满，但是与能源桥相连的IC2机器或者BC炼油厂无法获得对应的能量输入，退回首届面再进入该世界可以解决这个问题。

**Comment by Paindar** [comment]
我们需要更多的信息来确认BUG的发生点，在此之前我建议保持观望。
Close.
