### ISSUE TITLE
[Feature] Config synchronization

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#507]
# 问题描述

目前，AC的技能自定义数据文件（`academy-craft-data.conf`）未在客户端和服务端进行同步，在玩家进入服务端时两边可能享有的设置不一样。例如，在服务端禁用了一个技能，而客户端并没有。这可能会造成严重的游戏逻辑和同步问题。

# 解决方案

在玩家进入服务器时，将服务端的配置发送到客户端，并在玩家在此服务端的时间内使用这个配置副本。玩家进行客户端游戏时，再使用本地的配置。

**Comment by Paindar** [comment]
虽然有偷懒的嫌疑，但是个人不建议把公共数据（技能数据等）和私有数据（UI位置等）合并在一个config里。

**Comment by WeAthFoLD** [comment]
同意，这里config确实需要分的更明确，把服务端应该负责的部分分离出来做一个单独的config，剩下的放在另一个。

**Comment by Paindar** [comment]
我感觉我想多了。。一开始我以为ACConfig里还包括GUI的位置等内容，不过现在看来是完全没有的，因此貌似也没有特别需要分离的地方。。嗯。。
