### ISSUE TITLE
[1.0.4] 矢量反射技能特效没有正常终止

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#508]
开矢量反射将cp耗尽，刚恢复时再开再次耗尽cp后会永久有开启反射的游戏显示（就是屏幕上一个一个的黑圈）但是不会真正反射伤害，和没开一样

**Comment by Paindar** [comment]
在一个已知的版本中 通过开启矢量反射而将CP耗尽后矢量反射并不会关闭，而是继续运行。但此时会消耗掉刚恢复的CP,且在遭到攻击时依然会产生音效，被攻击者依然会受到伤害。

**Comment by Paindar** [comment]
另外 在开启矢量反射的情况下退出游戏游戏，进入另一个游戏，矢量反射的特效不会消失。
