### ISSUE TITLE
[1.0.4] Vector Deviation crashes the game

### ISSUE THREAD

**Issue by DestinyPlayer** [LambdaInnovation/AcademyCraft#509]
Basically that.
http://pastebin.com/eFa4DBrH - The crashlog
http://pastebin.com/eFa4DBrH - The modpack
Forge 10.13.4.1614
AcademyCraft 1.0.4

**Comment by DestinyPlayer** [comment]
The worst thing, it only crashes the game for one of my friends. For me, it works perfectly. For everybody else, it works perfectly. But for that friend it crashes the game. I honestly have no idea why. The only thing I could gather from the crash log is that it's failing to find a target or something.

**Comment by ACSBlock** [comment]
You use what server core

**Comment by DestinyPlayer** [comment]
Pure Forge, no Bukkit.

**Comment by KSkun** [comment]
Hi, there.
We found that your video card driver does not support OpenGL version 3.3.0. You can try to update your driver or replace your video card with a newer one that supports GL3.3.0.

Thanks for your feedback and good luck. :)
