### ISSUE TITLE
建议在配置文件中加入"单独控制原子崩坏是否可以采集方块“的项

### ISSUE THREAD

**Issue by ACSBlock** [LambdaInnovation/AcademyCraft#511]
建议在配置文件中加入"单独控制原子崩坏是否可以采集方块“的项
大家都知道，如果将destroyBlocks=true改成destroyBlocks=false所有的技能将无法破坏方块；
但是原子崩坏的所有采集技能将毫无乱用；
在服务器中，这是个头疼的问题，为了地图不被肆意破坏，很多服主选择destroyBlocks=false；
但是原子崩坏能力的玩家的所有采集技能将毫无乱用；
建议添加“能力技能不能破坏方块，但原子崩坏的采集技能可以采集方块”。

**Comment by nirvanaxiao6** [comment]
这个功能在academy-craft-data.conf文件中已经加入设置，可以直接调整那个文件中的采矿光束的破坏方块设置。

**Comment by ACSBlock** [comment]
可以教我如何设置吗？

________________________________
发件人: nirvanaxiao6 <notifications@github.com>
发送时间: 2016年9月3日 10:19:46
收件人: LambdaInnovation/AcademyCraft
抄送: ACSBlock; Author
主题: Re: [LambdaInnovation/AcademyCraft] 建议在配置文件中加入"单独控制原子崩坏是否可以采集方块“的项 (#511)


这个功能在academy-craft-data.conf文件中已经加入设置，可以直接调整那个文件中的采矿光束的破坏方块设置。

―

**Comment by nirvanaxiao6** [comment]
您可以在ac官网恢复后到wiki的杂项页面阅读详细信息。
