### ISSUE TITLE
[Enhancement]在config文件中设置“方块破坏设置例外的世界”处添加世界ID的说明。

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#516]
在academy-craft.cfg中的Line 59 and 60.
很多人都不太清楚如何添加世界的值，我认为给出说明（或者例子）是很重要的。

**Comment by KSkun** [comment]
希望能够在Wiki中给予说明，配置文件中的注释行数有限。

**Comment by nirvanaxiao6** [comment]
已经有所说明，但显然只有极少一部分人会去看wiki，故此提出一个建议
