### ISSUE TITLE
GUI is completely broken

### ISSUE THREAD

**Issue by haku-81** [LambdaInnovation/AcademyCraft#520]
When trying to use the misaka cloud terminal, or really any GUI, it's completely unusable, see attached screenshot.
The version of everything i'm using is
java 8 update 101 64 bit
minecraft 1.7.10-predictably
forge version-10.13.4.1614
academycraft-1.0.4-though i've had this issue with several other versions i've tried, and it is very persistent, happening every time without fail.
lambdalib-1.2.3

and just in case it helps, i'm using curse forge, and no other mods are installed.

![2016-09-09_00 09 52](https://cloud.githubusercontent.com/assets/9521080/18378530/6a8fb232-7622-11e6-8cd7-7b4dda6d389f.png)

**Comment by Paindar** [comment]
Could you tell me your video card model and version of the driver for your video card?

**Comment by haku-81** [comment]
Now it all makes sense, not sure how i never thought of that. I'm on a toshiba satellite C655-S5049 running windows 7, and it's very old. The only reason i'm not on windows 10 is because minecraft doesn't run at all due to outdated graphic drivers. Just another reason to work towards a good pc then.
