### ISSUE TITLE
[1.0.4]熟练度显示问题

### ISSUE THREAD

**Issue by qqaaaagg** [LambdaInnovation/AcademyCraft#521]
可能由于显示时的舍入，偶尔会出现熟练度显示值满足另一技能的前置，在另一技能的页面仍显示不满足，再提升少量熟练度才满足条件

**Comment by Paindar** [comment]
你好。
感谢你的反馈，事实上我们已经注意到这一问题，并且下个版本将会改进此方面的细节。

再次感谢你的反馈以及你对AcademyCraft的支持。
