### ISSUE TITLE
[1.0.4]"电磁牵引"技能改进建议

### ISSUE THREAD

**Issue by 553061224** [LambdaInnovation/AcademyCraft#522]
电磁牵引并不是很好用,距离有些短并且瞄准距离难以掌握.
建议改进增长一点距离,并按住技能键,能保持技能在发现可以牵引的物体后锁定并自动施放技能.
英文的界面我不知道如何选择tag,抱歉..

**Comment by ACSBlock** [comment]
同意，刚想发这个讨论的！
