### ISSUE TITLE
1.0.4版本指令无效并且无法开发能力

### ISSUE THREAD

**Issue by 2982450157** [LambdaInnovation/AcademyCraft#526]
该版本指令显示不存在，并且能力开发机种一旦开始开发进度条一直显示00%卡住不动，另外金属处理机点开会崩

**Comment by Paindar** [comment]
请给出具体的服务端和客户端forge、java、Lambda版本等信息。

**Comment by 2982450157** [comment]
单机 
forge：forge-1.7.10-10.13.4.1448-1.7.10-installer-win
Java：jre1.8.0_101
Lambda：1.2.3
注：版本若换为1.0.2及更低 以上皆正常

**Comment by KSkun** [comment]
请使用更新版本的Forge并且重试。
需要的Forge版本应该高于10.13.4.1517.
