### ISSUE TITLE
[1.0.4]单个技能配置修改无效及某些世界无法开发能力

### ISSUE THREAD

**Issue by 1098270209** [LambdaInnovation/AcademyCraft#528]
*以下问题皆出现于服务器中。

①在配置文件academy-craft-data中不是可以修改某个技能是否可以学习嘛，但是测试后发现依旧可以学习这个技能，该技能的cp消耗等配置也都是修改无效。还是我的格式错误了？
        storm_wing {
          enabled: false,
          damage_scale: 1.0,
          cp_consume_speed: 1.0,
          overload_consume_speed: 1.0,
          exp_incr_speed: 0
        }
例如这个，本来想禁止玩家学习这个风之翼的，毕竟在服务器里这个技能不太合适出现的= =但是修改为false后依旧可以学习技能。
不过该配置文件的其他内容都是可以修改的，只有这一段是修改无效。

②实测某些mod世界是不兼容能力开发的。例如御宅工艺的黑岩世界以及上古世界。在主世界开发能力后，传送到这两个世界，是无法使用能力的，或者说根本没开发能力。而在这两个世界试图开发能力也是无效的。开发进度0%
其他mod没测试过，不过应该也会有这种问题。

③顺带一提，AcademyCraft与匠魂的附属mod有冲突。一个是ExtraTiC 1.4.6。另一个是TiCTooltips 1.2.5。
这两个mod更换低版本后可解决冲突。

【服务器核心为Kcauldron。Forge版本是1614】

**Comment by Paindar** [comment]
①关于禁止学习，这可能是因为客户端上的配置文件没有更新所导致。我们已经在新版本中修复了这个bug（但是新版本还在路上→_→），权宜之计是通知客户端修改配置。

②参见issue#504.进度如①。

③参见issue#465. 
目测这bug是没有办法修复的...解决方法（虽然只是work around）是安装CoFH Core。
Ref: SlimeKnights/TinkersConstruct#1662, SlimeKnights/TinkersConstruct#1722
