### ISSUE TITLE
[1.0.4] Cannot use Meltdowner level 2 abilities

### ISSUE THREAD

**Issue by lOmicronl** [LambdaInnovation/AcademyCraft#529]
Hello,

I play on a server with Academycraft 1.0.4 installed. It is a lot of fun! But, as a Meltdowner, I can only use Electron Bomb. I have learned both Scatter Bomb and Light Shield, but I cannot cast them. It instantly overloads me, and nothing happens. I am already 80% towards Meltdowner 3, only from using Electron Bomb.

I am the only Meltdowner on the server so far. Everyone else has other classes, and they do not have any problems.

I found something like this described in #274, but that was may months ago, in an older version. Is that an old bug that has reappeared?

I apologize if this bug has already been reported. I cannot read the Chinese entries.

**Comment by Paindar** [comment]
well...it's...**DATA ERROR**.
You are right, it's a **BUG**.
Congratulation, we have more bug to fix.
---------------------------------------------
In fact, skill data should be able to grow. But, we forget to add it, and it'll be fixed soon.

This answer is created by Google Translator.

**Comment by lOmicronl** [comment]
Thank you for your work! =)
