### ISSUE TITLE
type learn than nothing happens

### ISSUE THREAD

**Issue by redDragon73** [LambdaInnovation/AcademyCraft#532]
when i try to get powers it says booting then booting failed it then says type learn the nothing happens

**Comment by Paindar** [comment]
Well.
Everything you said is normal until it said type learn, if it's first time getting power.
I'm not sure what happened. Maybe you can check if energy is enough, etc.
If you still have no idea, please tell us the version of the forge , AcademyCraft ,Java.
Thank you for your support.

**Comment by XCreeper1207** [comment]
This is also happening to me as well it's a real issue you cant start the mod at all. All what happens is it says starting simulation and 00% and doesn't go up. Please fix this bug I really wanna try out this mod.

**Comment by Paindar** [comment]
Please ckeck if the version of your forge is 1.7.10-1558 or higher.

**Comment by XCreeper1207** [comment]
Wow would you look at that. It works now thanks I had an outdated version of forge
