### ISSUE TITLE
[1.0.4][服务器]服务器加入后无限崩溃重启，图在2楼，急

### ISSUE THREAD

**Issue by k0to** [LambdaInnovation/AcademyCraft#536]
![-47e0e065e022b26e](https://cloud.githu急sercontent.com/assets/23167357/19852897/11d83124-9f34-11e6-8e6f-e5568f2323a9.png)如图，ji

**Comment by k0to** [comment]
![-47e0e065e022b26e](https://cloud.githubusercontent.com/assets/23167357/19852983/7a794d3a-9f34-11e6-93be-539e971222f6.png)

**Comment by Paindar** [comment]
请确保你的服务器forge版本在1558，至少是1517以上。
请不要问我们如何获知服务器版本。

**Comment by k0to** [comment]
非常感谢，有时间试试看
