### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by Kenovada** [LambdaInnovation/AcademyCraft#538]
Crash on Loading screen

List of Mods:
SecurityCraft
AcademyCraft
BuildCraft
CodeChickenCore
CustomModSpawner
Mo' Creatures
Electrical Age
ExtraUtilities
IC2 Nuclear Control
iChunUtil
IndustrialCraft
InventoryTweaks
Magical Crops
Magical Crops Armory
Mantle
MCA
Morph
MrCrayFishFurniture
NEI
OpenModularTurrents
RadixCore
Redstone Paste
Runic Dungeon
TConstruct
Thaumcraft
TMechworks
Twilight Forest
Wailia
Xaeros Minimap

[crash-2016-11-20_00.19.45-client.txt](https://github.com/LambdaInnovation/AcademyCraft/files/601902/crash-2016-11-20_00.19.45-client.txt)

**Comment by Kenovada** [comment]
I have discovered the error. LambdaLib is not posted as a requirement on Curse and other host.

**Comment by Zsashas** [comment]
Good thing I thought to check here before making an issue...thank you.
