### ISSUE TITLE
[Suggestion] About Teleporter

### ISSUE THREAD

**Issue by Niconoko** [LambdaInnovation/AcademyCraft#540]
Is it possible to add a feature when throw needle at mob and the needle stick onto mob like arrow did?
and another one to suggest if the needle can be strengthen or propertizing like poisonous, blindness, or slowness.

PS. Idk how to code, so I'll just leave some suggestions here then.
PS. I know this is not the video section, but I want to share my series that I'm doing this mod + roleplay, or if there a proper forum of this mod, please say so, maybe I could just share it there instead.
> http://www.youtube.com/playlist?list=PLSp4Qq8LFJ6wVnJ02E7_kz7Lc8v4Cany6

Thank you :3

**Comment by DarianLStephens** [comment]
The thing with teleporting needles is that you're not throwing them, you're directly putting them inside the mob's body, wreaking havoc on their internals. (When it comes to skeletons or other organless creatures, though... Don't think about it.)

**Comment by Renniuq** [comment]
That would in fact mean the "sticking in like arrows" would be contrary to the... lore? I guess, of how the ability works - but the ability to poison the needles would fit in perfectly, since you would deliver said poison directly into the target.

**Comment by Paindar** [comment]
A good idea, actually.
But now it's out of my plan.
Recently I'm trying to fix bug, having no time to add more feature. 
In fact,poisonous needles is considered as Medicine System, although our leader is afk.
I hope I can add these features somedays, because what I can do now is to fix some bugs.
