### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by Erzats-Weird** [LambdaInnovation/AcademyCraft#545]
I'm playing 1.7.10, using the curse client and upon death, the game crashes. I've attached the full list of mods used as well as the full error report. 
[AcademyCraft.pdf](https://github.com/LambdaInnovation/AcademyCraft/files/672321/AcademyCraft.pdf)
[Minecraft Crash Report.pdf](https://github.com/LambdaInnovation/AcademyCraft/files/672322/Minecraft.Crash.Report.pdf)

**Comment by Paindar** [comment]
1.0.5 is unstable, try 1.0.4 or 1.0.6.

**Comment by Zsashas** [comment]
Does it keep crashing when you load up the game, or is it a one-time crash?
