### ISSUE TITLE
伺服器里别人无法使用任何此模组的东西，一旦使用就会崩溃Others player cant use things in mod

### ISSUE THREAD

**Issue by Julius27** [LambdaInnovation/AcademyCraft#546]
比如Red是服主：一切东西完美运行。
然后其他玩家进入伺服器后：服主的一切模组东西完美运行，但tygtyg却不能用任何东西。就算用到也会崩溃.

such as Red is the one who open server:The mod work normally.
when a player come:He cant use anything of the mod. Even though command.

version: AcademyCraft 1.0.6
版本：AcademyCraft 1.0.6

**Comment by Paindar** [comment]
你能确定tygtyg的forge版本高于1517吗？对于那些低版本有时候会出现你所说的情况。。

**Comment by Julius27** [comment]
forge版本是最高了，是不是显示卡的问题呢？

**Comment by Paindar** [comment]
如果你所说的是跨服类mod的话，这个bug还需要对AC进行更深的排查，因此暂时无法为你解决这个issue.

**Comment by Paindar** [comment]
可以试试104版本，不知道1.0.4是否会有一样情况。
