### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by Zsashas** [LambdaInnovation/AcademyCraft#547]
https://gist.github.com/Zsashas/93d4844a44b4b81461933bda57eb3117

**Comment by liach** [comment]
Remove dragonapi and try again.

**Comment by Zsashas** [comment]
I just realized that the Gist doesn't have the entire log even...hold on, let me try to find it...

**Comment by Zsashas** [comment]
This might actually be a Botania thing, going to wait and see if Vazkii or anyone else over there knows the problem.

**Comment by Zsashas** [comment]
Alright, trying to make a new world got me a whole new crash...

https://gist.github.com/Zsashas/625a5cd83aa87fbfd378c33925c27aaa

**Comment by Paindar** [comment]
DO NOT USE ACADEMYCRAFT 1.0.5.

**Comment by Zsashas** [comment]
Um...is there a reason why? Curseforge doesn't say anything, isn't even marked as beta.

**Comment by Paindar** [comment]
There is something wrong with 1.0.5, and I didn't realize that when I released it...
