### ISSUE TITLE
[bug?]AC v1.0.6中关于电击使的磁场控制和电磁牵引技能的问题

### ISSUE THREAD

**Issue by knight826** [LambdaInnovation/AcademyCraft#551]
在v1.0.6中，磁场控制不能投掷石制方块，技能熟练度没有满，是否是因为技能熟练度的问题？电磁牵引对石制方块使用无特效无位移效果，但是有技能熟练度的增长，在满熟练度的情况下对石制方块使用依旧无特效无位移效果。请问是不是bug，还是原来可以这样做不符合能力设计的意图而修正了？

**Comment by Paindar** [comment]
事实上不完全是因为熟练度【因为我也不知道你熟练度到多少了】，但是可以肯定的是如果没改配置的话，你一定是动不了石头的【笑】。
我们确实实现了这一功能，但是这功能是依赖mod配置的，如果没有设置的话，动不了石头应该很正常吧邮编

**Comment by knight826** [comment]
了解了，感谢解答 @Paindar
