### ISSUE TITLE
求助，，，，，，

### ISSUE THREAD

**Issue by Hatsunemikuwu** [LambdaInnovation/AcademyCraft#556]
为什么将lambdalib和academycraft这两个文件放入mods文件夹就用打不开了

**Comment by Hatsunemikuwu** [comment]
Why lambdalib and academycraft these two files into the mods folder can not be used to open

**Comment by Hatsunemikuwu** [comment]
<img width="389" alt="sketch" src="https://cloud.githubusercontent.com/assets/25241602/22142890/f80d6e1e-df32-11e6-9060-323c48e6abf6.png">

**Comment by Hatsunemikuwu** [comment]
<img width="392" alt="sketch 1" src="https://cloud.githubusercontent.com/assets/25241602/22142930/20dee7d2-df33-11e6-88c7-221eda8c1f3e.png">

**Comment by Paindar** [comment]
机翻满分。
打不开的原因自行查看官方wiki。

**Comment by Hatsunemikuwu** [comment]
哈哈哈英语不行
