### ISSUE TITLE
AC1.0.2或以上無法用MCPC server?

### ISSUE THREAD

**Issue by LochNessX** [LambdaInnovation/AcademyCraft#560]
進入就會斷線，問題在1.0.1版或以下不會出現。
AC1.0.2或以上，在MCPCserver雖然能夠開到，但進不到，進入時閃退

**Comment by Paindar** [comment]
據我所知MCPC沒有高於10.13.4.1448的forge版本。

**Comment by LochNessX** [comment]
原來如此，了解。感謝
即是解決方法是用原版server，
或者等有生之年系列的MCPC更新

**Comment by Paindar** [comment]
可以试试KCauldron.
