### ISSUE TITLE
电磁牵引技能问题

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#562]
在使用‘电击使’的‘电磁牵引’技能时，当你没有选中磁力钩进行移动时你仍然可以获得技能经验和等级经验。而且不会消耗cp和增加过载值。

**Comment by Mastize** [comment]
从技能设计上来讲，这个技能是可以作用于任何铁质方块的
至于不消耗CP不增加过载的问题，并不存在于1.0.6版本中
如果没有更详细的描述基本可以认为是误报
