### ISSUE TITLE
标记传送技能的标记超过一页的时候游戏会崩溃

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#563]
空间使标记传送技能，标记超过一页的时候游戏崩溃出现A fatal error has occured,this connection is terminated.之后只要进地图就会崩溃弹出这句话，删除mod后可正常进入地图，重新安装mod依旧崩溃

**Comment by Paindar** [comment]
那么问题来了，传送使的标记要怎么超过一页，还有那是坐标传送吧喂【】
