### ISSUE TITLE
Skills can't be learned, activated or be used in some alien dimensions [AC v1.0.6]

### ISSUE THREAD

**Issue by Niconoko** [LambdaInnovation/AcademyCraft#566]
I'm not certain if it would happen with other mod dimension? but the dimension where I'm referring here are from the "Aliens Vs Predator v4.0.0.755". [Dimension name; LV-223 (Varda) and LV-426 (Acheron)]

![2017-02-07_14 45 04](https://cloud.githubusercontent.com/assets/24541618/22683961/e498317a-ed4c-11e6-9bd9-1d1e84a9c30a.png)
- ^ All the skill can't be activated or be used at all. (Both creative and survival mode)
PS. I have to learn the skill from overworld and jump into this dimension to test.
PS. The ability seems to be deactivated once I have got into this dimension.

![2017-02-07_14 45 23](https://cloud.githubusercontent.com/assets/24541618/22683964/e79bf19a-ed4c-11e6-933b-dfe49df42fb3.png)
- ^ The ability developer can't be clicked in. (Already powered)

![2017-02-07_14 45 52](https://cloud.githubusercontent.com/assets/24541618/22683965/e8b73044-ed4c-11e6-9552-b3dc06bba89e.png)
- ^ The portable developer can be clicked in, but can't type "learn" to learn any skills. (5 minutes passed by, the progress is still going 00%)

One more thing to mention, I think the first skill of Vector Manipulator (the holding charge punch) has a strange bug, when set the skill into the left mouse click, while holding the left click, player will constantly punching by its own, even I have released the left click.

That's all for now, Ty in Adv :3

**Comment by Paindar** [comment]
Is it similar to issue#504？

**Comment by Niconoko** [comment]
I'm not sure, but will it be fixed if I lower down the dimension number?

**Comment by Niconoko** [comment]
... It does fixed, problem solved, thank you for a quick fix :3
