### ISSUE TITLE
A Certain Teleporter Problemo

### ISSUE THREAD

**Issue by BanditOfManJuice** [LambdaInnovation/AcademyCraft#568]
Whenever you max out your mark teleport and use it to teleport, the hologram stays where it is and it doesn't go away unless you reset.

1.https://gyazo.com/0998e06e8cc9a9ac8c1b02f89096c8a9
                                            I
                                            I
                                            I
                                           V
2.https://gyazo.com/9e36c996edeacaf3bc6b5afefe5752dd

**Comment by Paindar** [comment]
fixed in issue #544
