### ISSUE TITLE
关于新版本的细节问题

### ISSUE THREAD

**Issue by bilser** [LambdaInnovation/AcademyCraft#569]
希望在新版本可以增加一个风力发电机的细节 希望电击使的电磁牵引可以使风扇逆向旋转 破坏矢量操作的风系技能 就像动漫里一样

**Comment by Paindar** [comment]
这种细节做了有什么用。。。。

**Comment by bilser** [comment]
感觉会非常有趣 套路什么的..

**Comment by Paindar** [comment]
嘛，我倒是不反对当成彩蛋了。。。。

**Comment by bilser** [comment]
所以 能考虑下添加这个细节吗。。。

**Comment by Paindar** [comment]
这个我说了不算，得由策划来考虑，我只负责bugfix。
