### ISSUE TITLE
I get this crash when trying to load up the game

### ISSUE THREAD

**Issue by comus777** [LambdaInnovation/AcademyCraft#571]
[crash-2017-03-09_21.34.23-client.txt](https://github.com/LambdaInnovation/AcademyCraft/files/830972/crash-2017-03-09_21.34.23-client.txt)

Crashlog says 1.0.4 but I've also had it happen on 1.0.5

**Comment by Paindar** [comment]
Failed to read crash-report.

Would you mind using [paste.ubuntu.com](url)?

**Comment by comus777** [comment]
http://paste.ubuntu.com/24161896/

I've also tested this on 1.0.6 and the crash still remains.

**Comment by Paindar** [comment]
You need LambdaLib 1.2.3.
