### ISSUE TITLE
Move back to Travis CI since mcbox.cc is dead

### ISSUE THREAD

**Issue by rogersachan** [LambdaInnovation/AcademyCraft#574]
I think the project should move back to Travis CI builds due to this.

**Comment by WeAthFoLD** [comment]
Agreed. There is some work to do to transit to Travis CI (Since we also have LambdaLib, there are some dependency issues), I will try it when I have some time.

**Comment by WeAthFoLD** [comment]
Cleaning up out-of-date issues. PS. we are considering setup CI before 1.1 release :-)
