### ISSUE TITLE
AC 1.0.6 Teleporter Issues

### ISSUE THREAD

**Issue by HaruDasom** [LambdaInnovation/AcademyCraft#579]
Forge : forge-1.7.10-10.13.4.1614-1.7.10
Version : AcademyCraft 1.0.6 (in Modpack Regrowth 1.0.2)

**1. Location Teleport sometimes fails**

I set a location in overworld, and used Location Teleport away from there.
It teleported me to selected location, but sometimes CP was consumed and nothing happened.
Is it a intended feature, or a bug?

**2. Cannot use Shift Teleport**

I tried to use Shift Teleport, but I could neither place a block nor deal damages; Only particle effects appeared. Tested with Cobblestones, Dirts, and Glasses.

**Comment by Paindar** [comment]
1.Bug, but I dont know why either.
2.May server disallows destroying block(in config).
