### ISSUE TITLE
Any estimated time for 1.10.2 update?

### ISSUE THREAD

**Issue by KamiSami** [LambdaInnovation/AcademyCraft#580]
This mod was pretty much one of top 3 mods, maybe even top 1 mod during 1.7.10 Minecraft, i am really hoping to see it to get updated if possible as every mod seems to be updated to that point. I feel like i can't let go of this mod but also i would have to let go of tons of mother mods aswell if i wanted to play with this... So is there any time estimation when next update may arrive? I am very curious, even if it is long time, i hope i would get an answer to sate my curiousity at least if the mod is even being worked on still..

**Comment by Renniuq** [comment]
#576 Has the most information currently available, they seem to be busy with other projects currently, so it will, at best, take a long time unfortunately.

**Comment by WeAthFoLD** [comment]
Closed as duplicates to #576
