### ISSUE TITLE
[1.0.4-1.0.6] Setting a skill's CP/Overload consume rate to under 1 will cause the ability to never trigger.

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#581]
This seems similar to the "teleporter ghost not going away" bugs, with the added effect of not actually triggering at all. I know that at low skill you can only use the ability while standing on the ground, so that's not the issue. When the ability is activated, it will render the arc roughly indicative of your projected trajectory, and that will expand to the full length (regardless of how long the ability key/button was pressed) and then won't go away until you either reload the world or hop dimensions - not sure if this is unique from the teleporter ghost or not. It will also not play the sound and won't use cp, nor generate overload, and you can stack multiple of the render.

This also makes it impossible to level the skill, so I suppose its good that VecManip doesn't have the skill tree setup to need certain skill percentages in previous skills.

**Comment by Renniuq** [comment]
Update: Upon further inspection, it appears flashing, storm wings, magnet movement, and jet engine all do similar things of simply not activating - all of which are mobility abilities, and therefore all of which I decided when adding the mod to the pack I'd try to make cheaper because I'm a mobility nut. I set cp_consume_speed and overload_speed to 0.5, and that was what rendered all of them non-functional.

This also still happened regardless of my having downgraded to 1.0.4 to try and fix it initially. I suppose that does mean the workaround is fairly simple, but I'll leave it here for whenever some of you get back and feel like patching something (probably) minor.

**Comment by Paindar** [comment]
Hello.
I think it's time to explain why skill effect would not exist disappear.

At first, a player uses a skill, then skill effect is spawned in his minecraft, but not server. Minecraft constructs a skill instance and sends a message that tells server that player uses a skill.

After server receives the message, it contructs a skill instance to execute other actions like damage, destroying blocks. At the same time, server sends messages to other players. While players' minecraft receive message, it will spawn skill effect.

After skill is finish, skill instance would be cleared in both client and server. If skill instance is cleared, any information about this using skill will be lost.

For some skills, server would tell client(player's minecraft) "it's time to clear effect" ; For others, effect would be cleared automatically in local(your minecraft).

"Teleport's Ghost" is that, Java throws a exception, interrupting clearing effect.
(When Mark Teleport's exp is more than about 0.92, its cooldown will be almost 0, which will cause exception)

In bad network quality or other stage, skill instance has benn cleared in client , but it may not  be constructed in server(like what you said).In this stage effect will show until you restart you minecraft.

**Comment by Renniuq** [comment]
I reset the exp consumption and it fixed the issues of them not triggering (though, if penetrate teleport was used while sneaking, it would not function and just leave a ghost that would be cleared when you used mark teleport, haven't checked if that is fixed in 1.0.6).

If I understand what you are saying, basically, the client tries to activate the ability, and does the client-side rendering in preperation, then the server finds the cp consumption invalid and the ability fails, and since it basically crashed, it doesn't tell the client to stop the render. Very enlightening.

**Comment by Paindar** [comment]
For Mark Teleport or other skills, the cooldown can be 0 sec. But **server disallow a skill whose cooldown is 0.** If so, it will interrupt the skill. The result of it is, as you said, it doesn't tell the client to stop the render.

In fact, this bug has been fixed in 4a3f92135497ed8b352339d7dbdac9199eadb67f , and a new release will fix many bugs including it. But, it seems that there is no longer a new release...

**Comment by Renniuq** [comment]
The whole sneaking-breaking-penetrate-teleport thing seems to be a thing with my mouse making shift-button 3 halfway do button 4 or something weird, but it happens based on the keybinds and doesn't seem to be a bug on your end.
