### ISSUE TITLE
[1.0.6]矢量操作技能导致伺服器卡顿

### ISSUE THREAD

**Issue by STGXAST** [LambdaInnovation/AcademyCraft#582]
在1.7.10伺服器中，如果两个矢量操作的能力者同时开矢量反射并且其中一个向对方发起攻击的时候，伺服器就会卡顿并且所有的玩家全部掉线，大约持续2-5分钟的卡顿，在此期间玩家不可进入伺服器，因为这种BUG不知道如何截图所以没有截图。

**Comment by Paindar** [comment]
那么大的计算量肯定会卡顿啊。。。这个大概是数据层面的事情了

总而言之 get 但是基本不可能有人修

**Comment by mintoazusa** [comment]
通过限制反射次数来减少计算？

**Comment by STGXAST** [comment]
我也在想能不能通过限制反射次数来减少计算量
