### ISSUE TITLE
[bug]能力会被重置

### ISSUE THREAD

**Issue by STGXAST** [LambdaInnovation/AcademyCraft#584]
在服务器中，如果玩家连接超时的时候，会过很长一段时间才掉线或者意识到自己连接超时，如果在这一段时间内被杀死没有重生，能力就会被重置，包括数据终端也会重置

**Comment by WeAthFoLD** [comment]
你好，由于我们目前没有1.7.10版本的更新计划，暂时先将这个issue关闭。如果在即将发布的1.1版本中仍然遇到同样问题，请开一个新的issue，感谢！
