### ISSUE TITLE
CoFH API outdated

### ISSUE THREAD

**Issue by Xaikii** [LambdaInnovation/AcademyCraft#585]
![2017-06-18_18 38 14](https://user-images.githubusercontent.com/25128633/27262371-654b085a-5455-11e7-90e4-42754801dbd5.png)

9/10 of my startups end up like these, I have to delete my whole logs folder that it works again, I've googled the problem already and asked around, it was said that the cause is that the API is outdated.
May you pls fix it? 
It's 100% that this issue is coming from AC since removing LambdaLib + AC is fixing this / it only happens with AC installed.

**Comment by DMSledge** [comment]
Can confirm. Work around is to go into the file for Academycraft and remove the cofh folder. This should work as long as another mod is supplying the correct api.
