### ISSUE TITLE
Server crash when throwing coin

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#59]
When throwing coin server will crash. It happened if you have an energy crystal with you.

**Comment by KSkun** [comment]
With log:

INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [AbstractNioByteChannel$NioByteUnsafe.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
15.03 00:57:02 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
15.03 00:57:02 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
15.03 00:57:02 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
15.03 00:57:02 [Server] INFO at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
15.03 00:57:02 [Server] INFO at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:310) [ef.class:?]
15.03 00:57:02 [Server] INFO at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:99) [ef.class:?]
15.03 00:57:02 [Server] INFO at net.minecraft.network.status.client.C00PacketServerQuery.func_148833_a(SourceFile:8) [jx.class:?]
15.03 00:57:02 [Server] INFO at net.minecraft.network.status.client.C00PacketServerQuery.func_148833_a(SourceFile:25) [jx.class:?]
15.03 00:57:02 [Server] INFO at net.minecraft.server.network.NetHandlerStatusServer.func_147312_a(NetHandlerStatusServer.java:70) [ng.class:?]

**Comment by acaly** [comment]
The log is incomplete. I can't even find the Exception.

**Comment by KSkun** [comment]
@acaly Well, I think we should have a try by ourselves.

**Comment by WeAthFoLD** [comment]
This shall be tested and reproduced by ourself. I didn't get any problem throwing a coin.
