### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by KamiSami** [LambdaInnovation/AcademyCraft#593]
Hello, I already have written question when update may come for this mod.. Now, i hate to sound desperate, but this is my favorite mod and everytime i play Minecraft, i always feel like i lack something... So i want to ask, would you please either continue updating this mod? If not, then... Can you guys hand over this mod to someone who is willing to continue the mod? Because if you guys are not going to do anything with this mod or not for very long time, i'd really suggest to let someone else work on it in that case. Or another option, work with your indie game and the mods, schedule your times for them. There's always options, but it's just if you guys are willing to do it. ...I'd hate to see this especially becoming abandoned.

Edit: If you plan to update it, i think 1.12 would be good. At least according what i have been hearing, it may be the new golden age of Minecraft mods. That is... If this mod will be back in developement...

**Comment by WeAthFoLD** [comment]
First of all I'm really glad that you enjoy AcademyCraft :-)

AcademyCraft's official development will be in a halt for still quite some time, for both team reason and my personal reason. As project lead and main programmer I am now near graduation as well as working as an intern in an indie game studio, so I hardly find time to maintain the mod. 

Also, thoughts of a **complete overhaul** came across my mind several times, as we now have capability to make much more fun ESPer or whatever Minecraft mods, and AC has potential to be substantially better. But, still, until I find some time to sit down and really do it.

Finally, to answer your question: AcademyCraft is completely open source, everything for the mod is out there and there's really NOTHING that stops anyone from maintaining their own version. I'd love to see someone carry the torch.

**Comment by KamiSami** [comment]
I really thank you for your time to answer.
