### ISSUE TITLE
Is this mod alive again?

### ISSUE THREAD

**Issue by KamiSami** [LambdaInnovation/AcademyCraft#598]
So i saw this in curse:

Last Released File     Mar 20, 2017

Is it finally happening? The mod is being continued on?

**Comment by Paindar** [comment]
It's about 2013 when Lambda Innovation started to create a new mod. And about 2015 D.C, AcademyCraft had its first released.
I mean, this is a very long process, 'cause all of us members have our works at real life. 
Now we are trying to update LambdaLib to Minecraft 1.12.2. It may be a long process, too. I don't know if it would still make sense when it completes. At least I still work on it now.
Thank you for supporting AcademyCraft.

**Comment by L1ttleFlyyy** [comment]
加油加油↖(^ω^)↗…等我明年转cs了第一个先学java…

**Comment by Philosyang** [comment]
That’s very nice of you guys to keep pushing the versions! Wish you have 0 errors and warnings in your next build. XD

**Comment by KamiSami** [comment]
I am very grateful for your work, thank you for this mod.

**Comment by Niconoko** [comment]
I would love to play this in the newer version, keep it up. :3

**Comment by Paindar** [comment]
Now we returned.

**Comment by Niconoko** [comment]
HYPE~!
