### ISSUE TITLE
when I open a GUI the game crashes

### ISSUE THREAD

**Issue by herobrine060606** [LambdaInnovation/AcademyCraft#599]
whenever I try to open any GUI from this mod my game crashes such as when I open the "portable ability developer,  advanced ability developer, and the Miska terminal". my second issue is the first time I mined ore from this mod and picked it up the mod tried to give me an achievement of sorts and my game crashed

**Comment by Philosyang** [comment]
Is there a crash report?
Paste it so that the dev can help you solve it quicker.

**Comment by herobrine060606** [comment]
I think so let me look

**Comment by herobrine060606** [comment]
https://pastebin.com/s2GYjbc0

**Comment by herobrine060606** [comment]
I don't think the log shows the info about it crashing through

**Comment by Philosyang** [comment]
Hmmm... you're right...
Let's wait for the dev...

**Comment by herobrine060606** [comment]
ok

**Comment by LemADEC** [comment]
looks like a Java crash, check for hs_err files in your modpack folder and upload them

**Comment by herobrine060606** [comment]
here is the hs_err i chose the file with the highest number there are 22 of them this ones name was hs_err_pid4448 heres the paste bin https://pastebin.com/WzMkR4wE

**Comment by LemADEC** [comment]
Looks like the mod is doing low lever graphics without proper context check. Updating your GPU HW or SW may help until the mod is fixed.

**Comment by Paindar** [comment]
Outdated issue, closed.
