### ISSUE TITLE
一些建议和提交bug

### ISSUE THREAD

**Issue by huajimi** [LambdaInnovation/AcademyCraft#600]
希望能加一个技能禁止的世界的黑、白名单，或者对某职业的黑白名单对服务器更友好，也可以更方便的解决一些事情，
另外能源桥储存工业的电量，会导致能源囤积住、不传输并且该方块位置无法再用能源桥传输能源
这还会产生一些服务器报错

模组很久没有更新了，也不知道进度是否弃坑，发布者很久没有去过中文论坛了

**Comment by Paindar** [comment]
outdate issue, close.
