### ISSUE TITLE
[1.0.6] Crash at startup

### ISSUE THREAD

**Issue by NikkyAI** [LambdaInnovation/AcademyCraft#604]
https://pastebin.com/Ez2yYMc1

using `forge-1.7.10-10.13.4.1614-1.7.10`

it loads fine when i remove academycraft from the mods

i will try to compile from source later

**Comment by NikkyAI** [comment]
and using multimc, 1.7.10, latest forge and JUST academycraft https://paste.ee/p/3YdNh

**Comment by Windowslen** [comment]
Hello, My name is Kazanami. Nice to meet you.
First apologize. I am Japanese and I do not understand English very much.
Therefore, I write sentences using Google Translate.


I am also introducing AcademyCraft and playing it, but there was not a problem like crashing particularly.

As a result of checking the error log, it seems that there is a possibility that [LambdaLib], which is a premise mod of AcademyCraft, is applied.

I do not know much details, but I am very happy if this is helpful.

**Comment by NikkyAI** [comment]
it seems to indeed be missing this..
why though is it not marked as required library?
