### ISSUE TITLE
关于快吧我的世界盒子上服务器将AC商用

### ISSUE THREAD

**Issue by AcientSpectator** [LambdaInnovation/AcademyCraft#605]
## 发现快吧平台分发AC本体，另其平台服务器将AC用于盈利行为
![image](https://user-images.githubusercontent.com/33504909/36781399-bae9c6b0-1cb0-11e8-97db-8c7a70544847.png)
![image](https://user-images.githubusercontent.com/33504909/36781487-f5fe351a-1cb0-11e8-9a20-5870269b1d98.png)
在快吧盒子中出现了AC，介绍信息中声称“数据来自网友共享”，请问其是否经过授权？

![image](https://user-images.githubusercontent.com/33504909/36781258-5e3450b6-1cb0-11e8-925d-0e6777fb9efc.png)
![image](https://user-images.githubusercontent.com/33504909/36781599-47594328-1cb1-11e8-9413-695756297589.png)
![image](https://user-images.githubusercontent.com/33504909/36781611-52f9ef2a-1cb1-11e8-8128-194b2e10a754.png)
另外在其平台上的官方服务器“秋之次元”，安装AC的同时通过服务器运营接受点券充值，将mod商用盈利

快吧盒子官网：http://mc.kuai8.com/

**Comment by WeAthFoLD** [comment]
感谢你的提醒。目前快吧官方网站已关闭，若未来出现类似情况我们将积极考虑维权。
