### ISSUE TITLE
[Issue] Jet Engine destination marker sticks

### ISSUE THREAD

**Issue by DarianLStephens** [LambdaInnovation/AcademyCraft#609]
Similar to the old Penetrate Teleport issue which was fixed in 1.0.7, sometimes the destination marker for Jet Engine will stay at your crosshair and stack up with itself until you reload.
It may happen more often if you're travelling to new chunks with it or rapidly pressing the button, but once it starts, every new usage of Jet Engine will create another marker.

**Comment by Paindar** [comment]
We have noticed this problem, but after discussion we came to the conclusion that we need a better framework.
In other words, we are not going to deal with it immediately, but we will definitely deal with it in the next version in 1.12.2.
Anyway, thank you for feedback.
