### ISSUE TITLE
Are you considering migrating AC to Update Aquatic (Version 1.13)?

### ISSUE THREAD

**Issue by L1ttleFlyyy** [LambdaInnovation/AcademyCraft#610]
According to MC official site, **Update Aquatic** will be released on July 18th, and we all believe this should be the best update since MC was created. However, AC is also a fantastic mod which I can't play without. They both have best features I like, so it's really a dilemma if I have to abandon one between MC 1.13 with Update Aquatic and MC 1.12.2 with AC.
I do know code refraction is not simple and the APIs might change in different versions. I just speak out my wish and I appreciate your decision. Many thanks for your offering the best mod _Academy Craft_ to us. @Paindar

**Comment by Paindar** [comment]
Every new version is the best version, you know.

**Comment by nirvanaxiao6** [comment]
As @Paindar  said,every new version is said to be the best version.But there is a question:why the most popular version in 1.7 is not 1.7.1 but 1.7.10?New version should be improved to make it stable,and it needs time.The mod may upgrade to 1.13 when there is a stable version for 1.13 and lots of modders agree to upgrade.

**Comment by WeAthFoLD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/DCajTTKr/15-test)
