### ISSUE TITLE
Bug with Mark Teleport

### ISSUE THREAD

**Issue by Marvinjvc** [LambdaInnovation/AcademyCraft#611]
Hi !!

First of all, I'm sorry for my bad english. I'm French ;w;

Next, I am, in my server, Teleporter and I have some problems with the Mark Teleport.
When you use the Mark Teleport, you can see a sort of blue spectrum which shows the place where you are going to be teleported. However, when I use my capacity, this blue spectrum is visible everywhere ... without the activation of the capacity !

It is the same problem of here:
https://github.com/LambdaInnovation/AcademyCraft/issues/544

However, the developper said that this bug was fixed but ... I have always this bug, which is quite frustrating.

I am on 1.0.6 for Academy Craft and 1.2.3 for Lambda Core.

Please help me ;w; Because I now need to use the Penetrate Teleport (so, sometimes, I die like a dumb in the walls ...).

Thanks a lot for your help !

**Comment by Paindar** [comment]
Maybe you can try AcademyCraft 1.0.7, we have solved it in this version.

**Comment by Marvinjvc** [comment]
Thanks a lot !! It works in this version :D
Problem resolved o/
