### ISSUE TITLE
1.0.7版本拉拉杆会蹦服

### ISSUE THREAD

**Issue by viphdf** [LambdaInnovation/AcademyCraft#612]
以下的蹦服内容,服务端版本1.7.10Um端 装有拔刀剑MOD NpcMOD 和一个翅膀MOD
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 18-7-24 下午9:39
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: cn/academy/ability/block/AbilityInterferer
	at cn.paindar.academymonster.core.support.tile.AbilityInterfManager.onBlockPlaced(AbilityInterfManager.java:43)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_377_AbilityInterfManager_onBlockPlaced_PlaceEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69)
	at cc.uraniummc.capture.type.CaptureBlock.fireBlockPlace(CaptureBlock.java:131)
	at net.minecraft.world.World.func_72921_c(World.java:909)
	at net.minecraft.block.BlockLever.func_149727_a(BlockLever.java:288)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:472)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:771)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: cn.academy.ability.block.AbilityInterferer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: cc.uraniummc:Uranium:1710-stable-4-B15 UNOFFICIAL DON'T REPORT THIS CRASH
	Plugins: SlashFortifier, ItemDurability, GroupManager, SpecialAttributes, ProtectWG, NBTConfig, ConsoleScheduler, LoginMessage, NeverLag, FreeSwitchTitle, tpLogin, Lockette, BetterLottery2, PvPToggle, DeluxeTags, ItemTime, BanItem, AT, Pcj, Soulbound, CoreProtect, Portable_Warehouse, WorldEdit, ColorChat, Essentials, ClearLag, AutoMessage, BaoShiPlus, SlashFixer, WorldBorder, ProtocolLib, NoCheatPlus, HappyLine, AntiDrop, SweepAttack, disintegrate, NOUnlimitedPickup, EssentialsChat, LevelChat, SQLibrary, FunnyFoot, GlobalShop, RandomTp, qiandao, XBox, Vault, Lores, TimeGivesYouMoney, WTP, QuickShop, VipZero, PlayerPoints, WorldGuard, ItemLoreStats, ChestCommands, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, PlotMe, RPG_Items, Residence, CrazyAuctions, UltimateGuild, SimpleLib, PlotMe-DefaultGenerator, QuickSee, SimpleMenu, ResBuild, Multiverse-Core, InfoBoardReborn, SimpleOnlineTime, HolographicDisplays, AreaShop
	Disabled Plugins: 
	Operating System: Windows Server 2008 R2 (amd64) version 6.1
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1034939456 bytes (986 MB) / 1461714944 bytes (1394 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xmx2G -XX:+AggressiveOpts
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 6, allocated: 28, tallocated: 86
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (Uranium-1710-stable-4-B15-server.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (Uranium-1710-stable-4-B15-server.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	UraniumPlus{${UMP_VER}} [Added title and actionbar support for client and server] (Uranium-1710-stable-4-B15-server.jar) 
	UCHIJAAAA	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] ([必须]CustomNPCs_d.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] (SlashBlade-mc1.7.10-r87.jar) 
	UCHIJAAAA	flammpfeil.nihil{mc1.7.x-r8} [Nihil] ([拔刀附属-似蛭]Nihil-mc1.7.x-r8.jar) 
	UCHIJAAAA	flammpfeil.frostwolf{mc1.7.2-r1} [FrostWolf] ([拔刀附属-冰狼之刃]SlashBladeFrostWolf-mc1.7.2-r1.1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.blademaster{mc1.7.2-r1} [BladeMaster] ([拔刀附属-剑圣之刃]Blademaster.jar) 
	UCHIJAAAA	flammpfeil.slashblade.laemmle{mc1.7.10-r1} [Slashblade-Laemmle] ([拔刀附属-幻魔炼金拵]Laemmle.jar) 
	UCHIJAAAA	flammpfeil.darkraven{mc1.7.2-r1} [DarkRaven] ([拔刀附属-暗鸦]DarkRaven.jar) 
	UCHIJAAAA	flammpfeil.slashblade.kamuy{mc1.7.10-r6} [Kamuy] ([拔刀附属-神剑]Kamuy.jar) 
	UCHIJAAAA	slashblade.yukari{mc1.7.10-r2} [Slashblade-yukari] ([拔刀附属-结月刀改]Slashblade-yukari-mc1.7.10-r2.jar) 
	UCHIJAAAA	flammpfeil.fluorescentbar{mc1.7.2-r3} [fluorescentbar] ([拔刀附属-荧光]fluorescentbar.jar) 
	UCHIJAAAA	flammpfeil.slashblade.anvilenchant{mc1.7.10-r1} [Slashblade-AnvilEnchant] ([拔刀附属-铁砧附魔]Slashblade-AnvilEnchant-mc1.7.10-r1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.wanderer{mc1.7.2-r1} [SlashBladeWanderer] ([拔刀附属-风来剑]Wanderer-mc1.7.2-r1.jar) 
	UCHIJAAAA	LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) 
	UCHIJAAAA	academy-craft{1.0.7} [Academy Craft] (AcademyCraft-1.0.7.jar) 
	UCHIJAAAA	academymonster{1.0.3a} [Academy Monster] (AcademyMonster-1.0.3a.jar) 
	UCHIJAAAA	balumg{1.0.0} [balumg] (Balmung+1.7.10-r1.0-1.jar) 
	UCHIJAAAA	BladeAnti{r1} [BladeAnti] (BladeAnti-r1.jar) 
	UCHIJAAAA	custommc{1.0v} [custommc] (custommc.jar) 
	UCHIJAAAA	Pseudo{1.0.0} [Pseudo] (DSlashBlade-PseudoEdge-mc1.7.10-r11.jar) 
	UCHIJAAAA	Yamazakura{1.0.0} [Yamazakura] (DSlashBlade-Yamazakura-mc1.7-r4.jar) 
	UCHIJAAAA	foxex{1.1.2} [FoxBlade Extra] (FoxExtrav1.1.2(MC1710).jar) 
	UCHIJAAAA	heartwork{2.1.0} [The Heartwork] (Heartwork_2.1.1_MC1.7.10.jar) 
	UCHIJAAAA	flammpfeil.kevinwalker{mc1.7.10} [kevinwalker] (huancaizhiren0.3v.jar) 
	UCHIJAAAA	cheatingessentials{9.999} [Cheating Essentials] (pixelmon.jar) 
	UCHIJAAAA	1.7.10{9.96.9} [Gameshark (Pixelmon)] (pixelmon.jar) 
	UCHIJAAAA	ThaiPixmon3D{1.0} [ThaiPixmon3D] (pixelmon.jar) 
	UCHIJAAAA	ThaiPixBlock3D{1.0.0} [ThaiPixBlock3D] (pixelmon.jar) 
	UCHIJAAAA	Thai-Pixmon2{Thai-Pix2} [Thai-Pixmon2] (pixelmon.jar) 
	UCHIJAAAA	ThaiPix-sword{ThaiPixsword} [ThaiPix-sword] (pixelmon.jar) 
	UCHIJAAAA	ThaiPix3d{1.0} [ThaiPix3d] (pixelmon.jar) 
	UCHIJAAAA	gameshark{99.0.0} [Gameshark (Pixelmon)] (pixelmon.jar) 
	UCHIJAAAA	Wingmod{thaiPixWing_1.7.10} [thaiPixwing] (pixelmon.jar) 
	UCHIJAAAA	examplemod{1.0} [Example Mod] (pixelmon.jar) 
	UCHIJAAAA	saligia{1.0.0} [PROJECT_SALIGIA] (PROJECT_saligia_2.1.0.jar) 
	UCHIJAAAA	ND{r2} [ND] (SlashBlade-buzhengjingdejian-r2.jar) 
	UCHIJAAAA	flammpfeil.slashblade.exsa{mc1.7.10-r6} [SlashBlade-ExSa] (SlashBlade-ExSa-r6.jar) 
	UCHIJAAAA	allweapon{1.0} [allweapon] (wanwujiekeren-r1.jar) 
	UCHIJAAAA	negorerouse{1.0.0} [NegoreRouse] (SlashBlade-NegoreRouse-r3vR.jar) 
	UCHIJAAAA	flammpfeil.slashblade.zxsa{mc1.7.10-r5} [ZxSa] (SlashBlade-ZxSa-r6vB+-OfficialEdition-.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 50; [EntityPlayerMP['hdf'/258, l='fb1', x=-32.44, y=30.00, z=68.30](hdf at -32.43906213096792,30.0,68.30000001192093)]
	Is Modded: Definitely; Server brand changed to 'uranium,kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Paindar** [comment]
删除AcademyMonster。
