### ISSUE TITLE
Crash when learning ability

### ISSUE THREAD

**Issue by Zsashas** [LambdaInnovation/AcademyCraft#613]
Right when it reached 100%, just before assigning my ability, it crashed.

https://hastebin.com/ubegoyaged.md

**Comment by Paindar** [comment]
Will it happen twice?

**Comment by Zsashas** [comment]
Loaded up the game again, everything was fine. Haven't tried resetting my ability yet.

**Comment by WeAthFoLD** [comment]
Please file another issue if you experience it again in the upcoming 1.1 release.
