### ISSUE TITLE
1.0.7版本AcademyCraft在1.7.10版本中的一个bug

### ISSUE THREAD

**Issue by shangfang21** [LambdaInnovation/AcademyCraft#619]
游戏过程中，当我使用 旅行地图mod（journeymap-1.7.10-5.1.4p2-unlimited），使用导航点传送回到家里时，游戏出现了一些未知的问题，导致游戏退出，并提示出现了一些未知的错误。
  经过几次粗略的检查加上日志报告，我发现应该是AcademyCraft的某个bug导致的。
  通过几次测试，我发现，当打开AcademyCraft的超能力时，跨区块传送会导致退出世界（只是游戏内退出，客户端并没有崩溃）。
  具体信息还请在附加的日志报告上查阅，谢谢您的检查。
  如果有任何新的回复，请尽可能先联系2467458619@qq.com，麻烦了！
[1.txt](https://github.com/LambdaInnovation/AcademyCraft/files/2297217/1.txt)

**Comment by WeAthFoLD** [comment]
你好，由于我们目前没有1.7.10版本的更新计划，暂时先将这个issue关闭。如果在即将发布的1.1版本中仍然遇到同样问题，请开一个新的issue，感谢！
