### ISSUE TITLE
可以通过作弊跨能力系绕能力干涉方块放技能.......

### ISSUE THREAD

**Issue by jht3QAQ** [LambdaInnovation/AcademyCraft#622]
以电气使磁弧触发为例..
`Minecraft mc = Minecraft.getMinecraft();
ArcGenContext context=new ArcGenContext(mc.thePlayer);
ContextManager.instance.activate(context); 
context.sendToServer("perform");`
嗯 就能在服务器里跨能力系绕干涉方块放了
(不过好像服务器会刷错Error during network message Caused by: java.lang.IllegalStateException: Skill electromaster.arc_gen not in category #4.  ??)
(所以说我为什么会关注这个,,,,)
(AcademyCraft-1.0.4,LambdaLib-1.2.3)
(1076168468@qq.com)

**Comment by WeAthFoLD** [comment]
AC本身是开源的，想要做到很完善的反作弊在这种情况下是极其困难的，因此我们基本不会考虑正常使用以外的情况，sorry :D
如果是在开服务器的过程中确有人通过这样的行为作弊，欢迎通过fork代码的形式定制或者通过提交pull request来修复相关代码，不过我们目前在专注于1.12的更新，可能不会有1710的发布计划了。
