### ISSUE TITLE
A Few Bugs about the Ender Dragon

### ISSUE THREAD

**Issue by maxjkwang** [LambdaInnovation/AcademyCraft#623]
AC 1.0.7
MC 1.7.10
If you try to target the Ender Dragon with flesh_ripping, it deals its damage but causes the game to crash. What's more it shows the 'Multiplayer' Section and comes with 'Connection Lost A fatal error has occurred, this connection is terminated'
Furthermore when you target it with shift_teleport, it deals damage multiple times. I don't know if it's a feature or calculation error, so anyway I reported it.

**Comment by Paindar** [comment]
Similar question with #549, closed.
