### ISSUE TITLE
Couple questions!

### ISSUE THREAD

**Issue by KamiSami** [LambdaInnovation/AcademyCraft#625]
Okay! So im sorry in advance as this might not be appropriate place to ask questions, but i am not sure where else i might get answers to these.. First question, will 1.12 version of this mod when it will be released work also in 1.12.2? -Removed second question since it was already answered by your guys site- Okay, third question, what would be new category (like vector manipulator and such) IF there will be new one? Those are questions i have been thinking of asking so far, feel free to close this with an answer, i will bookmark this to my browser and look it up eventually again. I am eagerly looking forward for the update! ^^ Good luck on getting first page in curseforge, i believe in you guys!

**Comment by Paindar** [comment]
First question, our answer is yes.
Third question, it's easy to have a idea about new category, but it's hard to have unique skills which can be achieved. So it may be had, but it will be a long process.

**Comment by KamiSami** [comment]
Awesome! Can't wait to get to play with the mod again! :D Thanks for reply
