### ISSUE TITLE
这个项目复活我很激动，有几个想法

### ISSUE THREAD

**Issue by wuyuzegang** [LambdaInnovation/AcademyCraft#626]
能不能像神秘时代mod那样有自己的地形（腐烂之地和魔法森林）和怪物。
比如增加城市地形（生成一大堆实体高楼和马路），增加怪物（比如高达什么的，毕竟超能力很强，没怪打就很难受）。

**Comment by Paindar** [comment]
面包会有的,牛奶会有的,一切都会有的（跑

**Comment by 3TUSK** [comment]
城市地形的话，其实有现成的Mod的——Lost Cities
