### ISSUE TITLE
在服务器破坏虚能融合机时的错误

### ISSUE THREAD

**Issue by stanly122729266** [LambdaInnovation/AcademyCraft#629]
服务端版本：Thermos-1.7.10
描述：玩家在服务器中破坏虚能融合机时会报错：a fatal error has occured, this connection is terminated
玩家会掉出服务器，但客户端和服务器都不会崩溃，服务器后台和客户端日志也没有任何信息

**Comment by WeAthFoLD** [comment]
感谢你提交的问题，但是很抱歉我们目前正在全力推进1.12版本的更新，所以1.7.10版本的问题目前都统一不做处理。如果在接下来会发布的1.1版本中仍然出现该问题，请再打开一个新的issue >3
