### ISSUE TITLE
[Bug] Magnet Manipulation drops items through the world

### ISSUE THREAD

**Issue by Darkveld** [LambdaInnovation/AcademyCraft#634]
When using Magnet Manipulation, the item you are grabbing and moving through the world very often just falls and gets deleted, I remember this being a problem from the previous version but its vastly more common now.

**Comment by nirvanaxiao6** [comment]
The bug that was mentioned here is fixed.

**Comment by nirvanaxiao6** [comment]
Wrong reopen, sorry
