### ISSUE TITLE
[Bug] Some skills doesn't have CD after usage (with low chance)

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#637]
**Describe the bug**
部分攻击技能在命中实体后概率性无CD

**To Reproduce**
1. Use Arc Generation or Lightning on a Creeper
2. Observe that sometimes skill doesn't get a CD

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
1.1rev3 QA

**Comment by Paindar** [comment]
Fixed.

**Comment by nirvanaxiao6** [comment]
这玩意..测不了啊
就当修好了吧
