### ISSUE TITLE
[Bug] Electron Missile will target dead entities

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#639]
**Describe the bug**
Electron Missile will target entities, even if they're dead.

**To Reproduce**
1. Use Electron Missle
2. Observe that it will attack entities even if they are dead.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
1.1.0beta1

**Additional context**

**Comment by Paindar** [comment]
Don't fix, feature.
