### ISSUE TITLE
[Bug] Rendering error when activating abilities w/ ShadersMod or Optifine installed

### ISSUE THREAD

**Issue by Shizuri23** [LambdaInnovation/AcademyCraft#647]
![qq 20181223155223](https://user-images.githubusercontent.com/46082179/50381796-c3398d00-06ca-11e9-8240-248a25c2f613.png)
![qq 20181223155306](https://user-images.githubusercontent.com/46082179/50381801-e401e280-06ca-11e9-97f5-c644ce41bbf6.png)
![qq 20181223155311](https://user-images.githubusercontent.com/46082179/50381802-e401e280-06ca-11e9-8bb6-330d935d0a26.png)
![qq 20181223155321](https://user-images.githubusercontent.com/46082179/50381803-e49a7900-06ca-11e9-88f7-8cd32953e917.png)
开能力前正常，一开启能力后渲染错误，需要重新选择光影文件才能恢复原样
其他的光影也是一样

 - OS: [e.g. Windows]
 - MC Version and Forge version: [e.g. 14.23.5.2796-1.12.2]
 - Version [e.g. 1.1.0beta1]
-  OptiFine HD E3 Ultra

**Comment by nirvanaxiao6** [comment]
Fixed :1.1.0_beta2-0ae447
