### ISSUE TITLE
[Bug] Touching creatures with reflection will have special effects

### ISSUE THREAD

**Issue by Shizuri23** [LambdaInnovation/AcademyCraft#648]
![qq 20181223161032](https://user-images.githubusercontent.com/46082179/50381895-5378d180-06cd-11e9-8c0b-d7bca846d5d6.png)
Such as chicken

 - OS: [Windows]
 - MC Version and Forge version: [14.23.5.2796-1.12.2]
 - Version [1.1.0beta1]

**Comment by Paindar** [comment]
Fixed.
