### ISSUE TITLE
[Bug] No files in the music player

### ISSUE THREAD

**Issue by Shizuri23** [LambdaInnovation/AcademyCraft#649]
![qq 20181223163022](https://user-images.githubusercontent.com/46082179/50382009-224dd080-06d0-11e9-85f1-31050f8bbc5f.png)
![qq 20181223163036](https://user-images.githubusercontent.com/46082179/50382010-22e66700-06d0-11e9-9922-5cd59c107028.png)

**Comment by Paindar** [comment]
Fixed.
