### ISSUE TITLE
[Bug] plasma_cannon disappear

### ISSUE THREAD

**Issue by Shizuri23** [LambdaInnovation/AcademyCraft#650]
The use of skill in the flight of the projectile causes overload and the projectile will disappear.
![qq 20181223172306](https://user-images.githubusercontent.com/46082179/50382317-84f69a80-06d7-11e9-909d-b11ccbdb4cb0.png)
![qq 20181223172344](https://user-images.githubusercontent.com/46082179/50382318-84f69a80-06d7-11e9-9293-2bd666ea5e97.png)
(Terrain destruction has been turned on)

**Comment by Paindar** [comment]
This is not bug. This skill will be invalid if it is aborted, whatever any stage(Ready or flying).
However, we will discuss this problem, because it looks really weird.
