### ISSUE TITLE
[Bug] wireless GUI Size

### ISSUE THREAD

**Issue by LISARIAT** [LambdaInnovation/AcademyCraft#655]
**Describe the bug**

**To Reproduce**
1. Go to e.g: Advanced Wireless Imag Node
2. Get Not Enough Items
3. GUI Scale normal (1900x1080)

**Screenshots**
http://www.noelshack.com/2018-52-1-1545671221-2018-12-24-18-01-10.png

**Comment by Paindar** [comment]
fixed.
