### ISSUE TITLE
[Bug] 磁力钩位置错了，其他UI隐藏时仍然能点到按钮的BUG等等

### ISSUE THREAD

**Issue by TakanashiYune** [LambdaInnovation/AcademyCraft#663]
、**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - MC Version and Forge version: [e.g. 14.23.4.2768-1.12.2]
 - Version [e.g. 1.1.0beta1]

**Additional context**
![default](https://user-images.githubusercontent.com/46100781/50507150-89e49100-0abf-11e9-972a-a06274526b62.gif)
略高精度的模型加载慢也许是MC自身的问题
![ui](https://user-images.githubusercontent.com/46100781/50507172-a41e6f00-0abf-11e9-94b6-ea6caf3416c1.gif)
这里在连接界面会隐藏掉其他UI，但是仍然能够点击到相关按钮
![1](https://user-images.githubusercontent.com/46100781/50507190-bf897a00-0abf-11e9-8e32-aca7a0dbf13a.png)
副手磁力钩位置错误，第三人称也偏了同时磁力钩也无法触发电击使的电磁牵引

**Comment by nirvanaxiao6** [comment]
实际上这是多个问题 最好能开多个issue 这样分锅和QA验收的时候都方便一些
开新issue时利用reference就好啦

**Comment by nirvanaxiao6** [comment]
UI问题无法复现，其他已经单开issue
