### ISSUE TITLE
[Bug] Resetting ability can be done in normal developer.

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#664]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - MC Version and Forge version: [e.g. 14.23.4.2705-1.12.2]
 - Version [e.g. 1.1.0beta1]

**Additional context**

**Comment by Paindar** [comment]
无法复现
