### ISSUE TITLE
[Bug] 矿物探测渲染位置偏移

### ISSUE THREAD

**Issue by Kurohoshi-aiba** [LambdaInnovation/AcademyCraft#666]
**Describe the bug**
渲染位置偏移矿物

**Screenshots**
![default](https://user-images.githubusercontent.com/46209911/50527689-e29a4500-0b24-11e9-9fc3-d2db6da52871.png)

**Desktop (please complete the following information):**
 - OS: [windows7]
 - MC Version and Forge version: [14.23.5.2768-1.12.2]
 - Version [1.1.0beta1]

**Comment by nirvanaxiao6** [comment]
Not fixed: AcademyCraft-analysis-1.1.0_beta2-78d8c9
