### ISSUE TITLE
[Bug] 采集光束起始点不跟随

### ISSUE THREAD

**Issue by Kurohoshi-aiba** [LambdaInnovation/AcademyCraft#668]
**Describe the bug**
固定在一个位置,当人物旋转到一定角度后,可实现胯下射出

**Screenshots**
![default](https://user-images.githubusercontent.com/46209911/50533754-f917bf00-0b6b-11e9-944b-bff92b9ead33.gif)

**Desktop (please complete the following information):**
 - OS: [Windows7]
 - MC Version and Forge version: [14.23.5.2768-1.12.2]
 - Version [1.1.0beta1]

**Comment by nirvanaxiao6** [comment]
![2019-01-19_11 09 35](https://user-images.githubusercontent.com/13258510/51421568-cac15880-1bda-11e9-81a7-e218adc4903f.png)
胯下输出也许就是这样的

Not fixed: AcademyCraft-analysis-1.1.0_beta2-78d8c9.
