### ISSUE TITLE
[Bug]Some bugs associated with Magnet Manipulate

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#671]
**Describe the bug**
BUG 1: After releasing the skill to sent the block, the block will drop visibly and then flash to the destination. It happens by chance, but very frequently.

BUG 2: The block will reach wrong destination. It will have about 3-4 blocks of deviation compared with the place you want the block to stay.

BUG 3: Sometimes the block wont stay at the block it reaches, but somewhere behind the blocks. The phenomenon is suspected to have the ability to supplant blocks.

BUG 4: The skill cannot hurt enemies sometimes. Only enemies standing near the place where the block stay finally can be hurt, and sometimes no one will be hurt. Anyway, you cannot hurt the enemies on the track of the block.

And when in low experience, the block will disappear sometimes. I'm not sure whether it's a bug.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - MC Version and Forge version: [e.g. 14.23.4.2705-1.12.2]
 - Version [e.g. 1.1.0beta1]

**Additional context**

**Comment by WeAthFoLD** [comment]
BUG1已修复，改进了实体的同步时序。
BUG4在现在实体速度同步更一致的情况下已经好多了，但在MC的网络环境下很难进一步理想化。
