### ISSUE TITLE
[Bug] Machines with multiply blocks should be loaded for about 1 second.

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#672]
**Describe the bug**
Like **Normal Developer**, **Advanced Developer**, **Matrix**, **Pillar** and **Wind Generator**
Also, **Solar Generator** has the problem, too.

The gif can be seen in #663 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - MC Version and Forge version: [e.g. 14.23.4.2705-1.12.2]
 - Version [e.g. 1.1.0beta1]

**Additional context**

**Comment by WeAthFoLD** [comment]
Fixed.
