### ISSUE TITLE
[Bug] 电气使的超电磁炮细节显示

### ISSUE THREAD

**Issue by Violet-Molder** [LambdaInnovation/AcademyCraft#674]
我记得旧版的超电磁炮在可以发射的时候右手的地方会有一个电圈的特效，现在没有了。哇没有参照物了，我得重新学习放电磁炮了（555
希望能重新加入awa
不知道是不是bug..

**Comment by WeAthFoLD** [comment]
是bug，感谢汇报我们会修复的~
