### ISSUE TITLE
[Bug]Server 定向冲力击杀怪物 

### ISSUE THREAD

**Issue by Kurohoshi-aiba** [LambdaInnovation/AcademyCraft#675]
**Describe the bug**
击杀实体时,不是对实体造成伤害.技能就像是没放出去一样,CD没有,手也抬着

**Desktop (please complete the following information):**
 - OS: [Windows7]
 - Server Version and Forge version: [Spongeforge-1.12.2-2705-7.1.0-beta-3361]
 - Version [1.1.0beta2]
[定向冲力报错.txt](https://github.com/LambdaInnovation/AcademyCraft/files/2718360/default.txt)

**Comment by Paindar** [comment]
无法复现，close.
