### ISSUE TITLE
[Bug] Bugs about Imag Phase Liquid.

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#676]
**Describe the bug**
There are two bugs here:
1. According to the official wiki, Imag Phase Liquid has the ability to "erode" water, or in other words, it will supplant water when toughing it. But now it doesn't.
2. When Imag Phase Liquid is placed together with a water source, they can create an infinite water.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - MC Version and Forge version: [e.g. 14.23.4.2705-1.12.2]
 - Version [e.g. 1.1.0beta1]

**Additional context**

**Comment by Paindar** [comment]
侵蚀不意味着替换，就我个人看来是这样。即使要严格按照设定，也会发生互溶，但是显然是不存在“不纯的虚相液"这种操作的。因此最合理的改动大概是将虚相液替换成水，但是大概会被玩家打死。
另外，虚相液源和水源会产生新的水源这点应该是毫无问题的，理论上。
因此，关于该issue的具体处置方案还应该在组内进行讨论才是，个人建议关闭此issue。
