### ISSUE TITLE
[Bug] 关于官服加forge形式服务器无法打开虚能节点UI面板

### ISSUE THREAD

**Issue by Amaomy** [LambdaInnovation/AcademyCraft#677]
**Describe the bug**
在服务器中安装mod后，对虚能节点进行右键会导致道具栏中的道具随机的移动到四个装备栏和人物自带的四格合成栏中，并且无法打开虚能节点的ui面板，但在客户端本地存档中不会出现这个问题。
**To Reproduce**

**Expected behavior**

**Screenshots**
![qq 20190102110436](https://user-images.githubusercontent.com/46307536/50579238-4ce11b80-0e7e-11e9-9f09-d8182228c3a3.png)
![qq 20190102110500](https://user-images.githubusercontent.com/46307536/50579239-4ce11b80-0e7e-11e9-97e3-1c7378030bd9.png)
以上两张图分别是羊毛与能力开发机背移动到头部装备位置的截图

**Desktop (please complete the following information):**
MC服务器版本1.12.1
服务器forge版本14.23.5.2768

**Additional context**

**Comment by nirvanaxiao6** [comment]
所附加的屏幕截图和问题不符，并且截图里那个问题是已经发现的问题。

另外，请在1.12.2服务器版本中确认是否存在该问题，AC是基于MC1.12.2的

**Comment by Paindar** [comment]
无后续反馈，关闭此issue。
