### ISSUE TITLE
[Feature] Analytics system

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#678]
* [x] 需要从 KeyDelegate 而非 AbilityContext 发送技能事件

**Comment by voidcl** [comment]
目前发送技能事件的位置从abilityContext的构造函数中移动至下方的setCoolDown()函数中，测试下来是技能进入冷却后在server上发送了一次事件，个人觉得这样做跟在KeyDelegate那边用按钮发送事件可能差不多？狼觉得可以的话这个issue可以关掉了，也不用在那边进行修改

**Comment by WeAthFoLD** [comment]
> 
> 
> 目前发送技能事件的位置从abilityContext的构造函数中移动至下方的setCoolDown()函数中，测试下来是技能进入冷却后在server上发送了一次事件，个人觉得这样做跟在KeyDelegate那边用按钮发送事件可能差不多？狼觉得可以的话这个issue可以关掉了，也不用在那边进行修改

问题是有的技能没有冷却

**Comment by voidcl** [comment]
狼今天提到的那个位置加事件发送不大行，对无cd的技能确实是可以发送出来，但是对技能按住然后V取消也会发送一次事件，不投掷硬币同时快速点击技能释放会按点击速度发送事件，如果要不精准的统计那确实那个位置就可以了，如果要精准的统计要么就要换个位置，要么就需要给那些没有cd的技能+一个1tick的cd之类的

**Comment by WeAthFoLD** [comment]
我觉得是可以的，这样做是计技能被触发而不是成功触发，应该够用了，
要精确的判定成功触发其实会很麻烦

**Comment by nirvanaxiao6** [comment]
很少会有人做出取消的动作吧。
而且这种不过是个误差项，我觉得无伤大雅，为了修正小误差而做出大改动我觉得不值

**Comment by voidcl** [comment]
ok，那就这么做了，其实我担心的主要不是V取消的问题，而是一些需要蓄力的技能或者特殊触发条件的技能，快速点击鼠标一次都成功触发不了，但是计数疯狂++
