### ISSUE TITLE
[Bug] Items will not show their info bar in the GUI of AC machines

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#683]
**Describe the bug**
Just look at the screenshots below.

First one is in AC machine, and the second is in IC2 machine

**To Reproduce**

**Expected behavior**

**Screenshots**
![2019-01-06_15 54 44](https://user-images.githubusercontent.com/13258510/50733654-36172d80-11cc-11e9-88a8-3b6ee9d6ccc6.png)

![2019-01-06_15 54 59](https://user-images.githubusercontent.com/13258510/50733605-788c3a80-11cb-11e9-9f8f-efe9e1c837c7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - MC Version and Forge version: 2768
 - Version 1.1.0_beta2

**Additional context**

**Comment by Paindar** [comment]
Merged into #644 .

**Comment by nirvanaxiao6** [comment]
emmmmm
我觉得这个和NEI没啥关系吧，这是个单独的问题
反正没修 我open了，等到修完了再close掉好了
