### ISSUE TITLE
[Bug] Problems of WorldGen

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#684]
**Describe the bug**
Using World Stripper, I found that WorldGen has some problem.

codes:
        AcademyCraft/src/main/java/cn/academy/worldgen/ACWorldGen.java

For example, constraint_metal will generate between y = 60 and y = 24. But in the following screenshot, you can see the y = 24 line(using wool) and ores of constraint_metal below 24(also wool)

Its size also has some problem. It's too small than what's in the code.

**To Reproduce**

**Expected behavior**

**Screenshots**
![2019-01-06_16 09 23](https://user-images.githubusercontent.com/13258510/50733705-7034ff00-11cd-11e9-917a-182e588f436c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - MC Version and Forge version: [e.g. 14.23.4.2705-1.12.2]
 - Version [e.g. 1.1.0beta1]

**Additional context**

**Comment by Paindar** [comment]
经确认，之前的说法有误。
正确的说法是：
