### ISSUE TITLE
[Idea] Sort out the items in the NEI

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#685]
**Is your feature request related to a problem? Please describe.**
It's like a chaos. The ores are divided by machines and machines are divided by items.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Paindar** [comment]
没法修，也没必要修。
这是JEI的排序规则导致的，和AC无关。
Close.
