### ISSUE TITLE
[Bug] Can't open UI for lots of machines in server 

### ISSUE THREAD

**Issue by sheng-ri** [LambdaInnovation/AcademyCraft#686]
红圈内机械可打开，其余皆不可且右键交互会使背包物品顺序改变
图在下面
文：
可打开：
方块
  能源桥 (IC2 EU输入)
  能源桥 (IC2 EU输出)
  基础能力开发机
 物品：
  便携能力开发机
  御坂云终端

不可：
 太阳能能量发生机
 改良无线虚能节点
 无线虚能矩阵
 能力干涉方块
 虚相位能量发生机
 虚能融合机
 金属处理机
 风力能量发生器 - 主机
 风力能量发生器 - 支架底座
 高级无线虚能节点
 高级能力开发机

更多信息
 - OS: Windows Server 2016
 - CatServer version pro(free)-181231 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2796)
 - 1.1.0beta2

**Comment by WeAthFoLD** [comment]
Duplicate of #679, and fixed.

**Comment by nirvanaxiao6** [comment]
NOT fixed：1.1.0_beta3
上述列表中仅有高级能力开发机在beta3中可以打开

国内/外玩家均反馈未修复
我在自己电脑的服务器上测的是可以开的..真是绝了
