### ISSUE TITLE
[Bug] Solar Generator will stop working when covered with water.

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#692]
**Describe the bug**
Only when it's covered with water, it will stop working.
While with other liquid covering, it will not stop., such as lava, imag flux liquid and uu matters.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - MC Version and Forge version: [e.g. 14.23.4.2705-1.12.2]
 - Version [e.g. 1.1.0beta1]

**Additional context**

**Comment by Paindar** [comment]
这是MC的锅，我们通过调用(block.pos+(0,1,0)).canSeeSky()这个方法判断能否工作。既然MC认为上面覆盖一层水就看不到天空...那我们....
