### ISSUE TITLE
Change of AbilityData's skill-exp mechanism

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#7]
We have just changed the setting to let a skill to be learned(upgraded) multiple times. So change the mechanism to the following:
Every time exp incr and meets the next integer(that is, able to get to a new skill level), ignore any further attempts to incr skill exp, and enable skill learning in GUI.(AbilityData should provide a method canSkillUpgrade(int)).
Also for wrapping purpose we should provide a getSkillLevel(int sid) function doing the floor internally.

**Comment by acaly** [comment]
Created field of skill level in AbilityData. 337869e490d5d08326ad7dae18eb35dd0b44f7b7.
Now it is the Category that is responsible to handle skill expr change event. Maybe we should make an api in SkillBase.

**Comment by acaly** [comment]
Added in 63a5629f198604f7276c40bb68763e446656ec05.
