### ISSUE TITLE
[Bug] Scattering Bomb causes client crash

### ISSUE THREAD

**Issue by Darkveld** [LambdaInnovation/AcademyCraft#708]
Charging up scattering bomb works fine, but releasing it causes a crash, log below:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2019-01-15 18:24:25 MST
Description: Unexpected error

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at com.google.common.collect.Iterators$3.next(Iterators.java:174)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:616)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1347)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 3 total; [EntityPlayerSP['Darkveld'/16136518, l='MpServer', x=53.18, y=70.00, z=201.77], EntityOtherPlayerMP['blazeash'/16587965, l='MpServer', x=99.76, y=88.50, z=289.05], EntityOtherPlayerMP['Hunyol'/14931859, l='MpServer', x=53.34, y=70.00, z=199.59]]
  Chunk stats: MultiplayerChunkCache: 441, 441
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (96,64,208), Chunk: (at 0,4,0 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 20353545 game time, 22990469 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 151 total; [EntitySkeleton['Skeleton'/16910599, l='MpServer', x=96.50, y=69.00, z=151.50], EntitySkeleton['Skeleton'/16905992, l='MpServer', x=25.30, y=67.47, z=155.30], EntityOtherPlayerMP['blazeash'/16587965, l='MpServer', x=99.76, y=88.50, z=289.05], EntityBat['Bat'/16911133, l='MpServer', x=40.40, y=53.88, z=124.14], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=82.17, y=67.33, z=375.17], EntityBat['Bat'/16911136, l='MpServer', x=119.81, y=39.51, z=278.15], EntityBat['Bat'/16897317, l='MpServer', x=30.25, y=52.10, z=188.34], EntityZombie['Zombie'/16906021, l='MpServer', x=86.50, y=24.00, z=276.50], EntityMdBall['entity.EntityMdBall.name'/16911663, l='MpServer', x=51.93, y=69.24, z=201.53], EntityBat['Bat'/16892207, l='MpServer', x=-18.63, y=52.10, z=229.63], EntitySkeleton['Skeleton'/16906037, l='MpServer', x=132.50, y=74.00, z=167.50], Menelaos Pantagiota/loneshepherd_byzantine/7672453668505097430/-45/71/99, EntitySpider['Spider'/16907064, l='MpServer', x=105.50, y=72.00, z=171.50], EntityOtherPlayerMP['blazeash'/16587965, l='MpServer', x=99.76, y=88.50, z=289.05], EntityCyberZombie['Cyberzombie'/6625318, l='MpServer', x=86.70, y=28.09, z=153.30], EntitySkeleton['Skeleton'/16910162, l='MpServer', x=42.50, y=67.00, z=256.50], EntityItem['item.item.cyberware.katana'/16906578, l='MpServer', x=59.26, y=64.00, z=221.38], EntityItem['item.item.skull.skeleton'/16906580, l='MpServer', x=58.90, y=64.00, z=220.98], EntitySkeleton['Skeleton'/16910174, l='MpServer', x=52.50, y=16.00, z=158.50], EntityZombieVillager['Zombie Villager'/16910175, l='MpServer', x=49.55, y=16.00, z=157.75], EntitySkeleton['Skeleton'/16905055, l='MpServer', x=-15.50, y=67.00, z=233.50], EntitySkeleton['Skeleton'/16903518, l='MpServer', x=-0.68, y=65.00, z=230.27], EntityZombieVillager['Zombie Villager'/16910176, l='MpServer', x=50.47, y=16.00, z=158.00], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=72.12, y=5.00, z=-67.47], EntityTippedArrow['Arrow'/5009444, l='MpServer', x=28.14, y=69.04, z=165.00], EntityBat['Bat'/16910701, l='MpServer', x=80.54, y=48.14, z=130.54], EntityMdRaySmall['unknown'/263284, l='MpServer', x=52.77, y=71.63, z=202.48], EntityMdRaySmall['unknown'/263285, l='MpServer', x=52.77, y=71.74, z=202.78], EntityPlayerSP['Darkveld'/16136518, l='MpServer', x=53.18, y=70.00, z=201.77], EntityMdRaySmall['unknown'/263286, l='MpServer', x=52.77, y=71.74, z=202.78], EntityMdRaySmall['unknown'/263287, l='MpServer', x=52.08, y=71.34, z=202.40], EntityZombie['Zombie'/16901492, l='MpServer', x=124.50, y=17.00, z=211.50], EntityMdRaySmall['unknown'/263281, l='MpServer', x=52.94, y=71.75, z=202.58], EntityMdRaySmall['unknown'/263282, l='MpServer', x=52.94, y=71.75, z=202.58], EntityMdRaySmall['unknown'/263283, l='MpServer', x=52.77, y=71.63, z=202.48], EntityMdRaySmall['unknown'/263292, l='MpServer', x=52.56, y=70.56, z=200.85], EntityMdRaySmall['unknown'/263293, l='MpServer', x=52.41, y=70.65, z=202.57], EntityFancyItemFrame['Clear Item Frame'/634, l='MpServer', x=75.97, y=71.50, z=192.50], EntityMdRaySmall['unknown'/263294, l='MpServer', x=52.41, y=70.65, z=202.57], EntityFancyItemFrame['Clear Item Frame'/635, l='MpServer', x=75.97, y=72.50, z=196.50], EntityBat['Bat'/16899450, l='MpServer', x=53.31, y=23.41, z=153.85], EntityWolf['Wolf'/636, l='MpServer', x=78.83, y=70.00, z=184.22], EntityMdRaySmall['unknown'/263288, l='MpServer', x=52.08, y=71.34, z=202.40], EntityWolf['Wolf'/637, l='MpServer', x=80.05, y=70.00, z=185.20], EntityMdRaySmall['unknown'/263289, l='MpServer', x=51.93, y=70.84, z=201.53], EntityWolf['Wolf'/638, l='MpServer', x=75.52, y=70.00, z=186.70], EntityMdBall['entity.EntityMdBall.name'/16911740, l='MpServer', x=52.56, y=68.96, z=200.85], EntityMdRaySmall['unknown'/263290, l='MpServer', x=51.93, y=70.84, z=201.53], EntityWolf['Wolf'/639, l='MpServer', x=64.72, y=73.00, z=187.86], EntityBat['Bat'/16888702, l='MpServer', x=23.66, y=43.10, z=128.99], EntityMdRaySmall['unknown'/263291, l='MpServer', x=52.56, y=70.56, z=200.85], EntitySkeleton['Skeleton'/16892295, l='MpServer', x=15.27, y=70.00, z=236.47], EntityOtherPlayerMP['Hunyol'/14931859, l='MpServer', x=249.46, y=67.69, z=549.12], EntityBat['Bat'/16895892, l='MpServer', x=80.56, y=31.80, z=160.44], EntityCreeper['Creeper'/16854423, l='MpServer', x=127.86, y=23.00, z=275.80], EntitySpider['Spider'/16908702, l='MpServer', x=86.50, y=68.00, z=140.50], EntityCyberZombie['Cyberzombie'/2441400, l='MpServer', x=86.03, y=28.48, z=153.61], EntityTippedArrow['Arrow'/5014252, l='MpServer', x=26.19, y=69.02, z=161.88], EntityMdBall['entity.EntityMdBall.name'/16911265, l='MpServer', x=52.94, y=70.15, z=202.58], EntitySpider['Spider'/16908713, l='MpServer', x=25.50, y=69.00, z=151.50], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=143.70, y=62.94, z=715.44], EntityZombie['Zombie'/16881604, l='MpServer', x=105.50, y=69.00, z=150.50], EntityMdBall['entity.EntityMdBall.name'/16911819, l='MpServer', x=52.41, y=69.05, z=202.57], EntityPig['Pig'/718, l='MpServer', x=115.46, y=68.00, z=223.75], EntityItem['item.item.rottenFlesh'/16910285, l='MpServer', x=86.88, y=27.00, z=140.13], EntityTippedArrow['Arrow'/944862, l='MpServer', x=26.88, y=70.04, z=205.28], EntityZombie['Zombie'/16906722, l='MpServer', x=79.50, y=74.00, z=267.50], EntityOtherPlayerMP['Hunyol'/14931859, l='MpServer', x=53.34, y=70.00, z=199.59], EntityMdBall['entity.EntityMdBall.name'/16911350, l='MpServer', x=52.77, y=70.03, z=202.48], EntitySpider['Spider'/16906748, l='MpServer', x=127.50, y=34.00, z=276.50], EntitySkeleton['Skeleton'/16871945, l='MpServer', x=125.50, y=67.00, z=225.27], EntityZombie['Zombie'/16911882, l='MpServer', x=-15.50, y=64.00, z=192.50], EntityHorse['Horse'/13245379, l='MpServer', x=49.42, y=69.00, z=184.99], EntitySkeleton['Skeleton'/16911883, l='MpServer', x=-9.50, y=64.00, z=193.50], EntityBolt['entity.bolt.name'/780, l='MpServer', x=61.59, y=69.04, z=168.55], EntityBolt['entity.bolt.name'/781, l='MpServer', x=59.79, y=70.03, z=156.20], EntityBat['Bat'/16897040, l='MpServer', x=61.35, y=10.20, z=234.19], EntityItem['item.item.cyberware.leg_upgrades.jump_boost'/16905749, l='MpServer', x=52.82, y=64.00, z=218.84], EntitySkeleton['Skeleton'/16902166, l='MpServer', x=89.50, y=38.00, z=146.50], EntityCreeper['Creeper'/16907301, l='MpServer', x=40.48, y=38.00, z=124.78], EntitySkeleton['Skeleton'/16907303, l='MpServer', x=41.50, y=41.00, z=131.50], EntityTippedArrow['Arrow'/5020011, l='MpServer', x=27.21, y=68.03, z=167.21], EntitySkeleton['Skeleton'/16907302, l='MpServer', x=41.50, y=41.00, z=135.50], EntityBat['Bat'/16910384, l='MpServer', x=34.25, y=29.09, z=236.75], EntityPig['Pig'/819, l='MpServer', x=-19.71, y=74.00, z=278.11], EntityBat['Bat'/16910385, l='MpServer', x=41.79, y=30.05, z=234.94], EntityHorse['Dan'/820, l='MpServer', x=47.85, y=69.00, z=185.11], EntityZombie['Zombie'/16900149, l='MpServer', x=15.50, y=66.00, z=240.50], EntityOtherPlayerMP['blackstar5623'/16309043, l='MpServer', x=404.32, y=72.00, z=875.70], EntityPig['Pig'/822, l='MpServer', x=95.82, y=69.00, z=137.78], EntityPig['Pig'/823, l='MpServer', x=97.55, y=69.00, z=128.29], EntityChicken['Chicken'/825, l='MpServer', x=80.88, y=70.00, z=123.16], EntityCyberZombie['Cyberzombie'/16899642, l='MpServer', x=132.52, y=72.00, z=200.80], EntityPig['Pig'/833, l='MpServer', x=15.93, y=82.00, z=278.52], EntityPig['Pig'/834, l='MpServer', x=11.37, y=78.00, z=278.45], EntityPig['Pig'/835, l='MpServer', x=12.55, y=79.00, z=278.50], EntityZombie['Zombie'/16905282, l='MpServer', x=73.50, y=45.00, z=135.50], EntityPig['Pig'/836, l='MpServer', x=14.94, y=82.00, z=278.39], EntityCyberZombie['Cyberzombie'/16885319, l='MpServer', x=110.50, y=73.51, z=260.17], EntityBolt['entity.bolt.name'/841, l='MpServer', x=54.08, y=65.04, z=219.01], EntityBolt['entity.bolt.name'/842, l='MpServer', x=58.44, y=70.67, z=211.95], EntityBolt['entity.bolt.name'/843, l='MpServer', x=58.41, y=70.72, z=211.95], EntityWolf['Wolf'/846, l='MpServer', x=82.47, y=70.00, z=191.06], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=130.97, y=4.54, z=-69.58], EntityCreeper['Creeper'/16907346, l='MpServer', x=50.53, y=37.00, z=137.81], EntityMdBall['entity.EntityMdBall.name'/16911441, l='MpServer', x=52.77, y=70.14, z=202.78], EntityTippedArrow['Arrow'/5005080, l='MpServer', x=24.71, y=68.04, z=162.57], EntityCreeper['Creeper'/16907861, l='MpServer', x=-24.22, y=51.00, z=240.52], EntitySkeleton['Skeleton'/16907860, l='MpServer', x=-22.50, y=52.00, z=243.50], EntityCyberZombie['Cyberzombie'/16909401, l='MpServer', x=131.30, y=17.00, z=235.70], EntityZombie['Zombie'/16907868, l='MpServer', x=122.50, y=35.00, z=280.50], EntityOtherPlayerMP['levineron'/12035004, l='MpServer', x=216.63, y=107.00, z=-85.29], EntityOtherPlayerMP['Hunyol'/14931859, l='MpServer', x=53.34, y=70.00, z=199.59], EntityZombie['Zombie'/16871538, l='MpServer', x=109.50, y=70.00, z=150.50], EntityZombie['Zombie'/16882805, l='MpServer', x=43.50, y=38.00, z=125.18], EntityCreeper['Creeper'/16902773, l='MpServer', x=16.50, y=69.00, z=136.82], EntityZombie['Zombie'/6629651, l='MpServer', x=85.70, y=28.19, z=154.70], EntityCreeper['Creeper'/16909435, l='MpServer', x=11.50, y=68.00, z=122.50], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=70.80, y=5.00, z=-67.46], EntitySkeleton['Skeleton'/16893057, l='MpServer', x=1.50, y=70.00, z=163.50], EntitySlime['Slime'/16368504, l='MpServer', x=236.93, y=5.00, z=-77.22], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=71.43, y=5.00, z=-67.55], EntityOtherPlayerMP['levineron'/12035004, l='MpServer', x=181.36, y=5.00, z=-55.48], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=70.53, y=5.00, z=-67.48], EntitySpider['Spider'/16902801, l='MpServer', x=86.50, y=32.00, z=171.50], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=69.58, y=5.00, z=-67.43], EntityZombie['Zombie'/16911507, l='MpServer', x=125.50, y=34.00, z=281.50], EntityZombie['Zombie'/16903828, l='MpServer', x=128.75, y=76.00, z=254.44], EntityZombie['Zombie'/16911508, l='MpServer', x=123.70, y=34.00, z=275.47], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=67.11, y=5.00, z=-67.41], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=131.39, y=5.14, z=-70.59], EntityZombie['Zombie'/16911526, l='MpServer', x=-11.63, y=64.00, z=177.26], EntityZombie['Zombie'/16911527, l='MpServer', x=-15.50, y=64.00, z=173.50], EntityZombie['Zombie'/16899238, l='MpServer', x=87.63, y=35.00, z=164.30], EntityZombie['Zombie'/16911525, l='MpServer', x=-15.50, y=64.00, z=174.50], EntityBat['Bat'/16906408, l='MpServer', x=121.52, y=12.07, z=222.71], EntityZombie['Zombie'/16911528, l='MpServer', x=-14.50, y=64.00, z=170.50], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=55.50, y=69.00, z=206.50], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=131.75, y=5.00, z=-68.44], EntitySkeleton['Skeleton'/16904376, l='MpServer', x=80.50, y=35.00, z=153.50], EntityCreeper['Creeper'/16912568, l='MpServer', x=80.50, y=26.00, z=131.50], EntityBat['Bat'/16906426, l='MpServer', x=96.35, y=46.56, z=143.54], EntityOtherPlayerMP['Mophise'/14812376, l='MpServer', x=63.50, y=5.00, z=-67.66], EntityZombie['Zombie'/16909006, l='MpServer', x=108.50, y=69.00, z=123.50], EntityZombie['Zombie'/16909007, l='MpServer', x=114.30, y=69.00, z=129.19], EntityTippedArrow['Arrow'/5023647, l='MpServer', x=28.39, y=68.96, z=155.99], EntityBat['Bat'/16907996, l='MpServer', x=54.48, y=18.97, z=160.53], EntityMdBall['entity.EntityMdBall.name'/16911583, l='MpServer', x=52.08, y=69.74, z=202.40], EntityOtherPlayerMP['Hunyol'/14931859, l='MpServer', x=374.33, y=64.00, z=756.02], EntityTippedArrow['Arrow'/5008807, l='MpServer', x=24.03, y=67.69, z=166.55], EntityOtherPlayerMP['levineron'/12035004, l='MpServer', x=218.23, y=62.00, z=-85.30]]
  Retry entities: 77 total; [EntitySlime['Slime'/16368504, l='MpServer', x=236.93, y=5.00, z=-77.22], EntityPig['Pig'/12035248, l='MpServer', x=282.72, y=120.00, z=-164.82], EntitySheep['Sheep'/12033855, l='MpServer', x=193.26, y=87.00, z=-19.39], EntitySheep['Sheep'/12033854, l='MpServer', x=188.52, y=113.00, z=-56.18], EntityWitch['Witch'/16372467, l='MpServer', x=154.50, y=32.00, z=-44.50], EntityWitch['Witch'/16372466, l='MpServer', x=156.50, y=32.00, z=-43.50], EntityChicken['Chicken'/12033978, l='MpServer', x=273.21, y=92.00, z=-59.86], EntitySlime['Slime'/16368503, l='MpServer', x=251.39, y=5.00, z=-84.37], EntityItem['item.item.arrow'/16360811, l='MpServer', x=183.88, y=107.00, z=-118.13], EntitySkeleton['Skeleton'/16339564, l='MpServer', x=164.50, y=42.00, z=-22.50], EntitySheep['Sheep'/12035232, l='MpServer', x=141.48, y=114.00, z=-50.23], EntityPig['Pig'/12035247, l='MpServer', x=276.49, y=119.00, z=-156.70], EntityItem['item.item.egg'/16332005, l='MpServer', x=249.86, y=76.00, z=-57.88], EntityItem['item.item.cyberware.jacket'/16371943, l='MpServer', x=220.56, y=9.00, z=-87.64], EntityItem['item.item.bone'/16370777, l='MpServer', x=204.13, y=69.00, z=-72.53], EntityItem['item.item.arrow'/16370776, l='MpServer', x=204.33, y=71.00, z=-71.73], EntityChicken['Chicken'/12033942, l='MpServer', x=264.45, y=89.00, z=-58.50], EntitySheep['Sheep'/12033941, l='MpServer', x=232.45, y=99.00, z=-38.47], EntitySheep['Sheep'/12033812, l='MpServer', x=169.51, y=116.00, z=-61.28], EntitySheep['Sheep'/12033940, l='MpServer', x=242.52, y=94.00, z=-36.50], EntitySheep['Sheep'/12033811, l='MpServer', x=165.45, y=87.00, z=-38.35], EntitySheep['Sheep'/12033939, l='MpServer', x=233.87, y=90.00, z=-31.55], EntitySheep['Sheep'/12033810, l='MpServer', x=168.51, y=82.00, z=-33.73], EntitySheep['Sheep'/12033938, l='MpServer', x=250.73, y=97.00, z=-94.51], EntitySheep['Sheep'/12033809, l='MpServer', x=175.52, y=92.00, z=-39.20], EntitySheep['Sheep'/12033808, l='MpServer', x=157.50, y=84.00, z=-24.27], EntityItem['item.item.bone'/16370000, l='MpServer', x=157.94, y=88.00, z=-130.88], EntitySheep['Sheep'/12033950, l='MpServer', x=257.93, y=101.00, z=-70.50], EntityChicken['Chicken'/12033948, l='MpServer', x=249.80, y=76.00, z=-57.50], EntityItem['item.item.bone'/16370389, l='MpServer', x=171.88, y=75.00, z=-113.41], EntitySkeleton['Skeleton'/16358356, l='MpServer', x=156.50, y=37.00, z=-26.50], EntityItem['item.item.arrow'/16370388, l='MpServer', x=171.72, y=75.00, z=-113.87], EntityChicken['Chicken'/12033946, l='MpServer', x=260.14, y=101.00, z=-70.89], EntitySheep['Sheep'/12033945, l='MpServer', x=257.90, y=101.00, z=-67.59], EntitySheep['Sheep'/12033944, l='MpServer', x=258.49, y=100.00, z=-63.27], EntitySheep['Sheep'/12033669, l='MpServer', x=208.22, y=113.00, z=-43.66], EntitySheep['Sheep'/12033668, l='MpServer', x=205.76, y=113.00, z=-47.48], EntityItem['item.item.arrow'/16369999, l='MpServer', x=158.47, y=88.00, z=-130.16], EntityBat['Bat'/16370497, l='MpServer', x=154.43, y=33.46, z=-45.40], EntityBat['Bat'/16331971, l='MpServer', x=175.75, y=20.63, z=-72.09], EntityBat['Bat'/16370499, l='MpServer', x=166.13, y=32.03, z=-49.59], EntitySheep['Sheep'/12035082, l='MpServer', x=150.19, y=99.00, z=-41.51], EntitySheep['Sheep'/12035081, l='MpServer', x=149.57, y=98.00, z=-37.10], EntitySheep['Sheep'/12035080, l='MpServer', x=159.90, y=88.00, z=-32.78], EntityCreeper['Creeper'/16356795, l='MpServer', x=205.70, y=31.00, z=-63.97], EntityCreeper['Creeper'/16340922, l='MpServer', x=255.50, y=94.00, z=-94.50], EntitySheep['Sheep'/12033904, l='MpServer', x=208.66, y=111.00, z=-41.06], EntityBat['Bat'/16376624, l='MpServer', x=157.66, y=32.40, z=-52.05], EntityBat['Bat'/16376626, l='MpServer', x=157.70, y=32.07, z=-51.58], EntityBat['Bat'/16376628, l='MpServer', x=157.45, y=33.64, z=-50.53], EntityCyberSkeleton['Cyberskeleton'/16365097, l='MpServer', x=205.27, y=32.00, z=-66.47], EntityCreeper['Creeper'/16319908, l='MpServer', x=263.50, y=78.00, z=-172.50], EntityCreeper['Creeper'/16369959, l='MpServer', x=146.50, y=33.00, z=-59.50], EntityCreeper['Creeper'/16364199, l='MpServer', x=267.50, y=19.00, z=-72.50], EntityCreeper['Creeper'/16364198, l='MpServer', x=263.50, y=19.00, z=-71.50], EntityItem['item.item.rottenFlesh'/16331034, l='MpServer', x=227.13, y=67.00, z=-87.13], EntityItem['item.item.egg'/16336144, l='MpServer', x=274.77, y=85.00, z=-61.60], EntityXPOrb['Experience Orb'/16351753, l='MpServer', x=225.25, y=9.50, z=-84.79], EntityZombie['Zombie'/16367752, l='MpServer', x=262.53, y=17.00, z=-81.20], EntitySkeleton['Skeleton'/16320651, l='MpServer', x=205.13, y=31.00, z=-64.75], EntitySheep['Sheep'/12033861, l='MpServer', x=217.27, y=96.00, z=-29.50], EntityXPOrb['Experience Orb'/16351755, l='MpServer', x=226.43, y=11.50, z=-80.47], EntitySheep['Sheep'/12033860, l='MpServer', x=202.20, y=92.00, z=-36.50], EntityXPOrb['Experience Orb'/16351754, l='MpServer', x=225.25, y=9.50, z=-84.73], EntityXPOrb['Experience Orb'/16356749, l='MpServer', x=193.73, y=96.00, z=-128.64], EntitySheep['Sheep'/12033859, l='MpServer', x=221.79, y=83.00, z=-72.49], EntityXPOrb['Experience Orb'/16356748, l='MpServer', x=191.41, y=95.00, z=-128.49], EntitySheep['Sheep'/12033858, l='MpServer', x=199.29, y=112.00, z=-51.49], EntitySheep['Sheep'/12033857, l='MpServer', x=218.52, y=114.00, z=-45.55], EntityXPOrb['Experience Orb'/16356750, l='MpServer', x=193.75, y=96.00, z=-129.93], EntitySheep['Sheep'/12033856, l='MpServer', x=207.79, y=113.00, z=-49.51], EntityItem['item.item.cyberware.shades2'/16354177, l='MpServer', x=196.13, y=98.00, z=-121.88], EntitySkeleton['Skeleton'/16336515, l='MpServer', x=174.49, y=19.00, z=-73.99], EntityBasalz['Basalz'/16367749, l='MpServer', x=263.50, y=16.00, z=-83.50], EntitySkeleton['Skeleton'/16336516, l='MpServer', x=191.21, y=25.00, z=-64.49], EntityZombie['Zombie'/16367751, l='MpServer', x=267.50, y=16.00, z=-82.50], EntityBasalz['Basalz'/16367750, l='MpServer', x=264.62, y=16.00, z=-79.66]]
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

**Comment by WeAthFoLD** [comment]
Duplicate with #636
