### ISSUE TITLE
[Bug] Other player cann't see MineRay effect.

### ISSUE THREAD

**Issue by Paindar** [LambdaInnovation/AcademyCraft#717]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - MC Version and Forge version: [e.g. 14.23.4.2768-1.12.2]
 - Version [e.g. 1.1.0beta4-adae07]

**Additional context**

**Comment by WeAthFoLD** [comment]
Fixed during beta. QA can reconfirm whether it's been fixed.
