### ISSUE TITLE
[Bug] 重置能力导致崩溃

### ISSUE THREAD

**Issue by ztmzzz** [LambdaInnovation/AcademyCraft#729]
用能力诱导因子重置能力时会崩溃
1.1.0_beta5

**Comment by Paindar** [comment]
请附上详细的崩溃报告(crash_report)

**Comment by nirvanaxiao6** [comment]
无法复现
请您在1月31日23:59前提供具体的crash-report，否则我们将关闭该issue

**Comment by ztmzzz** [comment]
[crash-2019-01-28_12.38.32-server.txt](https://github.com/LambdaInnovation/AcademyCraft/files/2816583/crash-2019-01-28_12.38.32-server.txt)

**Comment by WeAthFoLD** [comment]
@voidcl 接锅
