### ISSUE TITLE
[Bug] Shift-clicking an full stack of output out of a machine voids items if you have a partial stack in the first available slot

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#731]
**Describe the bug**
When shift clicking outputs out of the metal former or imag fusor, if the first available slot has a large enough stack that the combined total of the inventory stack and the output stack exceeds 64, it will void any output in excess of 64, rather than making a new stack.

**To Reproduce**
1. Process materials in any machine
2. have a partial stack in the first available slot in your inventory large enough that the processed materials will complete the stack, with extra to spare.
3. Shift-click the outputs out of the machine
4. Tested with the Metal Former and the Imag Fusor

**Expected behavior**
The items in excess of completing the first stack should start a new stack, not get voided.

**Screenshots**
Stack of 63 constraint metal plates in the first slot, 2 constraint metal plates in the Metal Former Output:
![2019-01-30_13 38 48](https://user-images.githubusercontent.com/11600141/52011198-8d8b7f00-2494-11e9-8f6b-446b833dc598.png)
Shift clicking the 2 plates out of the Metal former, adds one to the stack in the inventory for a full 64, and voids the second:
![2019-01-30_13 38 58](https://user-images.githubusercontent.com/11600141/52011199-8d8b7f00-2494-11e9-9a6f-7068743065fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MC Version and Forge version: 14.23.5.2808-1.12.2
 - Version 1.1.0beta_5
 - Tested in Singleplayer and in a LAN hosted on another machine.

**Additional context**
For instance, with 24 needles in on my hotbar, in slot 1, and 60 in the output of the metal former, shift-clicking the needles out voids 20, giving me a single stack of 64. Same thing happens for iron ingots as well.

Having two partial stacks in your inventory, will still only fill one and void the excess. i.e. a stack of 24 and a stack of 1 in slots 1 and 2 of the hotbar, respectively, with 60 in the output, will void 20, giving a stack of 64, and leaving the stack of 1 alone.

If the hotbar is full, it will prioritize the bottom-most row, going left to right.

As a side note, it also will always shift click the items into the first available slot, even if there is a stack of that item already in your inventory. Might be related.

**Comment by WeAthFoLD** [comment]
Fixed.
