### ISSUE TITLE
[Bug] dir blast destroy boxes

### ISSUE THREAD

**Issue by Shizuri23** [LambdaInnovation/AcademyCraft#740]
Server has been started to prevent explosion

**Comment by nirvanaxiao6** [comment]
Cannot understand what you mean.
Using Chinese is also acceptable.

**Comment by Shizuri23** [comment]
就是 配置文件已经开了防炸，但是基束冲击依然能够破坏

**Comment by LemADEC** [comment]
Explosion are disabled but blocks are still removed?
