### ISSUE TITLE
[Bug] Long running server now having constant crashes

### ISSUE THREAD

**Issue by Darkveld** [LambdaInnovation/AcademyCraft#741]
After running a server since the first beta updates, getting the below error with the mod installed even with no one online, error goes away after removing Academycraft

Error doesn't resolved itself by installing beta 6

Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
    at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:691)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:223)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: world
  All players: 0 total; []
  Chunk stats: ServerChunkCache: 45 Drop: 0
  Level seed: 4655362806987790371
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 0 game time, 0 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

**Comment by WeAthFoLD** [comment]
Does it affect gameplay?

**Comment by Darkveld** [comment]
Server can no longer run for more then 2-5 minutes before crash.

Even running it locally no longer works.

**Comment by WeAthFoLD** [comment]
I'm a bit confused about the timepoint that this bug appears. Do you mean that the bug exists ever since beta1, and still exists now?

**Comment by WeAthFoLD** [comment]
Closing as no further updates.
