### ISSUE TITLE
[Bug] 手持便捷能力开发机后，使用技能（电流回冲）时，按V会技能清空，且无法使用

### ISSUE THREAD

**Issue by 1798643961** [LambdaInnovation/AcademyCraft#743]
**Describe the bug**

手持便捷能力开发机后，使用技能（电流回冲）时，按V会是技能清空，且无法使用

**Comment by WeAthFoLD** [comment]
使用蓄力类技能时，V键功能更换为取消当前技能使用。在CP条上也有UI提示，属于固有设计。
