### ISSUE TITLE
[Bug] Can't use Freq Transmitter App in MP

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#748]
具体表现为：在点击节点或矩阵，需要对SSID和密码进行验证。输入密码回车后，会显示“验证中……”并停留几秒，随后显示操作超时（无论密码是否正确）。因此导致无法正常使用频率变送器

version：AcademyCraft 1.1.0

**Comment by zeldacl** [comment]
Need update to newest LambdaLib2
