### ISSUE TITLE
[Bug] Incorrect and incompatible dependencies set in Curse Forge

### ISSUE THREAD

**Issue by JadianRadiator** [LambdaInnovation/AcademyCraft#751]
**Describe the bug**
You have these two mods set as optional dependencies in the 1.12.2 build.
They are not available on 1.12.2
[MineTweaker3](https://minecraft.curseforge.com/projects/minetweaker3) has migrated more then a year ago to [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker).
[Not Enough Items](https://minecraft.curseforge.com/projects/222211) doesn't even have a 1.12.2 port.
It's been replaced entirely by [Just Enough Items](https://minecraft.curseforge.com/projects/jei).
The closest you can get to NEI on 1.12.2, is JEI with an addon mod that adds NEI stuff to JEI.

**To Reproduce**

1. Go to https://minecraft.curseforge.com/projects/academycraft/files/2682190
2. Technically all you need is step one. But if you want proof, look at the mc versions that the aforementioned incompatible mods support

**Expected behavior**
Technically irrelevant.
But I expected the mod author to correctly set it's (optional) dependencies.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
Irrelevant
 - MC Version and Forge version: [e.g. 14.23.4.2705-1.12.2]
Irrelevant
 - Version [e.g. 1.1.0beta1]
Semi irrelevant.
It's the info set to 1.1.0 for mc 1.12.2
But the bug/error is explicitly in the file page for it, and **_not_** the mod its self.
[Forge File ID 2682190](https://minecraft.curseforge.com/projects/academycraft/files/2682190)

**Additional context**

**Comment by WeAthFoLD** [comment]
Updated the dependency.
