### ISSUE TITLE
[Bug] Bug Title

### ISSUE THREAD

**Issue by TopFormula** [LambdaInnovation/AcademyCraft#757]
当我超能力过载时，透明方块（包括菜单，背包，物品栏，草方块）都看不见了，只能重启客户端才能恢复，我试着退回到主界面，结果主界面显示的是我退出时看见的画面，所有按键都看不见

**Comment by WeAthFoLD** [comment]
Duplicate with #711
下次提交时可以先开谷歌翻译看下现有的issue
