### ISSUE TITLE
[Bug] Server Crash upon using Vector Reflection against Guardians

### ISSUE THREAD

**Issue by KamiSami** [LambdaInnovation/AcademyCraft#759]
**Describe the bug**
Endless loop of errors and server crash when using vector reflection against guardians or waiting them to attack you with their beam. It is possible this happens to anyone when using against someone with thorns, unsure though, i don't have my friend often playing in my server to test it out. Attack guardian with punch for example with vector reflection on when they have spikes grown.

**To Reproduce**
Use vector reflection against guardians

**Expected behavior**
Reflecting damage to guardian without endless error loop

**Screenshots**
Unable to explain/show with screenshot, see link at bottom for crash report

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate
 - MC Version and Forge version: forge-14.23.5.2815 Minecraft 1.12.2
 - Version AcademyCraft 1.1.1

**Additional context**
Here is crash report link https://pastebin.com/svvBCdjz

**Comment by WeAthFoLD** [comment]
A infinite recursion has occured :/

**Comment by WeAthFoLD** [comment]
Fixed.
