### ISSUE TITLE
Double UI Appearance, causing abilites to behave abnormally.

### ISSUE THREAD

**Issue by Galvarino** [LambdaInnovation/AcademyCraft#769]
I'm not exactly sure why this has come about, but for some reason, the ability UI (what comes up when you are using your ability) Is doubled in a strange way, causing most abilities to not function at all.
![image](https://user-images.githubusercontent.com/31280096/54571493-4f510d00-49b9-11e9-8a03-b9952954f80c.png)
At first I thought this may be because of the many mods I've added with UI's on the same screen, but after running this in another world, everything actually worked fine. So I believe my world may have been corrupted or something... Either way, I'm wondering if there is a potential cause for this or a potential way to fix it. I am running version 1.07 of AcademyCraft on Minecraft 1.7.10.

**Comment by WeAthFoLD** [comment]
Sorry but the 1.7.10 version is not maintained anymore. If you find this issue popping up in 1.1.x version in case you play it in the future, please file a new issue. Thanks for your support!  （￣▽￣）
