### ISSUE TITLE
[Bug] "Cannot find addon dependency 316472"

### ISSUE THREAD

**Issue by Laurelai** [LambdaInnovation/AcademyCraft#773]
When installing a modpack i made that included academycraft the install failed with the error "Cannot find addon dependency 316472" when academycraft was removed from the modpack install proceeded as normal without error.

**Expected behavior**
I expected the install to work

 - OS: windows 10
 - MC Version and Forge version: 1.12.2 , forge-14.23.5.2815
 - Version AcademyCraft 1.1.1

**Comment by Ruchian** [comment]
That's an issue with the Twitch Client. It is unable to grab a file (could be temporarily) for some reason.
I don't think the devs of a mod can help you with this. You can try to manually download LambdaLib2 from [the Curseforge download page](https://minecraft.curseforge.com/projects/lambdalib/files) and add it to the mods folder.

**Comment by Sitheau** [comment]
I looked up the addon number on curseforge and apparently its for their plugin called "cat server" but it has since been removed for whatever reason, I have no idea why its marked as a dependency though

**Comment by Ruchian** [comment]
I think that, after taking another look at it, that I have the same problem, though the error is different.
Any pack I try to Import on Twitch that contains AcademyCraft 1.1.1(not LambdaLib, only the main mod), won't install. Twitch gives the error "An exception has occured: Curse.Radium.InstallManagement.InstallTaskFailedException"
It doesn't speak of any dependancies however. As Laurelai says, removing AcademyCraft before importing the profile fixes the issue. In other words, a profile must be exported without AcademyCraft and then have the user manually add AcademyCraft to the instance themselves.

The only dependancy the mod has is LambdaLib. (a dependancy is basically a core mod)

**Comment by Ruchian** [comment]
It seems twitch has silently fixed the issue. (at least for me)
You need to confirm whether or not you still have problems with importing a modpack that contains academycraft 1.1.1.

**Comment by nirvanaxiao6** [comment]
Duplicated with #782 . Further discussion can be done there.
