### ISSUE TITLE
[Bug] Client Crash when using Thunderbolt on End Dragon

### ISSUE THREAD

**Issue by CmdrJane** [LambdaInnovation/AcademyCraft#774]
Using Electromaster Thunder bolt on Ender Dragon causes Internal Server shutdown and application could become unresponsive.

Console log: https://pastebin.com/SrMK4kaS

Academy Craft 1.1.1
Minecraft 1.12.2

**Comment by Ruchian** [comment]
Duplicate of #772 
(just helping the devs sort issues)

**Comment by nirvanaxiao6** [comment]
Deplicated. And thanks @Ruchian  for your help :)
