### ISSUE TITLE
[Bug] 装有高级虚能核心的无线矩阵的连接范围与描述不符

### ISSUE THREAD

**Issue by VXF2016** [LambdaInnovation/AcademyCraft#778]
**Describe the bug**
装有高级虚能核心的无线矩阵的传输范围标示为42，但创造模式测试下只有17格的传输范围

**To Reproduce**
高级无线虚能节点   ---连接-->   装有高级虚能核心的无线矩阵

**Expected behavior**
null

**Screenshots**
![2019-03-30_15 13 09](https://user-images.githubusercontent.com/17941855/55273054-dd55bd80-5300-11e9-8147-74e65a54fca7.png)
（每隔四个铁块一个海晶灯，铁块柱子边上是图中唯一可以连接的无线矩阵）
![2019-03-30_15 13 26](https://user-images.githubusercontent.com/17941855/55273068-07a77b00-5301-11e9-98d9-ce30ef776760.png)
![2019-03-30_15 13 33](https://user-images.githubusercontent.com/17941855/55273069-08401180-5301-11e9-897b-47a1240b0fac.png)
![2019-03-30_15 13 51](https://user-images.githubusercontent.com/17941855/55273070-08401180-5301-11e9-92ed-8f6a47cd861f.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - MC Version and Forge version: 14.23.5.2811-1.12.2
![image](https://user-images.githubusercontent.com/17941855/55273091-3faebe00-5301-11e9-8a82-cb531693b828.png)

 - Version  1.1.1

**Additional context**
基础无线虚能节点只能在更近的地方连接  装有高级虚能核心的无线矩阵
其他虚能核心未测试
存档：
[实验基地.zip](https://github.com/LambdaInnovation/AcademyCraft/files/3025231/default.zip)

**Comment by Ruchian** [comment]
Used google translate to translate this. (Sorry if I misunderstand)
If I get this right, you're saying that the Wireless Imag Matrix and the Metal Former are within a correct range of 42, and yet for some reason cannot connect. Tell me if I am not correct. xd?

I tested the distancess.
The Wireless Imag Matrix with an Advanced Core has a max range of 41, not 42 as the interface claims.
![AcademyCraft Range test](https://user-images.githubusercontent.com/24900404/55283086-e1aac680-5352-11e9-9673-179ad8a86684.png)
I used Advanced Nodes in this test, which have a range of 19 each. (This is correct)

I suspect the confusion here is that the range drops when angled. If you go one block lower or one to the side, the range shrinks. You need to look at the line. Distance away from the matrix as a vector in cubes.
One down, so 18 left.

A machine like the Metal Former can only connect to a Node, so at max a distance of 19 away from the Node. Nodes can connect to Nodes and spread power, but only so long as they are within a distance of 41 away from the Wireless Imag Matrix these Nodes use.

This makes me wonder if it is possible to connect Nodes to multiple Wireless Imag Matrixes, to continue on in a longer connection range. (maybe an idea for the developers)

On your picture, the node is 17 blocks away from the Imag Matrix, and the machines are 17 or 18 blocks away from the node.

**Comment by VXF2016** [comment]
> Used google translate to translate this. (Sorry if I misunderstand)
> If I get this right, you're saying that the Wireless Imag Matrix and the Metal Former are within a correct range of 42, and yet for some reason cannot connect. Tell me if I am not correct. xd?

I was saying that the Wireless Imag Matrix and the  Advanced Nodes can only connect in the range of 17(or maybe 19). they should be able to connect in the range of 42.

Besides, maybe I should translate my comment to English? But my English is not good, and I do not know the name of these blocks in English.

**Comment by nirvanaxiao6** [comment]
Well, I tested it. And the result is that only when the matrix is in the distance which the node can reach. That's a bug I think.

As for the multiple matrix connections, now every matrix is an isolated system, and I think one matrix is enough for almost all situations when you only play with AcademyCraft. 
But we are trying to improve this Wireless Energy System so that it can be used in some other mods like IC2 to simplify the connections between machines and generations. When the improvement come true, your point is the best choice to deal with the problem of long distance of energy transformation.

**Comment by VXF2016** [comment]
> I should correct my answer. It's not a bug actually.
> When you only have one node trying to connect to the matrix, the distance must be less than the range of the node. But when you have multiple nodes to connect, the farther nodes can be connected to the matrix only when it's in the range of the other node which has been connected to the matrix (Also, in the range of matrix) . Actually, the farther nodes connect the matrix through the closer ones.

ok,I know it now. To connect a node to the matrix at the max distance, it needs to connect nodes to the matrix one by one. 
But since it needs to connect one by one, why it can't just connect a node to another node without the matrix?

**Comment by Ruchian** [comment]
(a bit surprised no one else answered this xD)
Sorry for the late answer.

The Wireless Imag Matrix creates a network. (where the nodes can connect to)
The nodes do not have a network like this on their own, meaning Nodes can only connect to machines without the matrix around. This means that your power buffer will be limited to 1 Node and that you machines and power generator need to be near each other.

The Matrix basically bypasses this limit and allows Nodes to connect to eachother, so long as they're in the Same Network, within the Matrix's field of 41 blocks distance.

(So basically the Nodes are doing the connecting and the Imag Matrix is just a network provider)
