### ISSUE TITLE
[Bug] Server/World Crashes on Launch

### ISSUE THREAD

**Issue by Moranlos** [LambdaInnovation/AcademyCraft#781]
**Describe the bug**
I'm no good at deciphering crash reports, but it's almost certainly a compatibility thing. The server crashes every time I attempt to launch it, and when the world file was copied to singleplayer it crashed as well. It is in a relatively large modpack, but AcademyCraft was listed as the source so I'm posting it here.

**To Reproduce**
As I don't know the cause of the error, I don't know how to reproduce it.

**Expected behavior**
I would expect the server to hopefully not crash when launching a world.

**Crash Logs**
[crash-2019-04-05_11.47.58-server.txt](https://github.com/LambdaInnovation/AcademyCraft/files/3048903/crash-2019-04-05_11.47.58-server.txt)
[crash-2019-04-05_11.38.08-server.txt](https://github.com/LambdaInnovation/AcademyCraft/files/3048905/crash-2019-04-05_11.38.08-server.txt)
The first log is for client, the second is for the server. For some reason, the server's report's formatting is awful.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MC Version and Forge version: 14.23.5.2814-1.12.2
 - Version 1.1.1

**Additional context**
The server had been working fine since the mod's release and I've only just started having major issues.

**Comment by Moranlos** [comment]
Even if this is a problem on my end, any help fixing it would be greatly appreciated.

**Comment by Ruchian** [comment]
The error reads: "java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=connected, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateMachine{block=mekanism:machineblock, properties=[active, facing, recipe, tier, type]}"

I'm not too sure what you did, but were you perhaps connecting a universal cable to an academycraft node?

I'll try to read the crash reports for you a bit. xD
References in the crash report:
https://github.com/mekanism-mod/Mekanism/blob/1.12/src/main/java/mekanism/common/block/states/BlockStateMachine.java
Affected block: Mekanism // MachineBlock
Seems to agrue with: Node Wireless Energy system. 'something' cannot tell if it is connected or not. (as in, using the 'connected' property from a Node.)
https://github.com/LambdaInnovation/AcademyCraft/blob/a5d59d2a4c469be2fa3f74f6a065a8afeb329bb2/src/main/java/cn/academy/block/block/BlockNode.java
