### ISSUE TITLE
[Bug] Config is regenerated every time

### ISSUE THREAD

**Issue by MasterEnderman** [LambdaInnovation/AcademyCraft#785]
**Describe the bug**
You can't tweak the configs (for example disable ore generation) because every time you launch the game the config file is regenerated with the default values.

**To Reproduce**
1. Change some Configs in academy.cfg
2. Start the Game
3. Check academy.cfg
4. See that all configs have the default value again

**Expected behavior**
save changed configs and don't reset them

**Desktop (please complete the following information):**
 - OS: Windows
 - MC Version and Forge version: 14.23.5.2835-1.12.2
 - Version 1.1.1

**Comment by Ruchian** [comment]
Cannot repeat.
> Tested this with  Forge 14.23.5.2836 (minecraft 1.12.2)
> AcademyCraft 1.1.1, LambdaLib 2 0.1.8, Just Enough Items 1.12.2-4.15.0.277

My configs save regularly. (I disabled oregen succesfully, it generates no ores. I disabled liquid succesfully as well, no liquids generated. I rechecked the academycraft.cfg config file, it saved everything I set that way.)

Sorry, I think this is something on your end. Make sure the file is not read-only, or in use by something else when saving.
