### ISSUE TITLE
雷击之枪在攻击其他mod生成的怪物时会断开服务器

### ISSUE THREAD

**Issue by justicebear** [LambdaInnovation/AcademyCraft#787]
游戏版本1.12.2
Forge version 14.23.5.2815
后台无报错，在主世界一个区域内连续释放会概率性的断开
重连后此区域每次释放都会断开。

在服务器导入的地图内，使用这个技能攻击怪物后会断开服务器。
非常喜欢这个mod希望能解决这个问题
![QQ截图20190413224624](https://user-images.githubusercontent.com/49587685/56081458-2436cd80-5e40-11e9-92e6-8d38ba7fa0ae.jpg)

**Comment by Ruchian** [comment]
(I used google translate, sorry if I misunderstood.)
Using lightning skill (electromaster) on a 'boss' mob causes a crash?

Sounds a lot like #549, #772 and #774.
If I understood it correctly, it's known at least. ;p

**Comment by nirvanaxiao6** [comment]
Duplicated with #772 .I will pin that issue later.

**Comment by justicebear** [comment]
thanks！




------------------ 原始邮件 ------------------
发件人: "Ruchia"<notifications@github.com>;
发送时间: 2019年4月16日(星期二) 凌晨1:54
收件人: "LambdaInnovation/AcademyCraft"<AcademyCraft@noreply.github.com>;
抄送: "?"<justicebear@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [LambdaInnovation/AcademyCraft] 雷击之枪在攻击其他mod生成的怪物时会断开服务器 (#787)




(I used google translate, sorry if I misunderstood.)
 Using lightning skill (electromaster) on a 'boss' mob causes a crash?
 
Sounds a lot like #549, #772 and #774.
 If I understood it correctly, it's known at least. ;p
