### ISSUE TITLE
[Idea] API for Adding Music Tracks? 提供API加更多音樂? 

### ISSUE THREAD

**Issue by Rongmario** [LambdaInnovation/AcademyCraft#788]

**Comment by nirvanaxiao6** [comment]
Actually it did have. You can find it at .minecraft/acmedia.

**Comment by Rongmario** [comment]
Thank you!

**Comment by Ruchian** [comment]
Just to be clear here ;p The ogg (music) files need to go in the source folder in acmedia.

**Comment by Rongmario** [comment]
@Ruchian thank you, I got it ^^
