### ISSUE TITLE
[Bug] AcademyCraft前置LambdaLib2 0.1.8與llibrary-core-1.0.11-1.12.2有衝突

### ISSUE THREAD

**Issue by leoowo** [LambdaInnovation/AcademyCraft#790]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CorePlugin (LambdaLib2-0.1.8.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/18/19 1:39 AM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:870)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:269)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:870)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:269)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)

-- Affected level --
Details:
	Level name: 新的世界--------
	All players: 1 total; [EntityPlayerMP['leo007123'/2975, l='新的世界--------', x=984.11, y=77.10, z=-383.09]]
	Chunk stats: ServerChunkCache: 573 Drop: 11
	Level seed: -2712989885017639420
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (244,64,180), Chunk: (at 4,4,4 in 15,11; contains blocks 240,0,176 to 255,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 17796 game time, 5052 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 106383 (now: false), thunder time: 138142 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 645859312 bytes (615 MB) / 2766524416 bytes (2638 MB) up to 6407585792 bytes (6110 MB)
	JVM Flags: 21 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -Xmx6144m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=50 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2835 Optifine OptiFine_1.12.2_HD_U_E3 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                          | Signature                                |
	|:------ |:--------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2835.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2835             | forge-1.12.2-14.23.5.2835.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | LambdaLib|Core        | 0.1.8                    | minecraft.jar                                   | None                                     |
	| LCHIJA | lambdalib2            | 0.1.8                    | LambdaLib2-0.1.8.jar                            | None                                     |
	| LCHIJA | academy               | 1.1.1                    | AcademyCraft-1.1.1.jar                          | None                                     |
	| LCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | jei                   | 4.15.0.277               | jei_1.12.2-4.15.0.277.jar                       | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                        | None                                     |
	| LCHIJA | twilightforest        | 3.9.888                  | twilightforest-1.12.2-3.9.888-universal.jar     | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                | None                                     |
	| LCHIJA | extrautils2           | 1.0                      | extrautils2-1.12-1.8.1.jar                      | None                                     |
	| LCHIJA | flyringbaublemod      | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e (1).jar | None                                     |
	| LCHIJA | autoreglib            | 1.3-26                   | AutoRegLib-1.3-26.jar                           | None                                     |
	| LCHIJA | bibliocraft           | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| LCHIJA | bookshelf             | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | cfm                   | 5.4.1                    | cfm-5.4.1-mc1.12.2.jar                          | None                                     |
	| LCHIJA | chesttransporter      | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| LCHIJA | codechickenlib        | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cookingforblockheads  | 6.4.70                   | CookingForBlockheads_1.12.2-6.4.70.jar          | None                                     |
	| LCHIJA | elevatorid            | 1.3.8                    | ElevatorMod-1.12.2-1.3.8.jar                    | None                                     |
	| LCHIJA | eplus                 | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage          | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | erebus                | 1.0.29                   | Erebus-1.0.29.jar                               | None                                     |
	| LCHIJA | fairylights           | 2.1.5                    | fairylights-2.1.5-1.12.2.jar                    | None                                     |
	| LCHIJA | llibrary              | 1.7.18                   | llibrary-1.7.18-1.12.2 (1).jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil                | 8.0.0                    | fossilsarcheology-8.0.0.jar                     | None                                     |
	| LCHIJA | grimoireofgaia        | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar              | None                                     |
	| LCHIJA | iceandfire            | 1.7.1                    | iceandfire-1.7.1-1.12.2 (1).jar                 | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                     | None                                     |
	| LCHIJA | miniheads             | 1.0.7                    | miniheads-1.0.7a-1.12.jar                       | None                                     |
	| LCHIJA | mob_grinding_utils    | 0.3.13                   | MobGrindingUtils-0.3.13.jar                     | None                                     |
	| LCHIJA | recipehandler         | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar           | None                                     |
	| LCHIJA | nei                   | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | pixelmon              | 7.0.5                    | Pixelmon-1.12.2-7.0.5-universal.jar             | None                                     |
	| LCHIJA | psi                   | r1.1-74                  | Psi-r1.1-74.jar                                 | None                                     |
	| LCHIJA | flammpfeil.slashblade | mc1.12-r20               | SlashBlade-mc1.12-r20.jar                       | None                                     |
	| LCHIJA | slashblade_addon      | 1.1.0                    | SJAP-1.1.0.jar                                  | None                                     |
	| LCHIJA | taiga                 | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                          | None                                     |
	| LCHIJA | tinkertoolleveling    | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
	| LCHIJA | lastsmith             | @version@                | TLS-V1.2.6.1-MC1.12.2.jar                       | None                                     |
	| LCHIJA | torohealthmod         | 1.12.2-11                | torohealth-1.12.2-11.jar                        | None                                     |
	| LCHIJA | waystones             | 4.0.53                   | Waystones_1.12.2-4.0.53.jar                     | None                                     |
	| LCHIJA | xcustomizedblade      | 1.60                     | XCustomizedBlade.TinyCore.1.12.2.VER1.60.jar    | None                                     |
	| LCHIJA | slashbladetic         | V1.0.6.1-MC1.12.2        | SlashBladeTic-V1.0.6.1-MC1.12.2.jar             | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CorePlugin (LambdaLib2-0.1.8.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['leo007123'/2975, l='新的世界--------', x=984.11, y=77.10, z=-383.09]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Ruchian** [comment]
According to information on Forge, it's a crash that happens for some people, but only with Forge version 14.23.5.2835. Forge's team already fixed it in forge version 14.23.5.2836
Suggestion: Update Forge and try again to see if it still happens.
