### ISSUE TITLE
[Nya] Discord activity

### ISSUE THREAD

**Issue by KamiSami** [LambdaInnovation/AcademyCraft#800]
Hi =w= I wanted to just make a message here since it appears to be hard to message you guys without being heard of as it seems none of you are very active in discord, so please feel free to drop by~ I dropped one message in Discord for developers as i am tiny bit worried, but i hope you guys understand. -With all love-

**Comment by WeAthFoLD** [comment]
No worries, we are still on the project :) It's just that some of our team members are having some real-life issues (graduation papers etc., XD), so developement is paused for some weeks. Now that most of us are free again, we will resume developement.
