### ISSUE TITLE
Rendering screen error

### ISSUE THREAD

**Issue by Stormbender0025** [LambdaInnovation/AcademyCraft#803]
I am trying to play Academy craft 1.7.10 bu i am always getting a null pointer exception that says rendering screen. All the files are up to date and my pc specs are given below:
intel i7 6th gen 2.00 ghz processor, 16 gb ram windows 10 64 bit.

The crash report can be found on this link: https://pastebin.com/zmwMUBrj
I am not running any other mods right now.

Thanks for the help in advanced!!

**Comment by Ruchian** [comment]
xiao6 will likely close this with the message: 1.7.10 is no longer going to be updated and supported. Please use the newer 1.12.2 version of this mod or something along those lines.

However, I took a quick look through your crash log and notice you haven't installed LambdaLib. This is a required mod for AcademyCraft on 1.7.10. 
[download it here](https://www.curseforge.com/minecraft/mc-mods/lambdalib/files/2321336)

**Comment by Stormbender0025** [comment]
Hey thanks for the help I will upgrade??
