### ISSUE TITLE
找不到lambdalib2-0.1.9.pom

### ISSUE THREAD

**Issue by EstamelGG** [LambdaInnovation/AcademyCraft#834]
如题，在命令行构建的时候提示无法下载lambdalib2-0.1.9.pom。尝试自行搜索也没有结果。

**Comment by MasterShihoChief** [comment]
Their site is down as well as whatever was hosting that dependency. I would love to try and merge the PR submitted yesterday, however we can't build the project without that lambdalib pom and I haven't found it yet

**Comment by LeLe570929726** [comment]
The private maven repository has downed. So you need to build and install LambdaLib2 by yourself.

**Comment by Paindar** [comment]
0.1.9 is a local verion, try dependencies 0.1.8
