### ISSUE TITLE
使用带有群体攻击伤害的超能力攻击某些实体导致断开连接

### ISSUE THREAD

**Issue by mr-cat-s** [LambdaInnovation/AcademyCraft#842]
**Describe the bug**
在twilightforest mod的维度中使用超能力攻击boss导致断开连接
但我并未进行多人游戏!!!
分析:
我认为所有群体攻击技能攻击一个由多个实体构成的生物(例如末影龙)都会造成 断开连接
因为单体攻击技能并不会造成 bug

**To Reproduce**
1. 单人游戏至暮色森林维度
2. 使用 雷击之枪 技能攻击 九头蛇BOSS 
3. 游戏屏幕卡住
4. 返回多人游戏界面提示:XXX lost connection: 连接中止

**Desktop (please complete the following information):**
 - OS:Windows
 - MC Version 1.12.2 ,Forge version 14.23.5.2847(最新)
 - ModVersion 1.1.2

**Comment by Ruchian** [comment]
Related to #772, #774, #787, and #549 
This issue is unfortunately known for a while now, but weathfold has been quiet about it.
It's very specific to when you use thunderbolt.

**Comment by zeldacl** [comment]
fix in v1.1.3
