### ISSUE TITLE
[Idea] 游戏的数值平衡有一定的问题

### ISSUE THREAD

**Issue by letdo1945** [LambdaInnovation/AcademyCraft#857]
电击使太强了，亲测lv5的电击使可以一小时速通暮色森林，建议做一下削弱，传送使应该强化一下攻击系技能；然后是有很多技能对上一个技能对熟练度有较高的要求，尤其是一些不怎么实用的技能（如光盾）练起来就很麻烦，如果不靠指令的话有的职业甚至已经到lv5了却只学了两三个技能（如原子崩坏）；能力诱导因子很难找，目前我开了四个存档找了几十处遗迹但是只在箱子里找到了两个超炮s的op

**Comment by Kanbe-Kotori** [comment]
mod之间的数值联动问题建议自己调整。
技能的伤害，消耗，过载，学习速度等都可以通过编辑config文件夹内的academy-craft-data.conf来调整。
