### ISSUE TITLE
[Bug] 1.12.2版本，forge版本是2847

### ISSUE THREAD

**Issue by letdo1945** [LambdaInnovation/AcademyCraft#858]
电击使在暮色森林（版本为3.10.1013）中打有血条的boss（如娜迦、九头蛇等）时使用雷击之枪技能击中boss时游戏会瞬间卡出去，并提示“连接已丢失”（单机模式）并退回到多人服务器列表,该bug的触发概率为百分之百

**Comment by zeldacl** [comment]
fix in 1.1.3
