### ISSUE TITLE
[NOT A BUG] 清除所有能打开百科链接的渠道

### ISSUE THREAD

**Issue by ChromaPIE** [LambdaInnovation/AcademyCraft#870]
最开始的恶意编辑：https://ac.li-dev.cn/wiki/index.php?title=%E9%A6%96%E9%A1%B5&type=revision&diff=352404&oldid=349306

弃用归弃用，玩家仍然可以通过官网进入这个百科，请把这些渠道处理掉。

**Comment by nirvanaxiao6** [comment]
已将中文界面中导航栏的“百科”连接至mcmod.cn
（不过mcmod的ac首页还有个本来的百科 真的不会套娃么（
