### ISSUE TITLE
[Bug] Non Update Mod and AcademyCraft conflict?

### ISSUE THREAD

**Issue by ghost** [LambdaInnovation/AcademyCraft#879]
**Describe the bug**
Install the two mods AcademyCraft and Non-Update Mod at the same time, and the message in the screenshot appears.
同時安裝AcademyCraft與Non-Update Mod兩個mod 出現截圖裡的訊息

**To Reproduce**
Not applicable.
不適用

**Expected behavior**
I don't understand what information needs to be provided. But I think I might need the update URL of the AcademyCraft Mod.
我不明白要提供甚麼訊息 但是我想我需要AcademyCraft的檢測新版本網址

**Screenshots**
![image](https://user-images.githubusercontent.com/56864151/107224947-1f023400-6a53-11eb-9f5f-eaf3cc21d2b7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - MC Version and Forge version: Minecraft 1.12.2, Forge 14.23.5.2854
 - Version: AcademyCraft 1.1.3

**Additional context**
如果可以的話 我希望我可以得知AcademyCraft模組的更新檢測網址
If I can, I hope I can know the update URL of the AcademyCraft Mod.

**Comment by Paindar** [comment]
In .minecraft/config/academy.cfg, generic - analysis, set to false:

> generic {
    # switch for analytic system [default: true]
    B:analysis=false
