### ISSUE TITLE
电击使的磁场控制问题！

### ISSUE THREAD

**Issue by asd995840846** [LambdaInnovation/AcademyCraft#885]
https://user-images.githubusercontent.com/80281518/127190265-11471059-1887-4fb0-941c-98cd8e877735.mp4

录视频没有出现物品丢出去会消失，平时对铁块使用经常消失无踪/铁块也一样，技能动画飘来飘去

**Comment by zeldacl** [comment]
AC 版本是多少？

**Comment by asd995840846** [comment]
MC1.12.2&nbsp; &nbsp; AC 1.1.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月2日(星期四) 凌晨0:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LambdaInnovation/AcademyCraft] 电击使的磁场控制问题！ (#885)





 
AC 版本是多少？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Paindar** [comment]
磁场控制吞方块是老BUG了，暂时没什么办法， 建议考虑技改
