### ISSUE TITLE
游戏闪退

### ISSUE THREAD

**Issue by dom-kital** [LambdaInnovation/AcademyCraft#887]
版本:1.12.2
系统: x86_64 Linux 5.13.12-arch1-1
安装了Forge:14.23.5.2855版本和HD_U_G5

> Mod:AcademyCraft-1.1.3-1

>报错log:
    error :

AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by nirvanaxiao6** [comment]
百度搜索该报错log易知这不是AC的锅，同时你也可以找到各种自己就能做的解决方案
比如这个：https://www.mcbbs.net/thread-1056886-1-1.html

善用百度 谢谢
