### ISSUE TITLE
[1.7.10] There was a critical exception handling a packet on channel AcademyCraft

### ISSUE THREAD

**Issue by Zarvera** [LambdaInnovation/AcademyCraft#888]
**Describe the bug**
I was playing for a few days like usual until the instance suddenly froze, haviing me kill it. Upon any attempt to load save now internal server shuts down almost instantly with no crash report or anything, but i see in the logs a lot of errors from AcademyCraft. Link to the log below

**To Reproduce**
I'm not sure it's entirely reproducable. It played fine for a few days.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MC Version: 1.7.10
 - Forge version:  10.13.4.1614
 - Version 1.0.7

**Additional context**
The log: https://pastebin.com/6FpBJDM4

**Comment by Paindar** [comment]
There are no longer any update for Academy Craft for 1.7.10, my suggestion is trying 1.12.2, or ignoring this crash if it sometimes happens.

**Comment by Zarvera** [comment]
Understandable. 
By the way, on 1.7.10 version,  Shift Teleport seems to not work at all, it won't place any block no matter what key the skill is bound to or what block is held, and so it does not do any damage either, doesn't receive EXP and just blocks further abilities and the class is kinda broken as a result. Is there any known workarounds? I can't seem to find anything at all in google

**Comment by Paindar** [comment]
I vaguely remember this bug...But i don't remember how to solve it...
Is there any error log? It may be helpful.

**Comment by Zarvera** [comment]
I'm checking out log while trying to cast ST and no, there doesn't seems to be anything in the latest.log besides occasional stall-report announcement. One non-fatal "fatal" error at lambdalib popped up but that was just some weird glitch with the ST outline stuck getting rendered wherever i look at even when i turn ability-casting mode off. :(

**Comment by Paindar** [comment]
Just now i checked out my backup code. Actually i have no idea, and i'm not sure if it's a bug or mod comflict. 
Seems like trying Academy Craft for 1.12.2 or using console command is the only suggestion i'm able to give now.

**Comment by Zarvera** [comment]
Ah well. I was recently playing a 1.17 pack and one magic mod was completely blocked from functioning by another mod that was  just adding a ladder and a rope. 😄  I guess i'll just try finding ability induction factor to reroll. Unfortunately "just updating" is not an option, as i'm playing with a very new for me and large Chinese mod that is very interesting but is for 1.7.10 only
Anyway, thank you for helping!
