### ISSUE TITLE
[Idea] Your Request

### ISSUE THREAD

**Issue by ZXLQ114514** [LambdaInnovation/AcademyCraft#893]
非常不幸的是，学园都市原作者已确认去世（悼。。。并致敬），发催更和问题反馈已经没有用了。。。
默哀

This mod author has confirmed death, and there will be no feedback on issue feedback and requests for updates
Silence

**Comment by nirvanaxiao6** [comment]
虽然这是事实，但我认为你跑到github来提个issue只为了彰显你知道了消息这件事非常的滑稽和不礼貌。
